### ISSUE TITLE
SQL Server Connection String Generated with $guid2$

### ISSUE THREAD

**Issue by pnewhook** [OmniSharp/generator-aspnet#102]
k runtime version: 1.0.0-beta3
generator version: 0.0.31

After running `yo aspnet` and selecting web application my project was generated. The connection string in config.json contains $guid2$ which I assume should be turned into a real GUID?

```
{
    "Data": {
        "DefaultConnection": {
            "ConnectionString": "Server=(localdb)\\mssqllocaldb;Database=aspnet5-<namespace>-$guid2$;Trusted_Connection=True;MultipleActiveResultSets=true"
        }
    },
    ...
}
```

**Comment by peterblazejewicz** [comment]
These are VS template params.
Let's call: @spboyer

**Comment by sayedihashimi** [comment]
Lol oops, yeah $guid*$ should create a new guid.

**Comment by spboyer** [comment]
#110 Submitted needs review

**Comment by spboyer** [comment]
#110 merged - closing issue.

**Comment by sayedihashimi** [comment]
@spboyer thanks for fixing and merging.
