### ISSUE TITLE
[Add] Move Mocha to development dependencies in package.json

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#103]
I've read a wiki note added by @sayedihashimi .
https://github.com/OmniSharp/generator-aspnet/wiki/how-to-run-test-cases-locally

We just need to add `devDependencies` section just like here:
https://github.com/yeoman/generator-generator/blob/master/package.json#L33-L36
and simply instruct people to run `npm install` as the `yeoman-generator` and `chalk` are already included by core dependencies.

This will make a note in the wiki cleaner and shorter.

Are you OK with this guys?

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz I'm an npm noob, this looks like it would be much better.

+1

**Comment by peterblazejewicz** [comment]
@sayedihashimi ready to go

note: I've changed title to better mark purpose of issue (actually - we already have mocha, but simply in wrong section)
