### ISSUE TITLE
Generate without bootstrap

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/generator-aspnet#105]
I am wondering if there is anything in the works to add support to generate projects without bootstrap? Thanks

**Comment by peterblazejewicz** [comment]
I assume that Bootstrap is still part of content generated by upcoming VS:
http://www.asp.net/mvc/overview/getting-started/introduction/getting-started
I'd rather stick with this, adopting other features and integrations as they appear. I think the first will be Angular SPA example with TypeScript once it appears in VS
We could create other content for vNext easily and quickly, I think:
https://github.com/peterblazejewicz/vnext-web-starter-kit
as MVC is quite versatile platform. Google WST is top notch one to consider.

**Comment by spboyer** [comment]
@jrock2004 is there another framework that you were looking to use in lieu of bootstrap? or just not have bootstrap in the templates? You can always remove the reference from bower.json and the associated .html

**Comment by jrock2004** [comment]
I have a home baked responsive grid that I use and for the rest I like to style it myself.

**Comment by spboyer** [comment]
i would suggest removing the reference and run `kpm restore`

**Comment by jrock2004** [comment]
That you remove boot strap from the wwwroot folder?

**Comment by spboyer** [comment]
if you remove the bootstrap ref from the bower.json file, when the grunt task is run as a part of the `kpm restore` it will clean the wwwroot folder and then the bootstrap resources will no longer be put there.

**Comment by xtianus79** [comment]
@jrock2004 what type of setup of dependencies would you like exactly?

**Comment by jrock2004** [comment]
With things like grunt and gulp having the js and css dep in wwwroot seems like it should not be. I guess its just me and maybe not everyone else

**Comment by peterblazejewicz** [comment]
> With things like grunt and gulp having the js and css dep in wwwroot seems like it should not be. I guess its just me and maybe not everyone else

I agree, but things are in flux in VS so to say :)

**Comment by xtianus79** [comment]
@jrock2004 are you saying the replication of those dependencies in the wwwroot should not be there?  Yes it seems a bit awkward and has caused a great deal of planning to get around the issue in my particular build.  I have been waiting to see how things pan out and there has been a lot of code changes as of lately so I think it is time for another update.  

But, to answer your question directly - the choice of having  a project started without bootstrap is up to you.  You can control the grunt and or gulp files and corresponding dependencies how you wish. If there is a particular group of dependencies you would like to see you can let me know and I will see what I can do for you.

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
