### ISSUE TITLE
Remove peerDependencies declaration

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#118]
The `peerDependencies` section is deprecated. When installing generator under recent Node/Npm and Yo users will receive:
```
$ npm install -g generator-aspnet
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator
-aspnet will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
generator-aspnet@0.0.32 C:\Users\PIBL\AppData\Roaming\npm\node_modules\generator
-aspnet
[...]
```
It was removed from template genarator project already:
https://github.com/yeoman/generator-generator/commit/14d39bc78a675742e5590b769a8d527fba81fa1f

Should we wait with this change or implement it to avoid spilling too much warnings at users when installing generator?

**Comment by sayedihashimi** [comment]
Sounds good to me.
