### ISSUE TITLE
Where does the lodash namespace get defined in certain subgenerators like StartupClass?

### ISSUE THREAD

**Issue by xtianus79** [OmniSharp/generator-aspnet#122]
I see <%= namespace => but i don't know how that is ever triggered?

**Comment by peterblazejewicz** [comment]
> I see <%= namespace => but i don't know how that is ever triggered?

It's set when user is prompted for application name:

https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L98-L102

**Comment by spboyer** [comment]
It's passed whenever `this.template()` is called inside the templatedata var. like here https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L119

**Comment by xtianus79** [comment]
yes but when I run the subgenerator how does that affect that? I am running it and it just leaves <%= this behind

**Comment by spboyer** [comment]
It is not implemented in the subgenerators, nor is the <%= namespace %> token in any of the subgenerator templates. They are hard coded as "MyNamespace"

**Comment by xtianus79** [comment]
@spboyer https://github.com/OmniSharp/generator-aspnet/blob/master/templates/startup.cs#L4 this just may be a one off but I was wondering.

**Comment by spboyer** [comment]
Looks like that subgenerator has a bug, should be implemented like the WebApiController for example. https://github.com/OmniSharp/generator-aspnet/blob/master/WebApiController/index.js

**Comment by xtianus79** [comment]
ok... I wanted to add some functions but they sub-generators seemed very specific to just creating a file. 

would some added functionality be beneficial... especially for certain files?

**Comment by spboyer** [comment]
Create a new issue stating what the "new/additional" functionality is and let everyone chime in.

**Comment by xtianus79** [comment]
sounds good. 
when you said this. 

> Looks like that subgenerator has a bug, should be implemented like the WebApiController for example. https://github.com/OmniSharp/generator-aspnet/blob/master/WebApiController/index.js

isn't that just a general name?  would a prompt be better to establish context?
