### ISSUE TITLE
Add .gitignore subgenerator

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#125]
For new project creation we create a ```.gitignore``` file. There are cases where users will need to create that file after the project has been created (i.e. they modified it and want to go back to square one, or they created with an older version). To enable this we should create a new subgenerator that users can use. The content should be the same as the new project case.

Related to #112

**Comment by peterblazejewicz** [comment]
When added you guys should promote it on every occasion - that's a little, nifty feature, kind of generator making `puffs` :D

**Comment by xtianus79** [comment]
I wanted to know what was the methodology of this generator... meaning will it be based off of the script-base.js file?  

If so, I wanted to ask what was the benefit of having the generators tied to that file.  I am finding it hard to globally scope variables to run functions from the subgenerators index.js file.
