### ISSUE TITLE
Update contribution docs with section about code style

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#130]
@sayedihashimi 
I've modified project Wiki with section describing basic information about code styles used in project:
https://github.com/OmniSharp/generator-aspnet/wiki/How-to-Contribute/_compare/e76771410a719273f70f0eb36590f2c25e5b45e2%5E...e76771410a719273f70f0eb36590f2c25e5b45e2
Would you mind reviewing?

**Comment by sayedihashimi** [comment]
@peterblazejewicz it looks great, thanks for adding that.

One thing that we may want to add is a statement to use ```git diff --check``` to ensure no whitespace errors are added. Thoughts?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 

> One thing that we may want to add is a statement to use git diff --check to ensure no whitespace errors are added. 

I've never used it. I'm using `.gitattributes` to manage newline between systems and linters to enforce white space (only if required by project, for example we are using strict enforced white space linters in [https://github.com/marionettejs](https://github.com/marionettejs) repositories - even as part of tests).
I think adding `.gitattributes` to automatically manage newlines will be enough. Other spaces are part of tooling and we are providing `.editorconfig` as help. `git-fix-whitespace` requires manual installation and is not really Windows friendly I think.

**Comment by sayedihashimi** [comment]
Ok thanks. Adding .gitattributes sounds like a good idea 💡. I haven't tried the white space enforcement/fixes myself.

**Comment by peterblazejewicz** [comment]
Assumed LGTM by Sayed first comment, the ticket was for reviewing purposes.
Thanks!
