### ISSUE TITLE
beta4: add class lib and console templates

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#136]
We should add a class lib and console generators, contents available at https://dl.dropboxusercontent.com/u/40134810/OmniSharp/classlib-console.zip

**Comment by chrisdias** [comment]
sorry, didnt know i had the power to close an issue :)

**Comment by sayedihashimi** [comment]
@chrisdias I may have to remove it :)

**Comment by sayedihashimi** [comment]
I'm having machine issues so I've assigned this to @spboyer

**Comment by spboyer** [comment]
Complete. Committed to beta4 branch.  in /templates/projects/classlib & /templates/projects/console
