### ISSUE TITLE
branch: beta4 kqueue() FileSystemWatcher has reached the maximum nunmber of files to watch.

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#138]
in web template getting the following error

```
$ dnx . kestrel
```

Browse to http://localhost:5001

```
An unhandled exception occurred while processing the request.

IOException: kqueue() FileSystemWatcher has reached the maximum nunmber of files to watch.
System.IO.KqueueMonitor.Add (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>, line 0

System.IO.KqueueMonitor.Add (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>
System.IO.KqueueMonitor.Scan (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>
System.IO.KqueueMonitor.Setup () [0x00000] in <filename unknown>
System.IO.KqueueMonitor.DoMonitor () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
```

empty, webapi running fine

@chrisdias @sayedihashimi @davidfowl

**Comment by spboyer** [comment]
Yosemite OSX, mono 4.0.1

**Comment by chrisdias** [comment]
i forgot i had this in my .bash_profile and it seems to fix the problem.

export MONO_MANAGED_WATCHER=disabled

@sayedihashimi  this needs to be documented on the asp.net site

**Comment by spboyer** [comment]
added to bash_profile.
getting new error in web template

```
TypeLoadException: Could not load type 'Microsoft.Framework.Runtime.ILibraryExport' from assembly 'Microsoft.Framework.Runtime.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.Lazy`1[System.Collections.Generic.List`1[Microsoft.CodeAnalysis.MetadataReference]].CreateValue () [0x00000] in <filename unknown>, line 0
System.Lazy`1[System.Collections.Generic.List`1[Microsoft.CodeAnalysis.MetadataReference]].CreateValue () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeResultAsync>d__44.MoveNext () [0x00000] in <filename unknown>
```

**Comment by sayedihashimi** [comment]
Adding @davidfowl @glennc

**Comment by spboyer** [comment]
Latest dnvm install this is still an issue.

```
$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
                            mono         ~/.dnx/runtimes
       1.0.0-beta5-11624    mono         ~/.dnx/runtimes
  *    1.0.0-beta5-11649    mono         ~/.dnx/runtimes      default
```


@glennc @danroth27 @davidfowl @shanselman @sayedihashimi

**Comment by spboyer** [comment]
@davidfowl @migueldeicaza @chrisdias @sayedihashimi 

The web template runs under 1.0.0-beta4, #140 is still valid on `dnu build`, be sure that you are setting the dnvm to **default**
```
Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default
       1.0.0-beta5-11625    mono         ~/.dnx/runtimes
       1.0.0-beta5-11631    mono         ~/.dnx/runtimes
       1.0.0-beta5-11657    mono         ~/.dnx/runtimes
       1.0.0.0-beta4        mono         ~/.dnx/runtimes
```

**Comment by Spencerooni** [comment]
@chrisdias Just encountered this. Your suggestion nearly worked for me but I had to use `export MONO_MANAGED_WATCHER=false` not `export MONO_MANAGED_WATCHER=disabled`.

**Comment by geirsagberg** [comment]
Had the same problem, `export MONO_MANAGED_WATCHER=false` fixed it for me as well.

**Comment by jrock2004** [comment]
With false will it detect change or do you still need to restart after every change?

**Comment by geirsagberg** [comment]
It would seem changes are not detected, unfortunately, so this is hardly a permanent solution.

**Comment by johnpapa** [comment]
`export MONO_MANAGED_WATCHER=false` fixes it for now, but I agree that the watcher should detect changes long term

**Comment by johnpapa** [comment]
any update on this @sayedihashimi or guidance?

**Comment by scionwest** [comment]
Using `export MONO_MANAGED_WATCHER=false` didn't solve the issue for me. Are there other work-arounds for this issue?

**Comment by geirsagberg** [comment]
It seems changes are not detected when using Kestrel regardless of whether `MONO_MANAGED_WATCHER` is `true` or `false`. Relevant thread: https://github.com/aspnet/Hosting/issues/45

**Comment by usersxm** [comment]
I am having the exact same problem as you.
![captura de pantalla 2015-05-10 14 45 59](https://cloud.githubusercontent.com/assets/9682572/7555485/51bff2aa-f723-11e4-969d-745ba9c5d230.png)

That was after doing the false/disable thing.. Did you solve the problem?

**Comment by peterblazejewicz** [comment]
@usersxm I'm afraid that is still a valid problem and fixing it depends on 3rd party

**Comment by ChidoYo** [comment]
Just wanted to upvote on what has been said. The following:
`export MONO_MANAGED_WATCHER=false`
Worked for me and I'm on OSX 10.11.1
I was getting the error after installing new bower components.

**Comment by rolandjitsu** [comment]
In my case this issue occurs if I have for instance `node_modules` in the same place where the project is started. So if there would be a way for telling mono not to watch that folder, I think the issue would be fixed.

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
