### ISSUE TITLE
How do I switch to branch beta4

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/generator-aspnet#143]
I installed this via yo, so I wonder how can I update to branch 4 since I am using dnx? Thanks

**Comment by peterblazejewicz** [comment]
- [optionally fork and] clone repo to your local machine
- make sure that your remote points to this repo
- fetch from remote and switch to beta 4 branch
- from console run:
```
npm uninstall -g generator-aspnet
```
(to be sure that you will be using one from repository and)
```
npm link
```
this will actually make a symlink in NPM registry to point to repository source code replacing one installed via `-g` flag
See this:
https://github.com/OmniSharp/generator-aspnet/wiki/how-to-try-local-changes
Note that you usually don't have to use `sudo` flag mentioned on Wiki, it depends on system and configuration.

**Comment by jrock2004** [comment]
What directory do I clone it to?

**Comment by spboyer** [comment]
Beta4 is now the release branch. 

Run `npm install -g generator-aspnet`

You will get the DNX version

**Comment by jrock2004** [comment]
lol that was quick :)
