### ISSUE TITLE
yo aspnet >WebApplication creates .gitgnore not .gitignore

### ISSUE THREAD

**Issue by TravisTheTechie** [OmniSharp/generator-aspnet#147]
```
$ yo aspnet
> WebApplication
? myproject
$ cd myproject
$ ls .gitgnore | wc -l
     1
$ ls .gitignore | wc -l
     0
```

Doh.

**Comment by MaximRouiller** [comment]
Is that live? Updating my template still gives me this error. :(

**Comment by peterblazejewicz** [comment]
@MaximRouiller I think the fix was merged into master just after *.34 release was tagged and published:
https://github.com/OmniSharp/generator-aspnet/commit/7239b6640a03f2cee67f2c330aa5f575b021bf96
(I've checked this by moving to this commit).

**Comment by peterblazejewicz** [comment]
@MaximRouiller 
The *.35 has been puslished:
https://github.com/OmniSharp/generator-aspnet/commit/e1b4cf7a35be6340df1a497634f936a2b0dec4ce

**Comment by MaximRouiller** [comment]
Seen it. Tested it. Loved it!
