### ISSUE TITLE
Default gitignore on new webapp doesn't ignore Compiler

### ISSUE THREAD

**Issue by TravisTheTechie** [OmniSharp/generator-aspnet#149]
With mono, instead of just Obj and Bin, we have to worry about Compiler too. 

```
dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11657    mono         ~/.dnx/runtimes      default
```

If that matters.

**Comment by spboyer** [comment]
@TravisTheTechie need to make sure that you are on version `1.0.0-beta4`
```
brew install dnvm
```
again

**Comment by TravisTheTechie** [comment]
How do I install beta4 then? `dnvm install 1.0.0-beta4` and `dnvm install 1.0.0-beta4 -u` both fail. They require me to clean up `~/dnx/runtimes` before trying again too.

**Comment by spboyer** [comment]
`dnvm install 1.0.0.0-beta4` should work, you can also do 
```
brew uninstall dnvm
brew update
brew install dnvm
```
that worked on another machine I have

**Comment by TravisTheTechie** [comment]
Once I got beta4 installed, `Compiler` no longer created in the folder. :+1:
