### ISSUE TITLE
on windows I get 'dnu is not recognised as an internal or external command'

### ISSUE THREAD

**Issue by JayAtCornwallCollege** [OmniSharp/generator-aspnet#155]
Where do I get dnu from?

**Comment by peterblazejewicz** [comment]
@JayAtCornwallCollege 
Depending on system there are different ways to install new runtime tools, please see instruction on asp.net/home project:
https://github.com/aspnet/home#getting-started-on-windows
https://github.com/aspnet/home#os-x
https://github.com/aspnet/home#linux

**Comment by peterblazejewicz** [comment]
Wait, there are docs now:
http://docs.asp.net/en/latest/getting-started/index.html

**Comment by peterblazejewicz** [comment]
@JayAtCornwallCollege :wave:

**Comment by hanu412** [comment]
Do you have the dnvm setup on your machine? If not,you might see the message you're seeing.

**Comment by JayAtCornwallCollege** [comment]
Many thanks. you helped me solve it.

**Comment by JSSU** [comment]
I have the same problem and I install the VS2015 with the tools
Here is what I did to fix it.
in cmd type: dnvm upgrade
then is fine to use dnu

**Comment by chersull** [comment]
Thank you, this last answer from JSSU solves it in VS2015.

**Comment by PratikSoni2889** [comment]
@JSSU : Your answer resolved my issue. Thnx.
