### ISSUE TITLE
Subgenerators workflow suggestions.

### ISSUE THREAD

**Issue by MiguelLattuada** [OmniSharp/generator-aspnet#159]
__This should be useful.__
1. The [options] parameter described in subgenerators *(yo aspnet --help)* has no documentation.
2. In the console situated at the root folder of my project when I run
```
myproject> yo aspnet:WebApiController Edges
```
this should create the __EdgesController.cs__ class in the __/Controller__ folder, and not the __Edges.cs__ class in the __/root__ folder like it does. The same for the other items.
3. I should be able to specify the namespace when I create a class (controller, model) instead of generate a default one, or create a default ones when the namespace is not specified.
4. I don't want to go further but it's nice to mention. Create a selective for controller like, command dialog for controller type, model bind, and view creation.

If you have that in mind, or think it's crazy, ignore. Anyways grate job guys, this will be part of my workflow.

**Comment by david-driscoll** [comment]
This also has an effect on atom-yeoman and the integration with Omnisharp Atom.  If the `.yo-rc.json` exists, then yeoman forces changes the working directory to the root project folder.  When we're trying to allow the user to add a class to the currently selected folder in the tree.

**Comment by xtianus79** [comment]
Yes, we could do this and I agree but there should be a total redesign of how the subgenerators work in general... i.e. taking on namespaces and applicationname.

**Comment by peterblazejewicz** [comment]
This was subject of #366
Thanks!
