### ISSUE TITLE
Web Application template in Kestrel causes 100% CPU

### ISSUE THREAD

**Issue by geirsagberg** [OmniSharp/generator-aspnet#160]
1. Run `yo aspnet` and select Web Application
2. `dnu restore`
3. `dnx . kestrel`
4. Navigate to `localhost:5001`
5. Open Activity Monitor and notice the `mono-sgen` process using ~100% cpu

This doesn't happen with the sample at https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta4/HelloMvc. Any ideas why?

**Comment by peterblazejewicz** [comment]
@geirsagberg out of curiosity, which version of mono is set as default on your machine? (I'm unable to run builds due to these mono pending issues on OS X)

**Comment by geirsagberg** [comment]
I'm using Mono 4.0.1.

**Comment by geirsagberg** [comment]
Strange... it seems the more files I have in the project, the higher the CPU usage; I can lower the cpu usage by removing node_modules/ and bower_components, for example. Could this be an issue with the file watcher?

**Comment by geirsagberg** [comment]
I have successfully reproduced this issue with the HelloMvc sample as well, once I started adding a few NPM and Bower packages. Closing this issue in lieu of a new issue in the Kestrel repo.
