### ISSUE TITLE
VisualStudioCode : How to restore packages?

### ISSUE THREAD

**Issue by hanu412** [OmniSharp/generator-aspnet#161]
I am getting started with visual studio code. I had set-up Yeoman with the aspnet generator. I loved the ASPNET5 webtemplate which it had generated for me. I am stuck with the package restoration.
Do we have any command which I can run to restore those packages to have the web application up and running?

**Comment by chrisdias** [comment]
Hi - Did you install the .NET Runtime from here: https://github.com/aspnet/home#upgrading-dnvm-or-running-without-visual-studio? Once you do this, you can run "dnu restore" from the terminal in the folder where the app was generated.  You will have to restart VS Code (or open the command palette using cmd+p and running "reload window").

**Comment by hanu412** [comment]
yes I do have the latest dnvm. I did try this one. Since I got the template by running some yo commands,I thought there might be a yo command to restore the packages too. 

I must say,omnisharp team is awesome. It's a great utility for those who love to work from the command line.
