### ISSUE TITLE
Can we have a SignalR "Hub.cs" template in the offering?

### ISSUE THREAD

**Issue by hanu412** [OmniSharp/generator-aspnet#162]
I think having a SignalR template in  the project would add more value to the aspnet-generator. We do not have to create this Hub.cs file when we run the generator initially but can we have it as an add-on? 
Can we have it - run a yo command to have it installed/set-up?

**Comment by peterblazejewicz** [comment]
@hanu412 
Do you think that adding only scaffolded Hub class would be enough in most cases?

Do you now if that official SignalR template project is updated or forked to work with ASP.NET 5?
https://github.com/SignalR/SignalR-StockTicker

/cc @sayedihashimi

**Comment by hanu412** [comment]
I guess we need the Hub class, SignalR dll(namespace) and the jquery-signalr javascript file . With these componets it should be fine. Looks like StockTicker is an example which  Damian Edwards might have used to demo SignalR. I have seen him(online) talk on SignalR a lot. The template project was last updated in Jan,which tells me it is not yet updated. But I heard, SignalR-v3 is being shipped with this ASPNET5.

**Comment by peterblazejewicz** [comment]
That's more then one file - so probably simple scaffolded project will be better. I can help with making one into real thing (OFC when the mono 4.0.* bug will be fixed :( )
:+1:

**Comment by hanu412** [comment]
awesome. I want to contribute by making it. But I need some guidance. Could you guide me so I can come up with it?

**Comment by sayedihashimi** [comment]
SignalR doesn't work with ASP.NET 5 yet.

cc @damianedwards

**Comment by peterblazejewicz** [comment]
This wont' happen until much later this year:
https://github.com/aspnet/SignalR-Server/issues/144#issuecomment-167118165
https://github.com/aspnet/Home/wiki/Roadmap#future-work

Closing/Thanks!
