### ISSUE TITLE
Web template should use gulp by default

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#163]
VS2015 RC now uses gulp by default instead of grunt, we should too. If we have a compatible grunt file then we can add a --grunt option.

cc @chrisdias @aeschli

**Comment by xtianus79** [comment]
Is this the starter web template?

**Comment by peterblazejewicz** [comment]
That's hard to tell why Gulp is preferred (maybe it is shorter and leaner, I use Gulp whenever possible), similar:
https://github.com/aspnet/Home/issues/156

**Comment by xtianus79** [comment]
My issue with Gulp is that it is not on parity with functionality of Grunt at this moment.  Yes there are plugins that can utilize grunt inside of gulp but at that point why would anyone do that... I know people like the easier things per se but for the most part of the simple things gulp does they are simple in grunt too.  The more complex things grunt can do gulp does not.  

I'm all for new if it is complete and thorough... this is not thorough/capable enough to warrant the focus... IMHO.  

Is this up for debate at all regarding the VS2015 RC?  I do understand that the generator should mimic that entirely.

**Comment by sayedihashimi** [comment]
@xtianus79 if you'd like to discuss what's the default task runner in Visual Studio you can file an issue at https://github.com/aspnet/tooling.

**Comment by peterblazejewicz** [comment]
This was fulfilled via #180 
https://github.com/spboyer/generator-aspnet/commit/3c6b22a00af63c0c7a39c713cb0dfc6a608f9737
