### ISSUE TITLE
Web template should be updated to use In memory db for xplat scenarios

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#164]
Before adding support for beta4 templates the web template was using the EF InMemoryStore. With the beta4 templates they do not have the functionality and because of it register/login do not work on cross platform.

For reference here is the code from beta3.
https://github.com/OmniSharp/generator-aspnet/blob/b1e99286bab297391105ab3e5878af52254ca484/templates/projects/web/startup.cs#L40.

cc @chrisdias @aeschli

**Comment by peterblazejewicz** [comment]
x-reference:
https://github.com/aspnet/EntityFramework/releases/tag/7.0.0-beta4

There is SQLite updated supported mentioned in the docs
