### ISSUE TITLE
Add xUnit test project

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#165]
Here is an xUnit test project that we can use that is based on beta4 https://dl.dropboxusercontent.com/u/40134810/SideWaffle/issue-259/UnitTestProject.zip. I haven't tried on mac/linux yet but will try on mac soon. I think it should work there.

FYI the contents of project.json in the link have ```beta4```, we should update that to ```beta5```

**Comment by peterblazejewicz** [comment]
@sayedihashimi 

> I haven't tried on mac/linux yet but will try on mac soon. I think it should work there.

Unfortunately that dreaded mono 4.0.* `System.IO.EndOfStreamException: Failed to read past end of stream.` prevents from building that project :crying_cat_face: : 
#140

**Comment by sayedihashimi** [comment]
What about dnx . test does it run the tests?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
> What about dnx . test does it run the tests?

This worked:
```
dnx . test
xUnit.net DNX test runner (64-bit DNX 4.5.1)
Copyright (C) 2015 Outercurve Foundation.

Discovering: UnitTestProject
Discovered:  UnitTestProject
Starting:    UnitTestProject
Finished:    UnitTestProject

=== TEST EXECUTION SUMMARY ===
   UnitTestProject  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.074s
```

**Comment by alexandros-s** [comment]
That would be a great addition, it was quite easy to add xunit myself but it will be awesome to have this preset by the generator.

**Comment by sayedihashimi** [comment]
OK I've added it at https://github.com/OmniSharp/generator-aspnet/commit/36eddf336b1a7c2e3279f4fa5b1a08050578c8a5
