### ISSUE TITLE
What changed with DNU / DNX... It seems there is instructions missing from the readme

### ISSUE THREAD

**Issue by xtianus79** [OmniSharp/generator-aspnet#166]
I am assuming KPM is dead long live DNU?  lol I will go find it but was wondering if the installation process and procedure should either be placed in the readme or at least linked to?  

your thoughts

**Comment by xtianus79** [comment]
this was helpful. 

https://github.com/aspnet/home

and perhaps this too. 

http://docs.asp.net/en/latest/dnx/overview.html

**Comment by peterblazejewicz** [comment]
There is similar issue I've created:
https://github.com/OmniSharp/generator-aspnet/issues/158
Basically go to ASP.NET 5 documentation and follow official documentation when installing runtime and tools. They are somehow outside of the scope of this project now.

**Comment by xtianus79** [comment]
@peterblazejewicz does the ASP.NET 5 documentation explain it the way the first link explains it?  otherwise I would have been totally lost.  Moreover, the getting rid of the KRE_Home variable is proving to be a nightmare.

**Comment by peterblazejewicz** [comment]
After there is official documentation (which we can improve via Github) I'd never advise to use just project readme :D I'd rather contribute to documentation.

**Comment by sayedihashimi** [comment]
Closing since I don't see any needed action in `yo aspnet` besides #158.
