### ISSUE TITLE
Delete samples folder

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#170]
I noticed that we still have a [```samples```](https://github.com/OmniSharp/generator-aspnet/tree/master/samples) folder. I think this was a hold over from before we moved to ```templates```. It should be removed.

**Comment by peterblazejewicz** [comment]
:+1:  it reads old-good '1.0.0-beta2'

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
It's used in current implementation for `unittest`:
https://github.com/OmniSharp/generator-aspnet/blob/d1fa3484acea0f25b076150e049d9cb8037278e2/app/index.js#L235
Also:
https://github.com/OmniSharp/generator-aspnet/blob/d1fa3484acea0f25b076150e049d9cb8037278e2/e2etest.sh#L8
https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L47-L50

**Comment by spboyer** [comment]
@peterblazejewicz `unittest` is not in the options for the project types right now. We can move the unittest code to the `/templates/projects` folder and then delete the `/samples` dir.

Also the `PROJECTSDIR` ref is not used in the e2etest.sh at this time, so there is no danger there in removing it.

thoughts? 

@sayedihashimi

**Comment by sayedihashimi** [comment]
Agreed

**Comment by peterblazejewicz** [comment]
TODO:
- [ ] move `unittest` content into `/templates/projects/unittest`
- [ ] remove `/samples` directory
- [ ] cleanup references in generator

**Comment by peterblazejewicz** [comment]
closed via #181
