### ISSUE TITLE
Update namespace for sub generators

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#171]
When a sub generator is invoked current we are hard coding to ```MyNamespace```. Better would be to populate the template data object with two values.

 - ApplicationName = folder name where ```project.json``` resides
 - Namespace = relative path from project.json to current folder (replace ```/``` with ```.```) and fix casing

**Comment by peterblazejewicz** [comment]
@sayedihashimi Entire project can be scaffolded that way. Angular generator scaffolds namespace and project name in similar ways:
https://github.com/yeoman/generator-angular/blob/master/app/index.js#L13-L42
If implementation is started based on linked code example or similar, one should remember to use underscore.strings as project dependency, as it is deprecated in Yo:
https://github.com/yeoman/generator/issues/766

**Comment by sayedihashimi** [comment]
@mayurid can we get someone to help out here?

**Comment by peterblazejewicz** [comment]
for reference: example implementation to evaluate in different project:
https://github.com/nexumAG/generator-atomic/blob/master/organism/index.js#L51-L54

**Comment by peterblazejewicz** [comment]
https://github.com/OmniSharp/generator-aspnet/pull/366

**Comment by spboyer** [comment]
Closing #366 has been merged
