### ISSUE TITLE
New changes incorporated into my fork from generator-aspnet crash VS 2015 RC

### ISSUE THREAD

**Issue by xtianus79** [OmniSharp/generator-aspnet#172]
I can't figure why but haven't heard anything from the aspnet dev team.  

https://github.com/aspnet/Home/issues/635

wondered if it might be something I need to add to the gitignore or something else. 

I have a file error log report included in the link...

**Comment by sayedihashimi** [comment]
Please port the issue to https://github.com/aspnet/tooling instead of aspnet/home. Since there is no action on the generators team ill close this now.

**Comment by xtianus79** [comment]
Ok thanks. Do you have any clue what might be triggering this.
