### ISSUE TITLE
Richer WebApi project

### ISSUE THREAD

**Issue by nojaf** [OmniSharp/generator-aspnet#173]
It would be nice to see a richer WebApi project template with some basic Identity stuff as in the Mvc template.

**Comment by peterblazejewicz** [comment]
@nojaf Florian, can you consider (I could do this as well) to repost request on ASP.NET home? They originally provide all samples to community via OpenSource:
https://github.com/aspnet/Home/tree/dev/samples

**Comment by peterblazejewicz** [comment]
This is now tracked on aspnet/Templates:
[WebAPI: Individual Auth Template](https://github.com/aspnet/Templates/issues/201)
[Advanced MVC and API Project Templates](https://github.com/aspnet/Templates/issues/221)
[Need a SPA template](https://github.com/aspnet/Templates/issues/137)

Closing
Thanks!
