### ISSUE TITLE
Server starts but white page (Windows 8.1)

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/generator-aspnet#182]
I just built a web application, I started the server and my browser opens and I get a white page. Any ideas?

**Comment by peterblazejewicz** [comment]
No erorrs in console, what about source/markup of that white page, is there any?

**Comment by sayedihashimi** [comment]
What OS are you running? And what version of dnx?

**Comment by jrock2004** [comment]
I get 2 console errors with the error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" for favicon.ico and localhost:8716

Oh I see. The DNX version I have is 1.0.0-beta5-12021. So let me update the dep to beta5 and see if that works

**Comment by jrock2004** [comment]
ok, so I switched the project to use beta 4 restored the packages and this is the error

Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  EntityFramework.Commands 7.0.0-beta4
  EntityFramework.SqlServer 7.0.0-beta4
  Kestrel 1.0.0-beta4
  Microsoft.AspNet.Authentication.Cookies 1.0.0-beta4
  Microsoft.AspNet.Authentication.Facebook 1.0.0-beta4
  Microsoft.AspNet.Authentication.Google 1.0.0-beta4
  Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta4
  Microsoft.AspNet.Authentication.Twitter 1.0.0-beta4
  Microsoft.AspNet.Diagnostics 1.0.0-beta4
  Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta4
  Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta4
  Microsoft.AspNet.Mvc 6.0.0-beta4
  Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta4
  Microsoft.AspNet.Server.IIS 1.0.0-beta4
  Microsoft.AspNet.Server.WebListener 1.0.0-beta4
  Microsoft.AspNet.StaticFiles 1.0.0-beta4
  Microsoft.AspNet.Tooling.Razor 1.0.0-beta4
  Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta4
  Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta4
  Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta4
  Microsoft.Framework.Logging 1.0.0-beta4
  Microsoft.Framework.Logging.Console 1.0.0-beta4

**Comment by tlk** [comment]
aspnet/Home#729

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
