### ISSUE TITLE
Add an option to use unstable package feed

### ISSUE THREAD

**Issue by DamianEdwards** [OmniSharp/generator-aspnet#183]
It would be great if the project generators had an option to use the unstable package feed ([aspnetvnext](https://www.myget.org/F/aspnetvnext/api/v2)). This would drop a `nuget.config` file in the project folder configured to use the feed (e.g. like [this](https://github.com/aspnet/Localization/blob/dev/NuGet.Config)) as well as setting the package dependencies versions in `project.json` to * instead of locked to a specific version, e.g. `1.0.0-*` instead of `1.0.0-beta4`.

**Comment by sayedihashimi** [comment]
How about adding a sub-generator (i.e. item template)? I think adding the sub-gen would be simpler, we can add the option as well to the generator but that may take more time.

Can you paste the content of the nuget.config file that you are looking for?

**Comment by peterblazejewicz** [comment]
Something like would be OK, it's commonly used solution I believe:
```
yo aspnet [...] --unstable
```
The subgenerator option can also work, it could:
- read `project.json` (if exists), make change and write back
- copy config file
