### ISSUE TITLE
ASP.NET Console App Template  for Beta5

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#185]
https://onedrive.live.com/redir?resid=43459A6389A804D9!94672&authkey=!ACAZTR07BatRWE4&ithint=file%2czip

**Comment by peterblazejewicz** [comment]
@sayedihashimi :me: as :construction_worker:

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz I have assigned it to you
