### ISSUE TITLE
ASP.NET Empty Template  for Beta5

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#186]
https://onedrive.live.com/redir?resid=43459A6389A804D9!94673&authkey=!AHE8H8l7OwMfcq4&ithint=file%2czip

**Comment by peterblazejewicz** [comment]
@sayedihashimi :me: as :construction_worker:

**Comment by peterblazejewicz** [comment]
`hosting.ini` is a new file: 
https://github.com/aspnet/Hosting/issues/277#issuecomment-103952499

**Comment by sayedihashimi** [comment]
Related #196

**Comment by sayedihashimi** [comment]
Blocked by error https://github.com/OmniSharp/generator-aspnet/pull/196#issuecomment-113577033

**Comment by rustd** [comment]
Here are the changes needed
* project.json

Package name is Kestrel instead of Microsoft.AspNet.Server.Kestrel
    "Kestrel": "1.0.0-beta5",

The commands section should have
  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --config hosting.ini",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --config hosting.ini"
  },

* hosting.ini

This file should only have the following content
server.urls=http://localhost:5000

* Remove build numbers from packages. Packages should as follows 1.0.0-Beta5
Set NuGet package source and DNX_FEED to https://www.myget.org/f/aspnetbeta5/api/v2
Do not use the release/ dev feed

* BrowserLink
Remove BrowserLink package and the  app.UseBrowerLink(). from Startup.cs

**Comment by sayedihashimi** [comment]
Closing thanks @peterblazejewicz
