### ISSUE TITLE
ASP.NET Server Side Item templates for Beta5

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#187]
https://onedrive.live.com/redir?resid=43459A6389A804D9!94675&authkey=!ADLdrmPtIDL6XQw&ithint=file%2czip

**Comment by rustd** [comment]
Following are the names of the Item Templates in order

* MVC View Layout Page
* MVC View Imports Page
* MVC View Start Page
* Class
* ASP.NET Configuration File
* MVC Controller Class
* MVC View Page
* Interface
* Middleware Class
* Startup Class
* Razor Tag Helper
* Text File
* Web API Controller Class

**Comment by sayedihashimi** [comment]
Related PR #193

**Comment by peterblazejewicz** [comment]
@sayedihashimi assign to :me:

**Comment by sayedihashimi** [comment]
Assigned!

**Comment by sayedihashimi** [comment]
All PRs have been merged. Closing.
