### ISSUE TITLE
ASP.NET Client Side Item templates for Beta5

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#188]
https://onedrive.live.com/redir?resid=43459A6389A804D9!94674&authkey=!AA7aI5UoOEZ6Zcg&ithint=file%2czip

**Comment by rustd** [comment]
Look in the wwwroot folder.
Following are the names of the Item Templates in order
* Bower Configuration File (include bower.json and .bowerrc)
* AngularJs Module (app.js)
* CoffeeScript File (CoffeeScript.coffee)
* AngularJs Controller (controller.js)
* AngularJs Controller using $scope (controller1.js)
* AngularJs Directive (directive.js)
* AngularJs Factory (factory.js)
* TypeScript File (file.ts)
* Grunt Configuration File (gruntfile.js)
* Gulp Configuration File (gulpfile.js)
* HTML Page (htmlpage.html)
* JavaScript File (JacaScript.js)
* JSON File (json.json)
* JSON Schema File (json-schema.json)
* JSX (jsx.jsx)
* NPM Configuration File (package.json)
* Style Sheet (StyleSheet.css)
* LESS Style Sheet (StyleSheet.less)
* SCSS Style Sheet (StyleSheet.scss)
* TypeScript Configuration File (tsconfig.json)

**Comment by peterblazejewicz** [comment]
Naming should be discussed - the items are to be rendered via subgenerators - each subgenerator for one particular type (exception Bower). What is expected naming? For example:
```
LESS Style Sheet (StyleSheet.less)
SCSS Style Sheet (StyleSheet.scss)
```
or:
```
AngularJs Controller (controller.js)
AngularJs Controller using $scope (controller1.js)
```
How they are named in VS?

**Comment by sayedihashimi** [comment]
I don't think that we need the ```(...)``` content with the file name. That will show up as the default name of the file so it doesn't have to be in the name of the sub-generator itself. Regarding ```controller1.js```, it should just be ```controller.js``` (no ```1```).

In VS the names are the following.
 - LESS Style Sheet
 - SCSS Style Sheet (SASS)
 - AngularJs Controller
 - AngularJs Controller using $scope

**Comment by peterblazejewicz** [comment]
@sayedihashimi all templates are add via renent PRs. The list above is updated and contains a links.
Thanks!

**Comment by sayedihashimi** [comment]
Closing this now everything has been merged.
