### ISSUE TITLE
ASP.NET Web API Template for Beta5

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#189]
https://onedrive.live.com/redir?resid=43459A6389A804D9!94676&authkey=!AK_F4dzipIag-U8&ithint=file%2czip

**Comment by peterblazejewicz** [comment]
@sayedihashimi I can prepare PR (though I have problems compiling final projects with 'beta5' version).
Thanks!

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz if you can create and send the PR that will be great. I'll followup with the team on the issues. I'll assign the item to you now.

**Comment by peterblazejewicz** [comment]
Quesetion: should I ignore `launchSettings.json` from generated sample?

**Comment by sayedihashimi** [comment]
@peterblazejewicz it's used by Visual Studio. I think it would be good to include it in the generator for the cases where the project is used on both Mac + Windows. Since the file is under Properties I don't think many people will notice so there should be no harm in including it.

**Comment by peterblazejewicz** [comment]
`launchSettings.json` added in PR:
https://github.com/peterblazejewicz/generator-aspnet/blob/update/webapi-project/templates/projects/webapi/Properties/launchSettings.json

**Comment by rustd** [comment]
Here are the changes needed
* project.json

Package name is Kestrel instead of Microsoft.AspNet.Server.Kestrel
    "Kestrel": "1.0.0-beta5",

The commands section should have
  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --config hosting.ini",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --config hosting.ini"
  },

* hosting.ini

This file should only have the following content
server.urls=http://localhost:5000

* Remove build numbers from packages. Packages should as follows 1.0.0-Beta5
Set NuGet package source and DNX_FEED to https://www.myget.org/f/aspnetbeta5/api/v2
Do not use the release/ dev feed

* BrowserLink
Remove BrowserLink package and the  app.UseBrowerLink(). from Startup.cs

**Comment by sayedihashimi** [comment]
Closing thanks @peterblazejewicz
