### ISSUE TITLE
Update Nancy generator for beta5

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#197]
We should update the Nancy generator for beta5.

**Comment by sayedihashimi** [comment]
@Yantrio @jchannon any thoughts about updating for ```beta5```?

**Comment by sayedihashimi** [comment]
@Yantrio @jchannon I have just pushed the ```beta5``` build to travis. Nancy is still based on beta4. Can one of you update the Nancy templates?

**Comment by jchannon** [comment]
I've just got someone to try it for me at Prognet2015 and it all works so looks to me it works fine on beta5. I think because the depednencies are 1.0.0-*

**Comment by sayedihashimi** [comment]
Thanks @jchannon, closing this now.
