### ISSUE TITLE
Subgenerator for `hosting.ini`

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#198]
It appears that `hosting.ini` will have important meaning in upcoming ASP.NET project and having separate generator can be useful, for example when user wants to update existing, older project or just create entire project step by step.
That's hard to decide this right now I think before that `beta5` release, but let's have this topic discussed.
Thanks!

**Comment by spboyer** [comment]
No longer needed, can close correct @peterblazejewicz

**Comment by peterblazejewicz** [comment]
:ok:
