### ISSUE TITLE
_ViewImports.cshtml has no content in sample archives for beta5

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#206]
I've created a subgenerator for MVC View Imports Page item template - but files for that template (in combo and in single example archive for item templates) are empty. Is that by design?
https://github.com/peterblazejewicz/generator-aspnet/commit/8b922b082d9d9cc5d5ad33b91cd70714a0d33c14

/cc @rustd

**Comment by rustd** [comment]
Yes, this is by design

**Comment by peterblazejewicz** [comment]
Thanks! Closing
