### ISSUE TITLE
Delete develop branch

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#223]
@spboyer @peterblazejewicz @larsw  

The following branches don't have any recent activity.

 - develop
 - larsw-unittest-beta3
 - unittest

For the unit test one we have some updated content for beta5 at https://github.com/OmniSharp/generator-aspnet/issues/165.

Can we delete these branches?

**Comment by spboyer** [comment]
:thumbsup:

**Comment by peterblazejewicz** [comment]
LGTM

**Comment by sayedihashimi** [comment]
Deleted them
