### ISSUE TITLE
Change Gruntfile subgenerator to simple generator - without argument

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#229]
The `Gruntfile` is always a `Gruntfile` in default settings, written uppercase and we should not use named generator - as users are expected to not modify this default name:
http://gruntjs.com/getting-started

Due to this assumptions user can just type: 'grunt' and by convention the 'Gruntfile' file will be used.

Historic background:
https://github.com/gruntjs/grunt/issues/110

I'll make a change for `beta5` and let this for discussion.

Thanks!

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz  I agree its better to use ```Gruntfile```.

**Comment by sayedihashimi** [comment]
Closed via #230

**Comment by sayedihashimi** [comment]
Thanks, I've created an issue to get the VS templates updated as well https://github.com/aspnet/Tooling/issues/108
