### ISSUE TITLE
Add #top link anchor with "Return to top"/"Top" shortcuts to README.md

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#242]
The `README.md` is rendered just as web page. The project README.md is becoming lengthier after beta5.
Can we add [Return to top](#top)
```md
[Return to top](#top)
``` 
shortcuts? They are part of HTML5 and are supported natively by browsers (no JS required): pt. 2 in specs:
https://html.spec.whatwg.org/multipage/browsers.html#scroll-to-the-fragment-identifier
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
I've used in other projects as fallback/native behavior.
When viewed on NPM it would be rendered as:
![20150629213015](https://cloud.githubusercontent.com/assets/14539/8416441/1f427c80-1ea6-11e5-848b-05e1bcb82e13.jpg)

Thanks!

**Comment by sayedihashimi** [comment]
+1
