### ISSUE TITLE
Generate Web API controller based on an existing model class

### ISSUE THREAD

**Issue by devhammer** [OmniSharp/generator-aspnet#249]
Not sure if it's feasible, but would like to explore the possibility of adding another Web API controller option to generate a controller based on a provided class, similar to how the scaffolding for an OData Web API 2 controller works in Visual Studio.

Would be good to have both OData and non-OData options.

**Comment by sayedihashimi** [comment]
@devhammer how would you get the info to create the controller? Previously we worked on [k gen](http://blogs.msdn.com/b/webdev/archive/2014/08/21/command-line-scaffolding-for-asp-net-vnext.aspx) for command line scaffolding but we've put that on the back burner for now to focus on other more important features.

**Comment by devhammer** [comment]
Well, as a first pass, could you not use an additional parameter for the model name, and then build a naïve implementation that simply passes the model name as the generic type for a list returned by the GET, and the input parameter for the POST/PUT?

As I said above, I haven't had a chance to evaluate feasibility. I'm hoping to see if it's possible to have parity with the templates that are available in Visual Studio. I recognize that with differences in the underlying plumbing this may not be possible. I'm a relative noob to Yeoman, so I understand that I may be missing some important things regarding how hard this may be.

**Comment by peterblazejewicz** [comment]
Guys, Is that OData scaffolding add-on a built-in feature in VS? Or does it require plugin install?

**Comment by devhammer** [comment]
@peterblazejewicz As far as I'm aware, the OData Web API 2 controller scaffolding is built-in. I checked my installed extensions just to make sure that I didn't accidentally install that, and I'm not seeing anything that looks like a likely candidate for adding it after the fact.

**Comment by sayedihashimi** [comment]
@peterblazejewicz 
>Guys, Is that OData scaffolding add-on a built-in feature in VS? 

I'm 99% sure it's shipped with the MVC tooling which is a part of VS. FYI that applies to ASP.NET 4, not ASP.NET 5 yet.

@devhammer 
>could you not use an additional parameter for the model name
I'm hoping to see if it's possible to have parity with the templates that are available in Visual Studio. I

Are you referring to ASP.NET 5 or ASP.NET 4? In ASP.NET 4 we have the `Add New Scaffolded Item...` dialog which can take an EF Model and then scaffold the resulting files. For ASP.NET 5 we have not yet implemented that support.

From what I can tell we should have parity with ASP.NET 5 item templates now.

@devhammer if you are interested in prototyping/spiking something to generate controllers from a model then let's chat.

**Comment by devhammer** [comment]
@sayedihashimi I'd love to help, and had started looking at the code to see if I could figure out a good way to get a start on this, but was looking at the beta 4 version, so I'll have to pull down the new version and start again.

Would love to chat, but probably not until next week. Client work needs to take priority this week.

**Comment by devhammer** [comment]
@sayedihashimi With respect to the question on parity, I'm referring to the scaffolding available in VS2013 for Web API 2.

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
