### ISSUE TITLE
Update travis build to verify all templates

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#25]
We already have a [travis build in place](https://travis-ci.org/ligershark/generator-aspnet). When there are changes it's cumbersome to verify. It would be good if travis could verify the following continue to work.

 - ```yo aspnet``` creates content for all generators
 - ```kpm restore``` passes for all generators
 - ```kpm build``` passes for all generators
 - ```k kestrel``` successfully starts kestrel on given port for web projects. ***stretch goal***

I don't know much about travis myself so this is def an area that we can use some help.

**Comment by spboyer** [comment]
@sayedihashimi PR #59 verifies that all `yo aspnet` and `yo aspnet:[generator]` validates. I also added the Travis CI hook, you can see here https://travis-ci.org/OmniSharp/generator-aspnet/builds/49649866 when it fails for example on one of the PR test I put in.
