### ISSUE TITLE
Latest version doesn't install with latest npm

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#255]

**Comment by peterblazejewicz** [comment]
@spboyer Do you mean NPM 3? (beta, via `npm install -g npm@3.0-latest.`)

**Comment by spboyer** [comment]
$yo --version
1.4.7
$npm -v
2.12.1
$npm -v
2.12.1

```
$ npm install -g generator-aspnet
generator-aspnet@0.0.33 /Users/shayneboyer/.npm-packages/lib/node_modules/generator-aspnet
├── uuid@2.0.1
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── yosay@1.0.4 (string-length@1.0.0, ansi-styles@2.1.0, ansi-regex@1.1.1, word-wrap@1.0.3, strip-ansi@2.0.1, pad-component@0.0.1, minimist@1.1.1, taketalk@1.0.0)
├── chai@1.10.0 (assertion-error@1.0.0, deep-eql@0.1.3)
└── yeoman-generator@0.19.2 (detect-conflict@1.0.0, read-chunk@1.0.1, yeoman-welcome@1.0.1, xdg-basedir@1.0.1, user-home@1.1.1, diff@1.4.0, text-table@0.2.0, mime@1.3.4, dargs@4.0.1, async@0.9.2, istextorbinary@1.0.2, debug@2.2.0, cross-spawn@0.2.9, nopt@3.0.3, mkdirp@0.5.1, run-async@0.1.0, shelljs@0.4.0, mem-fs-editor@1.2.3, through2@0.6.5, cli-table@0.3.1, underscore.string@3.1.1, pretty-bytes@1.0.4, dateformat@1.0.11, glob@5.0.13, findup-sync@0.2.1, rimraf@2.4.1, github-username@1.1.1, yeoman-assert@1.0.0, class-extend@0.1.1, download@4.1.2, yeoman-environment@1.2.5, gruntfile-editor@1.0.0, html-wiring@1.1.0, lodash@3.10.0, sinon@1.15.4, inquirer@0.8.5)
```

**Comment by spboyer** [comment]
Even when I do 
```
$npm install -g generator-aspnet@0.0.36
```
then run `$yo aspnet` getting old version prompts:
```
$ yo aspnet

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |   marvellous ASP.NET 5   |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What type of application do you want to create? (Use arrow keys)
❯ Empty Application
  Console Application
  Web Application
  Web API Application
  Nancy ASP.NET Application
  Class Library
```

But in my `npm` folder I have *0.0.33* and *0.0.36*

@peterblazejewicz @sayedihashimi

**Comment by sayedihashimi** [comment]
Try
sudo npm r generator-aspnet -g

To remove previous npm link usage.

**Comment by spboyer** [comment]
@sayedihashimi still brings down v.0.0.33, but if I do `npm upgrade -g generator-aspnet`, I do get versioin .50 but the prompts are the old. meaning that I do not get the "w/o Auth" options.

**Comment by spboyer** [comment]
I have reinstalled node, npm etc.  Still get 33 every time even though 34, 35, 36 -> 50 is there on npm.  If I specifically ask for 50 it installs but still doesn't work.  And for more fun, npm link on the repo does the same thing. I'm out of commission now. This is a whole new set of issues I have now.

@peterblazejewicz @sayedihashimi

**Comment by sayedihashimi** [comment]
This is insane, is there a node_modules folder 📁 somewhere above your pwd? Do you have any old copies of the repo that you've renamed the folder? I think on mac/Linux if you rename a folder symlinks point to renamed folder. Check your symlinks.

**Comment by sayedihashimi** [comment]
Maybe try npm list to see where it is installed.

**Comment by spboyer** [comment]
I completely cleaned npm, and node and any existence of generator-aspnet from my machine and started clean.

As far as the machine was concerned it never had node installed nor npm.

Same issue.

**Comment by xtianus79** [comment]
@spboyer I think I've ran into a similar issue with this latest build.  I am still investigating. With that said have you went to your global npm's and adjusted things from there? That should work like a hammer.

**Comment by peterblazejewicz** [comment]
@spboyer 
you should get v50:
```
generator-aspnet@0.0.50 /usr/local/lib/node_modules/generator-aspnet
├── uuid@2.0.1
...
```
That's not the latest version your local system is installing, v.33:
```
generator-aspnet@0.0.33 /Users/shayneboyer/.npm-packages/lib/node_modules/generator-aspnet
...
```
I've tried this and it seems to work on my machine (package version explicit):
```
npm install -g generator-aspnet@0.0.50
```

**Comment by spboyer** [comment]
@peterblazejewicz i know.  Even if I do an explicit `..@0.0.50` i get the proper download.  However when running `yo aspnet` the initial prompts still only gives me these

```
? What type of application do you want to create? (Use arrow keys)
❯ Empty Application
  Console Application
  Web Application
  Web API Application
  Nancy ASP.NET Application
  Class Library
```

Next, I will again remove node, npm from the machine and re-install these. Then `npm install @0.0.50` explicit.  It makes no sense.  On another machine I have, no issues where I am running 

```
npm 2.7.4
node 0.10.35
yo 1.4.6
```

@sayedihashimi

**Comment by peterblazejewicz** [comment]
@spboyer 

> I completely cleaned npm, and node and any existence of generator-aspnet from my machine and started clean.

I could only think about previously used `npm link` still pointing to previous local version of generator via git clone. Does it make sense?

**Comment by spboyer** [comment]
@peterblazejewicz hard to do...got rid of all of that as well.  Very weird going to give it another look tonight.

**Comment by sayedihashimi** [comment]
What's the result when you execute the following commands?

`npm list -g generator-aspnet`
and
`npm list generator-aspnet`

**Comment by spboyer** [comment]
FIXED! 
https://github.com/npm/npm/wiki/Troubleshooting
https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken

Reinstall npm:
```
curl -L https://www.npmjs.org/install.sh | sh
```
**Try clearing the npm cache**
Sometimes npm's cache gets confused. You can reset it using:
```
npm cache clean
```

**Comment by sayedihashimi** [comment]
Ok glad you got it figured out, closing this now.
