### ISSUE TITLE
Update to avoid using .remote()

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#26]
Migrated issue from https://github.com/ligershark/generator-aspnet/issues/9. See that for full comments.

@shirhatti in the current implementation we are using ```.remote()``` in [index.js](https://github.com/ligershark/generator-aspnet/blob/master/app/index.js) to retrieve the template content. What I've noticed is that when calling ```.remote()``` if the git repo exists on the client cache then it will not be refreshed. There is a ```refresh``` parameter on [remote()](http://yeoman.github.io/generator/actions.html#remote). If we specify ```true``` for refresh then the git repo will be cloned each time when the generator is invoked. On my box in order to get rid of yeoman cache I had to remove ```yo```.

Is using ```.remote()``` the right approach here? I looked at the [generator-angular](https://github.com/yeoman/generator-angular/blob/master/app/index.js) and they include the files directly inside the npm package then use [.template()](http://yeoman.github.io/generator/actions.html#template) and [.copy()](http://yeoman.github.io/generator/actions.html#copy) to write the files.

The code to always update when using remote is below.

```javascript
    retrieveContent: function () {
        var done = this.async();

        this.remote('ligershark', 'aspnet_vnext_samples', 'master', function(err, remote) {
            done();
        },true);
    }
```

cc @jchannon

**Comment by peterblazejewicz** [comment]
The implementation for local templates/files can be as simple as:
https://gist.github.com/peterblazejewicz/9ae54b300b862b4e5320
I'd also think about bringing back tests for templ/files creation process.

**Comment by spboyer** [comment]
@peterblazejewicz have you done this locally and tested?

**Comment by peterblazejewicz** [comment]
@spboyer Yes, this is from my local branch. Can I bring back default Yeoman's testing structure to project? (by default yeoman-generator scaffolds tests for generator projects). I could investigate this.
I would not add local copy features yet unless covered by tests

**Comment by spboyer** [comment]
.remote() removed and test coverage added for entire repo in latest PR -> https://github.com/OmniSharp/generator-aspnet/pull/59
