### ISSUE TITLE
How to quit ASP.NET Kestrel web server on a Mac (Using WebApplicationSimple)

### ISSUE THREAD

**Issue by misterzik** [OmniSharp/generator-aspnet#272]
I'm running the WebAppliactionSimple app generated by YO!. Running kestrel, Everything runs great. Until the part where i have to shutdown my server.

When I hit Ctrl+C (or Enter), the server doesn't quit. So i went ahead and "kill" the process by using 

    CTRL + Z

But now my next problem is that when i check

    ps   

it's still running on the ttys0001, and the process is still on the background, which blocks me from starting, unless i change the port. 

    dnx . kestrel 

I came across this topic, and will like to know if this will fix the issue.
https://gist.github.com/Tragetaschen/18e59107934333b8a3ea

Thanks for the help!

**Comment by nosami** [comment]
`Ctrl+Z` doesn't kill, it suspends to the background. You can verify this by running the command `fg` for 'foreground'. You will see the app come back to life.

**Comment by misterzik** [comment]
Thanks @nosami , what would be the best practice to stop the server from running at all?

**Comment by nosami** [comment]
For now, you need to kill it.

I have the following function in my `~/.zshrc` to help (it will work inside `~/.bashrc` too)

```sh
killit() {
    # Kills any process that matches a regexp passed to it
    ps aux | grep -v "grep" | grep -i "$@" | awk '{print $2}' | xargs kill
}
```

Then I can run `killit kestrel` in a new terminal.

**Comment by misterzik** [comment]
Guys, 
So I was able to stop this by doing,

    CTRL + Z

to be able to exit from the hangup terminal, and afterwards i used;

    kill %1

Please let me know if there is a better way for this.

**Comment by nosami** [comment]
Yeah... that will work too :)

**Comment by misterzik** [comment]
@nosami Awesome! will def do it your way, looks sexier hehe. Thanks for help man.
