### ISSUE TITLE
ASP.NET 5 Beta6 Console App Template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#273]
Sample is uploaded http://1drv.ms/1LAz7uJ

**Comment by Spinarooni** [comment]
I'll take a shot at this one.

**Comment by peterblazejewicz** [comment]
Thanks!

**Comment by sayedihashimi** [comment]
@Spinarooni thanks! FYI I've added some details on getting started at https://github.com/OmniSharp/generator-aspnet/issues/279. Please keep an eye on that issue as we may add more details there.

@Spinarooni we are hoping to release on Monday in the morning (Pacific time). Ideally we'd like to have PRs submitted for all projects by Sunday at the latest. Please let us know if that will be an issue.

**Comment by sayedihashimi** [comment]
Fixed in https://github.com/OmniSharp/generator-aspnet/commit/7a54d51d0cb3d5ff63b2888d5c08778f44297911 by @Spinarooni
