### ISSUE TITLE
ASP.NET 5 Beta6 Class Library project

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#274]
Sample is uploaded http://1drv.ms/1LAz7uJ

**Comment by peterblazejewicz** [comment]
Me 
Thanks!

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz

**Comment by sayedihashimi** [comment]
Fixed in https://github.com/peterblazejewicz/generator-aspnet/commit/eb4ae80fd3f973347b65794c47b2b864c3d54967 by @peterblazejewicz
