### ISSUE TITLE
ASP.NET5 Beta6 Empty Web Template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#275]
Sample is uploaded http://1drv.ms/1LAz7uJ

**Comment by peterblazejewicz** [comment]
Me, thanks!

**Comment by peterblazejewicz** [comment]
The https://github.com/OmniSharp/generator-aspnet/pull/281 by @Spinarooni covers this one already.
I've removed me as assingee and closed my PR. Thanks!

**Comment by sayedihashimi** [comment]
Fixed in https://github.com/OmniSharp/generator-aspnet/commit/29d3eacbc52a135d71dfb358c4e39843cb1dd07d by @Spinarooni
