### ISSUE TITLE
ASP.NET 5 beta6  WebApp with authentication template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#276]
Sample is uploaded http://1drv.ms/1LAz7uJ

**Comment by peterblazejewicz** [comment]
Me, Thanks!

**Comment by peterblazejewicz** [comment]
That's blocked:
https://github.com/OmniSharp/generator-aspnet/issues/286
The new samples comes without Grunt support. Wait until #286 is closed.

**Comment by peterblazejewicz** [comment]
We are free to go, the Grunt templates and details simply didn't changed for beta6

**Comment by peterblazejewicz** [comment]
This one does not restore, for details see PR:
https://github.com/OmniSharp/generator-aspnet/pull/288/

**Comment by sayedihashimi** [comment]
Fixed in https://github.com/OmniSharp/generator-aspnet/pull/288 by @peterblazejewicz
