### ISSUE TITLE
ASP.NET 5 beta6 WebApp No Auth project

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#277]
Sample is uploaded http://1drv.ms/1LAz7uJ

**Comment by Spinarooni** [comment]
I'll try this one also.

**Comment by sayedihashimi** [comment]
Fixed in https://github.com/OmniSharp/generator-aspnet/commit/c8571d23b31dbe15b0644b668b0ea7cd8368d3b9 by @Spinarooni
