### ISSUE TITLE
Does beta6 drop Grunt completely?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#286]
/cc 
@sayedihashimi @rustd
To be sure: I cannot find a Grunt reference and template in samples for Web applications for beta6.
Is this by decision or omission? 
I know that Gulp is now default, just want to be sure that there is no changes in the projects that are created with Grunt option.
Thanks!

**Comment by sayedihashimi** [comment]
In beta6 I don't think there were any changes to the default gulp file so I think the existing grunt file should continue to work. We should keep it if we can.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Thanks! Sorry to sound overhyping, but just want to be sure (and that was late evening to be honest).
Solved
