### ISSUE TITLE
Setting up project for git

### ISSUE THREAD

**Issue by hahmed** [OmniSharp/generator-aspnet#289]
I have used the asp.net generator a couple of times for vnext projects, I am unsure how other devs are creating their web applications, but I always have a root Folder then the web app and tests sitting below.

When I am storing my project in Git, I want to save both projects into a single git repo.

When using the generator it seems as though it is a git repo per project. So if I use the yo generator to create my app it is already initialised with git. Was this the intended purpose? Do i need to change my approach?

Thanks

**Comment by peterblazejewicz** [comment]
@hahmed 
Created template project just ships with `.gitignore` file - that is not the same as initialised Git repo. The `Git` can have multiple `.gitignore` files, you could always remove one, etc.
When I create ASP5 with generator I usually use flat structure - the same as used in VisualStudio:
https://github.com/peterblazejewicz/AngularJS101
(recreation of VS created tutorial with generator).
Thanks!

**Comment by peterblazejewicz** [comment]
Closing this assuming answered fully to OP
Thanks!
