### ISSUE TITLE
Upgrade to latest travis

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#290]
Travis has some new infrastructure and it looks like we should move to that. More info on migrating at http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade.

**Comment by spboyer** [comment]
I believe that #360 covers this issue, correct @shirhatti

**Comment by shirhatti** [comment]
Yes. The change has already been merged :+1:

**Comment by peterblazejewicz** [comment]
> Yes. The change has already been merged

closing

**Comment by peterblazejewicz** [comment]
x-ref: https://github.com/OmniSharp/generator-aspnet/commit/2660da51737fa5bebcae60c02cb44a2b990a6ccf
