### ISSUE TITLE
Update npm test to fail when publish fails

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#291]
Currently if the publish to npm step fails the [travis build](https://travis-ci.org/OmniSharp/generator-aspnet) passes, for example https://travis-ci.org/OmniSharp/generator-aspnet/builds/73074286.

Ideally the build would fail in this case as well to notify everyone of the error.

Also related #290

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
