### ISSUE TITLE
Automated publish no longer working

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#292]
There has been some changes and the [travis build](https://travis-ci.org/OmniSharp/generator-aspnet) is no longer publishing to npmjs.org. For example: https://travis-ci.org/OmniSharp/generator-aspnet/builds/73074286

@sayedihashimi will look into it.

**Comment by sayedihashimi** [comment]
Related issue https://github.com/npm/npm/issues/8970

**Comment by peterblazejewicz** [comment]
Looks like already fixed?

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
