### ISSUE TITLE
lib folder missing

### ISSUE THREAD

**Issue by varghesep** [OmniSharp/generator-aspnet#294]
In the asp.net 5, there are three environments (1) Development (2) Staging and (3) Production. Using the command **set ASPNET_ENV = Development** at the command line, the project can be run with development settings. In the development environment, the **_Layout.cshtml*** refers a **lib** folder

``` html
        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
            <link rel="stylesheet" href="~/winstrap/css/winstrap.css"/>
        </environment>
```

During the scaffolding, the **lib** folders are not deployed which should contain the css and js files. Please see the attached image.

![yo](https://cloud.githubusercontent.com/assets/12233474/8982814/4b80fa78-368a-11e5-97e3-c147b52b7319.png)

**Comment by Spinarooni** [comment]
@varghesep The lib folder is created when the bower packages are restored.  Have you tried running 'bower install' from the command line in the project directory?

**Comment by varghesep** [comment]
Thank you. I ran **bower install** and it created the **lib** folder.

**Comment by peterblazejewicz** [comment]
I think they guys at MS does not set yet how to automate the build process - they already added some relevant scripts to templates:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/project.json#L54-L62

@varghesep Does @Spinarooni answered your question?

**Comment by Spinarooni** [comment]
@peterblazejewicz Could you use the "postrestore" event in project.json to restore the bower packages?

    "postrestore": [
      "npm install",
      "bower install"
    ]

**Comment by sayedihashimi** [comment]
We had that before. I think the problem was that Visual Studio calls restore and the scripts would take a while to execute. Adding @rustd and @madskristensen to comment back.

**Comment by varghesep** [comment]
@peterblazejewicz Yes. I'm able to see the test website that I was working on.

**Comment by peterblazejewicz** [comment]
There is not much change to state of this implementation problem. The 'dnu restore' does not trigger `npm` nor `bower` installs as of RC1.
Thanks!
