### ISSUE TITLE
Should we use 'postrestore' in 'project.json' script as supported build phase?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#295]
In relation to #294 I have a doubt if we should use `prepublish` build phase in `project.json`:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/project.json#L54-L62
That exact step is not listed in the docs:
https://github.com/aspnet/Home/wiki/Project.json-file#scripts
http://json.schemastore.org/project

@sayedihashimi

**Comment by sayedihashimi** [comment]
I think that wiki is our of date. The prepublish strip should be executed when dnu publish is called.

How do you suggest that we change it?

**Comment by peterblazejewicz** [comment]
to 'postrestore', it works and is documented:
http://json.schemastore.org/project
https://github.com/OmniSharp/generator-aspnet/issues/294#issuecomment-126416670
```
➜  WebApplicationBasic  dnu restore
...
Restoring packages for /Users/piotrblazejewicz/dev/WebApplicationBasic/project.json
  GET https://www.nuget.org/api/v2/
  ....
  OK https://www.nuget.org/api/v2/package/System.Linq.Expressions/4.0.0-beta-23109 3585ms
Writing lock file /Users/piotrblazejewicz/dev/WebApplicationBasic/project.lock.json

Executing script 'postrestore' in project.json

npm WARN package.json WebApplicationBasic@0.0.0 No repository field.
npm WARN package.json WebApplicationBasic@0.0.0 No license field.
rimraf@2.2.8 node_modules/rimraf
.....
````

**Comment by peterblazejewicz** [comment]
Title changed

**Comment by peterblazejewicz** [comment]
reference from docs:
http://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html?highlight=postrestore
> http://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html?highlight=postrestore

**Comment by sayedihashimi** [comment]
Is there any action needed here?

**Comment by peterblazejewicz** [comment]
Here no more probably, Shayne asked to move related discussion to #400
