### ISSUE TITLE
Setting up the environment variable ASPNET_DEV

### ISSUE THREAD

**Issue by varghesep** [OmniSharp/generator-aspnet#296]
It would have been nice if there was some documentation on setting up the Environment variable **ASPNET_DEV**. I followed the documentation on [Visual Studio Code](https://code.visualstudio.com/) to create the asp.net 5 application. The build is for Staging/Production by default if the environment is not set up at the OS system level. I don't know is it the right approach to control the build via OS level environment variable.

Is there a better solution by controlling the build from some settings from the project folder? I'm thinking, by default, the **build** should be for development and during the **publish** to Azure, a staging or production release is selected.

**Comment by peterblazejewicz** [comment]
One needs to specify them either when running process (dnx) or within project configuration:
```json
"commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --ASPNET_ENV development --config hosting.ini",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --ASPNET_ENV development --config hosting.ini"
  },
```
https://github.com/peterblazejewicz/CustomTagHelper/blob/master/src/project.json#L21

**Comment by peterblazejewicz** [comment]
Also on Windows with IIS:
http://docs.asp.net/en/latest/fundamentals/environments.html?highlight=launchsettings

**Comment by sayedihashimi** [comment]
@varghesep the default value is determined by the ASP.NET 5 runtime. The feedback/questions that you're bringing up should be brought up in the https://github.com/aspnet/dnx repository. This repo is just for the yeoman templates.
