### ISSUE TITLE
Make sure to switch `hosting.ini' to `hosting.json' when shipped

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#298]
A note: make sure in future changes to double-check, if provided templates do use changed 'hosting.json' files:
https://github.com/aspnet/Hosting/issues/269
https://github.com/aspnet/Hosting/pull/270

Thanks!

**Comment by peterblazejewicz** [comment]
This one does not get implemented yet on upstream:
https://github.com/aspnet/Tooling/issues/140
Removing `beta7` tag

**Comment by spboyer** [comment]
@peterblazejewicz Close this?  now that this file is no longer here...

**Comment by peterblazejewicz** [comment]
Yes, we will see what `rc1` brings LoL
