### ISSUE TITLE
Add `applicationId` token generator for user secrets [feature]

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#303]
I'm writing a small project progression to use config/env and now user secrets store and I found a problem outlined in ASP5 documentation after battling how to use `user-secret` tool on OS X (so no VS):

https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration#generator-support
> Generator support
Visual Studio: Visual Studio will generate a <SuperSecretStuffId> and put it in your project.json if you go through the auth flow of the new web application wizard. It will also put the values you configure in the wizard into your user secret configuration.
No other generators yet, but if you have one that works feel free to send a PR to add it to this list.

And in official docs:
http://docs.asp.net/en/latest/security/app-secrets.html#how-the-secret-manager-tool-works
> The applicationId comes from the the project.json file and is arbitrary, but should be unique unless you have a reason for it not to be. The following markup shows a portion of the project.json file with the applicationId highlighted:
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-WebApplication1-f7fd3f56-2899-4eea-a88e-673d24bd7090",
  "version": "1.0.0-*"
}
The userSecretsId key for the applicationId highlighted above was generated by Visual Studio.

Can we do this?
> No other generators yet, but if you have one that works feel free to send a PR to add it to this list.

We have all things in place:
* the user picks a template project (just like in VS)
* the user enters project name used later as namespace:
https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L103
* we already generates hashes, e.g. for connection strings:
https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L106

So I propose  the implementation should just go Visual Studio-ish way and simply add user secret/application secret it to `project.json` as part of scaffoling any project via templates where this make sense to use Microsoft.Framework.Configuration. I'm using it now in console application for example and will use secrets for tokens and sids from 3rd party service.

If we add that feature we should simply make PR to update ASP5 docs and make a blog post describing how to use `generator-aspnet` scaffolded projects with user-secret tool together.

The my stance on this problem is that I had really hard time to figure out why my `user-secret` tool keeps complaining about missing 'usersecretsids':
```
critical: Command failed : Missing 'userSecretsId' in ...
```

If that is part of VS scaffolding we should add this as well I think.

/cc 'S'-men team :)
@Spinarooni @sayedihashimi @spboyer

**Comment by peterblazejewicz** [comment]
Ops - I've just found we are doing it already for web project:
https://github.com/OmniSharp/generator-aspnet/blame/master/templates/projects/web/project.json#L3
and it was me who ported this as part of beta5 updates.

Still valid points for other types of projects (web basic/web api/etc)

**Comment by Spinarooni** [comment]
Agreed.

**Comment by peterblazejewicz** [comment]
@Spinarooni Thanks!

**Comment by Spinarooni** [comment]
@peterblazejewicz If we add the`userSecretsId` property to project.json for other projects would we also want to add the `Microsoft.Framework.Configuration.UserSecrets` dependency?
