### ISSUE TITLE
Opening with Xamarin Studio?

### ISSUE THREAD

**Issue by rawberg** [OmniSharp/generator-aspnet#310]
Does anybody have guidance on how to work with the generated projects in Xamarin Studio? Can't seem to import the generated directory into a new project. I can create blank project and add the files from the generated directory. Is there a better way?

**Comment by sayedihashimi** [comment]
Sorry I'm not familiar with Xamarin, maybe someone else here is.

**Comment by spboyer** [comment]
@rawberg can you past the error, or give some more information as to the issue you are having opening the generated project?  I would suggest that you use VS Code, Brackets or one of the editors with OmniSharp on OS X or Visual Studio on PC. Xamarin Studio does not support ASP.NET 5

**Comment by rawberg** [comment]
Was hoping the generator would create a .csproj or .sln file which could be opened by Xamarin Studio. It would be great to have one IDE for all C# projects on Mac.

Unfortunately importing a project that doesn't have one of these files is a kludgy process for Xamarin Studio. I imagine as it get's closer to official release they'll officially support ASP.NET 5.

**Comment by spboyer** [comment]
@rawberg There is no .csproj or .sln for ASP.NET 5

**Comment by rawberg** [comment]
How about .xproj? The latest ASP.NET samples seem to [include](https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta7/HelloMvc) [these](https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta7/HelloWeb) and the [MusicStore example](https://github.com/aspnet/MusicStore) still has an .sln.

**Comment by spboyer** [comment]
Yes if you open the files in visual studio, these files are added, as these are needed for vs.

**Comment by sayedihashimi** [comment]
As @spboyer discussed in Visual Studio when you do `File->Open Project` in Visual Studio you can select `project.json` and it will create the .xproj file for you. It'd be nice if Xamarin could do something similar if it requires an `.xproj` file.

I am not sure what % of users are calling `yo aspnet` who are using Xamarin, but my hunch tells me that it's not a large % of users. So I don't think it would make sense to create an `.xproj` file for each project. One thing that we could consider is to create a subgenerator (i.e. equivalent to VS `File->Add New Item`) which can be used to create the `.xproj` file after the project has been created.
