### ISSUE TITLE
Exceeded maximum path length

### ISSUE THREAD

**Issue by cveld** [OmniSharp/generator-aspnet#311]
I was trying out an app generated by the webapplication option and the --grunt switch within the aspnet generator and running the WebListener webserver. After a while the dnx runtime crashed due to an exception with regards to a file access with a path or filename that had exceeded the maximum allowed length:

<code>The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.</code>

Using beta6 of the dnx stack. OS: Windows 10 Pro
Base folder:
G:\not shared\Dropbox-W10\Dropbox\src\Visual Studio 2015\yeomanwebapp\WebApp2

**Comment by peterblazejewicz** [comment]
@cveld 
That's probably not `generator-aspnet` issue, but dnx one:
https://github.com/aspnet/dnx/issues/1173
https://github.com/aspnet/dnx/issues/2179
As you are probably running VS2015 - does it happen when you generate the same project type (with Grunt as option if possible) via VS2015?

**Comment by sayedihashimi** [comment]
VS no longer has a grunt option.

I think the best thing to try is moving it to a shorter path and use the flatten packages package. In the long term I think npm v3 should hopefully solve this.

**Comment by cveld** [comment]
About Grunt:
I believe the ASP.NET ecosystem should provide options and therefore also
provide a scenario to work with Grunt. Most of the
Angular/TypeScript/Webapi tutorials I found are towards Grunt by the way.
Strangely, Microsoft decided to go for Gulp only. There is no decision yet
in the community. Both tools attract an equal amount of fans.

About flattening the packages:
Can you help? Where can I find this flatten packages package.

About possibly experiencing the issue within Visual Studio:
I have not yet experienced the same issue when playing within Visual Studio
and using IIS Express.

2015-08-24 0:04 GMT+02:00 Sayed Ibrahim Hashimi <notifications@github.com>:

**Comment by scottaddie** [comment]
@cveld You can find the "flatten-packages" NPM module [here](http://scottaddie.com/2015/08/16/npm-vs-windows-max_path-limitation/). There's also a Visual Studio extension available to make it even easier. I wrote a [blog post](http://scottaddie.com/2015/08/16/npm-vs-windows-max_path-limitation/) about this very topic a while back.

**Comment by spboyer** [comment]
@cveld install npm3, this will solve your issue.

**Comment by sayedihashimi** [comment]
Closing as there is nothing for us to do in generator-aspnet here.
