### ISSUE TITLE
ASP.NET WebApp (No Auth) for beta7

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#316]
Feed used: https://www.myget.org/F/aspnetliterelease/api/v2 
 Samples are here: https://onedrive.live.com/redir?resid=43459A6389A804D9%21102054

**Comment by Spinarooni** [comment]
@peterblazejewicz I'll take this one.

**Comment by sayedihashimi** [comment]
@Spinarooni it seems like I should add you to the OmniSharp organization, let me know if you'd like an invite.

**Comment by peterblazejewicz** [comment]
@Spinarooni 
assigned - the `beta7` branch is already made from clean master so you could start with PR
Thanks!

**Comment by Spinarooni** [comment]
@peterblazejewicz @sayedihashimi I know that last time we specified the dependices in Beta6 as beta6 but again in the example files they are using *.  Do we use * or beta7?

	"Microsoft.AspNet.Diagnostics": "1.0.0-*",
	"Microsoft.AspNet.Mvc": "6.0.0-*",
	"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*",
	"Microsoft.AspNet.Server.IIS": "1.0.0-*",
	"Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
	"Microsoft.AspNet.Server.WebListener": "1.0.0-*",
	"Microsoft.AspNet.StaticFiles": "1.0.0-*",
	"Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
	"Microsoft.Framework.Configuration.Json": "1.0.0-*",
	"Microsoft.Framework.Logging": "1.0.0-*",
	 "Microsoft.Framework.Logging.Debug" : "1.0.0-*",   "Microsoft.Framework.Logging.Console": "1.0.0-*"

**Comment by Spinarooni** [comment]
When trying to use beta7 on restore I get this:

	Errors in C:\DevProjects\VSCode\WebApplicationBasic\project.json
    	Unable to locate Microsoft.Dnx.Compilation.CSharp.Common >= 1.0.0-beta7

Output:

	λ dnu restore -f https://nuget.org/api/v2/
	Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15524
	
	Restoring packages for C:\DevProjects\VSCode\WebApplicationBasic\project.json
	  CACHE https://www.nuget.org/api/v2/
	  CACHE https://www.myget.org/F/aspnetbeta7/api/v2/
	  CACHE https://nuget.org/api/v2/
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Dnx.Compilation.CSharp.Common'
	  CACHE https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='Microsoft.Dnx.Compilation.CSharp.Common'
	  CACHE https://nuget.org/api/v2/FindPackagesById()?id='Microsoft.Dnx.Compilation.CSharp.Common'
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
	  CACHE https://www.myget.org/F/aspnetbeta7/api/v2/FindPackagesById()?id='System.Reflection'
	  CACHE https://nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
	Unable to locate Microsoft.Dnx.Compilation.CSharp.Common >= 1.0.0-beta7
	Writing lock file C:\DevProjects\VSCode\WebApplicationBasic\project.lock.json
	Restore complete, 899ms elapsed
	
	Errors in C:\DevProjects\VSCode\WebApplicationBasic\project.json
	    Unable to locate Microsoft.Dnx.Compilation.CSharp.Common >= 1.0.0-beta7
	
	NuGet Config files used:
	    C:\Users\repatterson\AppData\Roaming\NuGet\NuGet.Config
	    C:\DevProjects\VSCode\WebApplicationBasic\NuGet.Config
	
	Feeds used:
	    https://www.nuget.org/api/v2/
	    https://www.myget.org/F/aspnetbeta7/api/v2/
	    https://nuget.org/api/v2/

**Comment by peterblazejewicz** [comment]
@Spinarooni 
mind to check this, so we wouldn't override with empty script:
https://github.com/aspnet/Tooling/issues/132

**Comment by Spinarooni** [comment]
@peterblazejewicz I made sure to retain that script reference.

**Comment by peterblazejewicz** [comment]
> Errors in C:\DevProjects\VSCode\WebApplicationBasic\project.json
>     Unable to locate Microsoft.Dnx.Compilation.CSharp.Common >= 1.0.0-beta7

I'm getting the same. 
I think they haven't released that package to nuget feed yet, as it is not yet listed (or maybe I'm reading this list wrong):
https://www.myget.org/gallery/aspnetbeta7


> Do we use * or beta7?

I don't know - that's up to MS guys.

@sayedihashimi

**Comment by Spinarooni** [comment]
With the new feed (http://myget.org/F/aspnetbeta7take2/api/v2) the restore works. However I am getting a compilation error on build:

	C:\DevProjects\VSCode\WebApplicationBasic\Startup.cs(43,27): DNXCore,Version=v5.0 error CS1061: 'ILoggerFactory' 
		does not contain a definition for 'AddDebug' and no extension method 'AddDebug' accepting a first argument of 
		type 'ILoggerFactory' could be found (are you missing a using directive or an assembly reference?)

Line 43 of Startup.cs.

	loggerFactory.AddDebug();

I think maybe the Web Basic template provided is missing a dependency in the project.json file.

	    "Microsoft.Framework.Logging.Debug" : "1.0.0-beta7"

**Comment by peterblazejewicz** [comment]
@Spinarooni 
You could be correct:
http://www.elanderson.net/2015/08/viewing-sql-for-entity-framework-7-queries/
> In project.json add a dependency for Microsoft.Framework.Logging.Debug

Are you able to make a PR and update it with rebase and forced updates? It would be easier to help you with this. We add 'bug'/'blocking' tags to be sure that PR is not merged before issues are solved.

**Comment by Spinarooni** [comment]
@peterblazejewicz I'll rebase and send a PR.
