### ISSUE TITLE
ASP.NET Web App (With Auth) for beta7

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#317]
Feed used: https://www.myget.org/F/aspnetliterelease/api/v2 
Samples are here: https://onedrive.live.com/redir?resid=43459A6389A804D9%21102054

**Comment by peterblazejewicz** [comment]
Me, thanks!

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/6828e0d11dc3eaba727b30153654f715c9a90d92
