### ISSUE TITLE
:question: Is there ASP.NET xUnit Test project template for beta7

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#318]
@rustd 
@sayedihashimi 
Is there xUnit template project update for `beta7` planned? 
Thanks!

**Comment by sayedihashimi** [comment]
@rustd can you post the xUnit beta7 .zip file?

**Comment by rustd** [comment]
There is no xUnit template since the xUnit bits are not compatible with beta7. This can be updated later when there is a xUnit package that works with beta7

**Comment by sayedihashimi** [comment]
@rustd so there's no story for xUnit in beta7? That sucks that we shipped a template with it and it will no longer work.

**Comment by peterblazejewicz** [comment]
Guys, closing in favour of:
https://github.com/OmniSharp/generator-aspnet/issues/327
Thanks!
