### ISSUE TITLE
Beta7 known issues

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#326]
## Known issues

 - [xUnit template still targets beta6](https://github.com/OmniSharp/generator-aspnet/issues/327) - the xUnit runner has not yet been updated for beta7 so it still targets beta6. When beta7 support is released we will update it.
 - [Nancy project doesn't run](https://github.com/OmniSharp/generator-aspnet/issues/328)

**Comment by sayedihashimi** [comment]
@peterblazejewicz @Spinarooni thanks a lot for all your contributions in `beta7`. I want to make sure that @shanselman is aware that you guys have helped out for this release.

@peterblazejewicz @Spinarooni once we fix the issues above we should think about blogging about the update in the [official ASP.NET team blog](http://blogs.msdn.com/b/webdev/). It's a great chance to get your name on the official blog and to get your name out there a bit more. If either of you are interested (_or anyone else if reading this for that matter_) please let me know.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I'm not sure if beta7 branch has been merged back to master fully:
https://github.com/OmniSharp/generator-aspnet/commits/beta7

**Comment by sayedihashimi** [comment]
@peterblazejewicz thanks for letting me know I just updated it. After we get the xUnit and Nancy template updated I'll push another release.

**Comment by peterblazejewicz** [comment]
> thanks for letting me know

You're welcome :)

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
we have already updated Nancy:
https://github.com/OmniSharp/generator-aspnet/commit/e7db397abc5cabb52a02195718b752878a43a57c
https://github.com/OmniSharp/generator-aspnet/commit/bdc1ed0d54a757c848472c5992843b7772b92fc8

**Comment by potatman** [comment]
The 0.7.1 build in NPMJS is supposed to be beta7 right?  I pulled down that build via npm update and the resulting project is still the same as beta6.  All refs in project.json are to beta6, which clearly is not an issue if I pull down the source for the generator instead.

**Comment by sayedihashimi** [comment]
Thanks @potatman, I think it was a merge error on my part. I've merged all changes and started a new build for `0.0.72` https://travis-ci.org/OmniSharp/generator-aspnet/builds/78492009.

**Comment by sayedihashimi** [comment]
@potatman OK, `0.0.72` is now available. I tried it and it contains `beta7`.

**Comment by potatman** [comment]
Cool, thanks, the rebuild fixed it for me.

**Comment by JaimeStill** [comment]
I just did a full Web App build of beta7, and the only issue I ran into was the using statements in the Views > _ViewImports.cshtml file. Rather than @using MyWebApp, they were targeting @using WebApplication.

**Comment by Spinarooni** [comment]
@JaimeStill Should be fixed with PR https://github.com/OmniSharp/generator-aspnet/pull/333

**Comment by JaimeStill** [comment]
Awesome, thanks!

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
both are fixed. Now xUnit:
https://github.com/peterblazejewicz/generator-aspnet/commit/2fc27283bd8530f28babd8b8c45abef326203571

**Comment by peterblazejewicz** [comment]
@sayedihashimi closing this one. Thanks!
