### ISSUE TITLE
Namespace generated incorrectly in Web App _ViewImports.cshtml

### ISSUE THREAD

**Issue by Spinarooni** [OmniSharp/generator-aspnet#332]
Reference [https://github.com/OmniSharp/generator-aspnet/issues/326#issuecomment-137302801](https://github.com/OmniSharp/generator-aspnet/issues/326#issuecomment-137302801)

**Comment by peterblazejewicz** [comment]
closed via:
https://github.com/Spinarooni/generator-aspnet/commit/fe773043d1e49f1e9770af538e57275741d41e4a

**Comment by sayedihashimi** [comment]
FYI I just released version `0.0.73` which contains this fix.

cc @chrisdias
