### ISSUE TITLE
"npm update -g generator-aspnet" is generating beta5 instead of beta7

### ISSUE THREAD

**Issue by MaherJendoubi** [OmniSharp/generator-aspnet#334]
After installing all the tooling for asp.net beta 7 and doing npm install -g generator-aspnet (generator-aspnet version: 0.0.72), I get the following beta 5 stuff instead of beta 7!!
![image](https://cloud.githubusercontent.com/assets/1798510/9674287/40360e74-52af-11e5-808a-6c097ad531d3.png)

**Comment by sayedihashimi** [comment]
That looks right to me, the only thing I can think to try is clear your npm cache, uninstall and reinstall.

**Comment by MaherJendoubi** [comment]
I cleared my npm cache, uninstalled and reinstalled but in vain always beta5 references are generated...

**Comment by MaherJendoubi** [comment]
I have 2 machines one win7 and the other is win10. I tested on my win7 it works but still my problem on windows 10.

**Comment by peterblazejewicz** [comment]
@MaherJendoubi 
```
npm list -g --depth=0
```
This will list a complete list of your NPM packages installed with `-g` flag. It should list `generator-aspnet`, its path and version.
For example on my machine (OS X) it lists:
```
/usr/local/lib
├── generator-aspnet@0.0.72 -> /Users/piotrblazejewicz/git/generator-aspnet
```
which is correct - it means that the symlink in my `/usr/local/lib` points to development version of generator (we are using it locally while developing).
Your one should point different location (as you are on Windows) but the rule is the same.
When you go into pointed location you could just check manually what version of generator `package.json` is installed and for example what template is in `{GENERATOR_INSTALLATION}/templates/projects/web/project.json'

**Comment by MaherJendoubi** [comment]
I'm on Windows 10 and here is the result of npm list -g --depth=0

![image](https://cloud.githubusercontent.com/assets/1798510/9694905/16cf4286-535d-11e5-9111-71255d1586d8.png)

**Comment by sayedihashimi** [comment]
I'm baffled here, maybe it would help to open an issue with npm?

**Comment by MaherJendoubi** [comment]
good idea why not? Thanks.

**Comment by bstenberg64** [comment]
@MaherJendoubi, this is happening to me too although I'm on Windows 8.1 (still). Did you raise an issue with npm or should I?

**Comment by MaherJendoubi** [comment]
Sorry not yet! Would you please raise it? Thanks.

**Comment by bstenberg64** [comment]
No worries. I'm not sure it's an npm issue though. The app still won't deploy correctly from github to azure. I'll look into it and get back.

**Comment by sayedihashimi** [comment]
@bstenberg64 if you don't think it's an npm issue than what could it be?

**Comment by bstenberg64** [comment]
@sayedihashimi Sorry, real world stuff got between me and this. I use the generator to create a new basic web application (no membership and authorization). Running it locally, using `dnx web`, works just fine. Deploying this to a new Azure web app will fail as the deployment script will use the beta5 runtime. If I add a `global.json` file to the project with the following content

    {
      "sdk": {
        "version": "1.0.0-beta7"
      }
    }

in it and then deploy to Azure the deployment script will be generated using the following command:

    azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNet5 "D:\home\site\repository\project.json" --aspNet5Version "1.0.0-beta7" --aspNet5Runtime "CLR" --aspNet5Architecture "x86"'.

which looks good to me. `--aspNet5Version` is set correctly to `1.0.0-beta7`. When I browse to the site I get an error which I've pasted below. It's a long error message about unresolved references so it seems that something is not correct in the deployment process. Some path is not set correctly on the host or do I need to explicitly set dependencies in my `project.json`file? But this is why I feel that the error is not an npm issue but rather an Azure deployment/kudu issue. I'm new to the tooling though so I'm grasping at straws at the moment. I'm just making half-educated guesses...

#### Long error message about unresolved references: ####
```
Server Error in '/' Application.

Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Microsoft.AspNet.Antiforgery 1.0.0-beta7
   Microsoft.AspNet.Authorization 1.0.0-beta7
   Microsoft.AspNet.Cors.Core 1.0.0-beta7
   Microsoft.AspNet.Cryptography.Internal 1.0.0-beta7
   Microsoft.AspNet.DataProtection 1.0.0-beta7
   Microsoft.AspNet.DataProtection.Abstractions 1.0.0-beta7
   Microsoft.AspNet.Diagnostics 1.0.0-beta7
   Microsoft.AspNet.Diagnostics.Abstractions 1.0.0-beta7
   Microsoft.AspNet.FileProviders.Abstractions 1.0.0-beta7
   Microsoft.AspNet.FileProviders.Physical 1.0.0-beta7
   Microsoft.AspNet.Hosting 1.0.0-beta7
   Microsoft.AspNet.Hosting.Abstractions 1.0.0-beta7
   Microsoft.AspNet.Hosting.Server.Abstractions 1.0.0-beta7
   Microsoft.AspNet.Html.Abstractions 1.0.0-beta7
   Microsoft.AspNet.Http 1.0.0-beta7
   Microsoft.AspNet.Http.Abstractions 1.0.0-beta7
   Microsoft.AspNet.Http.Extensions 1.0.0-beta7
   Microsoft.AspNet.Http.Features 1.0.0-beta7
   Microsoft.AspNet.JsonPatch 1.0.0-beta7
   Microsoft.AspNet.Loader.IIS 1.0.0-beta7
   Microsoft.AspNet.Loader.IIS.Interop 1.0.0-beta7
   Microsoft.AspNet.Localization 1.0.0-beta7
   Microsoft.AspNet.Mvc 6.0.0-beta7
   Microsoft.AspNet.Mvc.Abstractions 6.0.0-beta7
   Microsoft.AspNet.Mvc.ApiExplorer 6.0.0-beta7
   Microsoft.AspNet.Mvc.Core 6.0.0-beta7
   Microsoft.AspNet.Mvc.Cors 6.0.0-beta7
   Microsoft.AspNet.Mvc.DataAnnotations 6.0.0-beta7
   Microsoft.AspNet.Mvc.Formatters.Json 6.0.0-beta7
   Microsoft.AspNet.Mvc.Localization 6.0.0-beta7
   Microsoft.AspNet.Mvc.Razor 6.0.0-beta7
   Microsoft.AspNet.Mvc.Razor.Host 6.0.0-beta7
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta7
   Microsoft.AspNet.Mvc.ViewFeatures 6.0.0-beta7
   Microsoft.AspNet.PageExecutionInstrumentation.Interfaces 1.0.0-beta7
   Microsoft.AspNet.Razor 4.0.0-beta7
   Microsoft.AspNet.Razor.Runtime 4.0.0-beta7
   Microsoft.AspNet.Routing 1.0.0-beta7
   Microsoft.AspNet.Server.IIS 1.0.0-beta7
   Microsoft.AspNet.Server.Kestrel 1.0.0-beta7
   Microsoft.AspNet.Server.WebListener 1.0.0-beta7
   Microsoft.AspNet.StaticFiles 1.0.0-beta7
   Microsoft.AspNet.Tooling.Razor 1.0.0-beta7
   Microsoft.AspNet.WebUtilities 1.0.0-beta7
   Microsoft.CodeAnalysis.Analyzers 1.1.0-beta1-20150812-01
   Microsoft.CodeAnalysis.Common 1.1.0-beta1-20150812-01
   Microsoft.CodeAnalysis.CSharp 1.1.0-beta1-20150812-01
   Microsoft.Dnx.Compilation.Abstractions 1.0.0-beta7
   Microsoft.Dnx.Compilation.CSharp.Abstractions 1.0.0-beta7
   Microsoft.Dnx.Compilation.CSharp.Common 1.0.0-beta7
   Microsoft.Dnx.Runtime.Abstractions 1.0.0-beta7
   Microsoft.Framework.Caching.Abstractions 1.0.0-beta7
   Microsoft.Framework.Caching.Memory 1.0.0-beta7
   Microsoft.Framework.Configuration 1.0.0-beta7
   Microsoft.Framework.Configuration.Abstractions 1.0.0-beta7
   Microsoft.Framework.Configuration.Binder 1.0.0-beta7
   Microsoft.Framework.Configuration.CommandLine 1.0.0-beta7
   Microsoft.Framework.Configuration.EnvironmentVariables 1.0.0-beta7
   Microsoft.Framework.Configuration.Ini 1.0.0-beta7
   Microsoft.Framework.Configuration.Json 1.0.0-beta7
   Microsoft.Framework.DependencyInjection 1.0.0-beta7
   Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta7
   Microsoft.Framework.FileSystemGlobbing 1.0.0-beta7
   Microsoft.Framework.Globalization.CultureInfoCache 1.0.0-beta7
   Microsoft.Framework.Localization 1.0.0-beta7
   Microsoft.Framework.Localization.Abstractions 1.0.0-beta7
   Microsoft.Framework.Logging 1.0.0-beta7
   Microsoft.Framework.Logging.Abstractions 1.0.0-beta7
   Microsoft.Framework.Logging.Console 1.0.0-beta7
   Microsoft.Framework.Logging.Debug 1.0.0-beta7
   Microsoft.Framework.Notification 1.0.0-beta7
   Microsoft.Framework.OptionsModel 1.0.0-beta7
   Microsoft.Framework.WebEncoders 1.0.0-beta7
   Microsoft.Framework.WebEncoders.Core 1.0.0-beta7
   Microsoft.Net.Http.Headers 1.0.0-beta7
   Microsoft.Net.Http.Server 1.0.0-beta7
   Microsoft.Net.WebSockets 1.0.0-beta7
   Newtonsoft.Json 6.0.6
   System.Collections 4.0.0
   System.Collections.Immutable 1.1.36
   System.Diagnostics.Debug 4.0.0
   System.IO 4.0.0
   System.Reflection 4.0.0
   System.Reflection.Extensions 4.0.0
   System.Reflection.Metadata 1.1.0-alpha-00009
   System.Reflection.Primitives 4.0.0
   System.Resources.ResourceManager 4.0.0
   System.Runtime 4.0.0
   System.Runtime.Extensions 4.0.0
   System.Runtime.InteropServices 4.0.0
   System.Text.Encoding 4.0.0
   System.Text.Encoding.Extensions 4.0.0
   System.Threading 4.0.0

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-15532
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0
 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Microsoft.AspNet.Antiforgery 1.0.0-beta7
   ...(repeat list of unresolved references from above)...
   System.Threading 4.0.0

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-15532
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0


Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 



[InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Microsoft.AspNet.Antiforgery 1.0.0-beta7
   ...(repeat list of unresolved references from above)...
   System.Threading 4.0.0

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-15532
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0
]

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +506

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +4531288
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +94
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +191

  


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.81.0  
```

**Comment by MaherJendoubi** [comment]
I'm thrilled that my issue is now solved thanks the great help to @tugberkugurlu who recommand me to check "where yo" after monitoring yo process using procmon. We saw that there were two paths for yeoman. I deleted the yo stuff under roaming path, then I cleared the npm cache and finally I reinstalled yeoman and generator-aspnet. I tested and it works as a charm :+1: 

![image](https://cloud.githubusercontent.com/assets/1798510/9831428/9868554e-5957-11e5-9547-2b702f15a4a3.png)

**Comment by sayedihashimi** [comment]
@bstenberg64 it should work when publishing to Azure. Can you open a new issue so we don't overload this issue? It seems like some pkg dependencies are not getting published.

@MaherJendoubi I'm glad you were able to resolve this. That sounds like a nasty bug. Can we close this issue now?

**Comment by MaherJendoubi** [comment]
@sayedihashimi Thank you so much Sir for the great help! Yes, we can close this issue now. I appologize for that nasty bug :)

**Comment by MaherJendoubi** [comment]
BTW Could you please update the gif image ( https://github.com/OmniSharp/generator-aspnet )  that's showing dnx . web old stuff and put dnx web?

**Comment by MaherJendoubi** [comment]
@sayedihashimi I mean this gif : 
![image](https://cloud.githubusercontent.com/assets/1798510/9831818/f93b0e62-5965-11e5-94b0-9f1ea58893ac.png)

**Comment by peterblazejewicz** [comment]
> BTW Could you please update the gif image ( https://github.com/OmniSharp/generator-aspnet ) that's showing dnx . web old stuff and put dnx web?

@MaherJendoubi Yes, :racehorse:  Thanks!

**Comment by peterblazejewicz** [comment]
@bstenberg64 
Please repost on new issue if problem persists, as we are closing this one.
Thanks!
