### ISSUE TITLE
Remove duplicate Bootstrap "btn-default" class

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#338]
When generating a Web Application Basic, the Views/Home/Index.cshtml file's "Learn More" anchor tag has 2 occurrences of the Bootstrap "btn-default" CSS class applied to it. Please remove one of them.

**Comment by peterblazejewicz** [comment]
@scottaddie 
Thanks!
Yes, we already know this. We resubmit content to other repository (all templates are prepared by MS VisualStudio tooling team):
https://github.com/aspnet/Tooling/issues/156
Please add your +1 in the linked issue.

**Comment by scottaddie** [comment]
@peterblazejewicz +1 added to the linked issue. Thank you!

**Comment by peterblazejewicz** [comment]
closed via:
https://github.com/OmniSharp/generator-aspnet/pull/349/commits
