### ISSUE TITLE
Should we add .gitignore to UnitTest template?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#341]
All project templates create `.gitignore`. It looks like a simple ommision in MS tooling team to not include it in samples. 
Should we add one here to project template and make a ticket in tooling repo? Or just add issue on for tooling team and wait until fixed/accepted?

@sayedihashimi @rustd

**Comment by sayedihashimi** [comment]
For cases like this we should go ahead and make the change and open a tooling issue so that VS will update on next release.
