### ISSUE TITLE
Usage tips should include UnitTest `dnx test` hint

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#342]
We ship UnitTest project template now, but usage tips outputted by the `end` method do not have references to unit test usage.
The xUnit team described usage tip for xUnit under beta7 as:
```
dnx test
```
http://xunit.github.io/docs/getting-started-dnx.html

Should we add this?

That way it will be propagated to people using it and to docs and posts.

Thanks!

**Comment by sayedihashimi** [comment]
I think it would be good. Right now I think we show the same message across project types. Maybe we should have a specific message per project now?

**Comment by peterblazejewicz** [comment]
> Maybe we should have a specific message per project now?

:+1: 
It will tremendously help as the tool matures. I was thinking about the same. Can you consult this with MS tooling/product team? That's good to know their stance.

I'll add usage tips PR.

**Comment by sayedihashimi** [comment]
@peterblazejewicz 
>Can you consult this with MS tooling/product team

I am the rep for the team here :) Let's go ahead with it.

**Comment by peterblazejewicz** [comment]
KK
