### ISSUE TITLE
Use platform-friendly directory separators

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/generator-aspnet#345]
Use forward slashes instead of back-slashes in templates.

e.g. when running WebApplication template on Linux, it behaves oddly due to the backslash in the filepath at  https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/Startup.cs#L41

```c#
Configuration["Data:DefaultConnection:ConnectionString"] = $@"Data Source={appEnv.ApplicationBasePath}/<%= namespace %>.db";
```
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/Startup.cs#L41

**Comment by peterblazejewicz** [comment]
@natemcmaster 
Is this related to your other post and source repo ticket?
https://github.com/aspnet/Microsoft.Data.Sqlite/issues/55#issuecomment-121693771
Thanks!

**Comment by natemcmaster** [comment]
@peterblazejewicz no. That ticket resolves what happens when a user does not specify and absolute path. In this example, an absolute path is specified (`ApplicationBasePath`). This issue is simply a note about using `/` not `\`.

**Comment by peterblazejewicz** [comment]
@natemcmaster 
Thanks!

@sayedihashimi 
Should we fix this here or first create ticket in `aspnet/tooling` upstream project?

**Comment by sayedihashimi** [comment]
We should fix it here. We don't want to be delayed by Visual Studio, instead we should lead.
