### ISSUE TITLE
don't hard coded namespace in _ViewImports.cshtml file

### ISSUE THREAD

**Issue by doggy8088** [OmniSharp/generator-aspnet#355]
I found a bug in this file:
https://github.com/OmniSharp/generator-aspnet/blob/beta7/templates/projects/web/Views/_ViewImports.cshtml

There are hard coded namespace `WebApplication` in this file which may cause error when user change the default app name.

**Comment by doggy8088** [comment]
I was found there is a dup #350

**Comment by peterblazejewicz** [comment]
@doggy8088 
Thanks! 
It should be fixed with *.74
https://twitter.com/sayedihashimi/status/643826331638063104
Go ahead and just update your version!

**Comment by doggy8088** [comment]
@peterblazejewicz Nice job! :+1:
