### ISSUE TITLE
*Canary* Tooling content access [Twitter]

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#358]
This issue is just started to discuss announcement by Damian Edwards about Canary tooling releases:
https://twitter.com/damianedwards/status/644576439925391361

/cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
The *early* access to content from Tooling future releases can be beneficial to people contributing here (and elsewhere) to avoid *all hands*/*waterfall* release for beta's. Someone contributing could be better accustomed to changes, spot problems early, make less errors, think about adding a test case or two.
The content won't be probably used at by many people. But at least one could see if *is there update to some core client component or is not'*, etc. I did a mistake in my past commit for beta7, something that bothers me. Just by knowing upcoming changes I would probably never do that mistake. 
I find @aspnet/Announcements useful for this reason.

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz I think that would be great if we could do something to help people get started.

I'm concerned that it may be a lot of work, but maybe it's not.

What were you thinking exactly here? Would we create a new generator for example `generator-aspnet-canary` or were you thinking to overload `generator-aspnet` somehow?

**Comment by peterblazejewicz** [comment]
I think the *canary* content has so many rough edges that it won't be a fun to release it via regular NPM releases - not mentioning another project or tool. My *Canary* Chrome browser regulary breaks a feature here and there.
We could just make a branch here so it could be developed and updated with *canary* content. Anyone interested in canary can just add a *template* (subgenerator) or a feature, just branching from this *canary* branch and linking generator locally (the same way as for contribution):
```
npm link
```
Exactly like with e.g. Bootstrap 4 alpha:
https://github.com/twbs/bootstrap/tree/v4-dev
Anyone can pick an alpha and play with branch locally (and contribute back).
That way anyone can provide a feedback back to Tooling team using *nix based tools early before final release.
Let me cook another example:
Q: How VS Tooling team plan to implement and provide support for `dnx-watch` feature that had been discussed in latest live.asp.net community standup:
https://github.com/aspnet/dnx/issues/2700
How it will work on my *nix setup? Maybe it won't work at all?
Thanks!

**Comment by sayedihashimi** [comment]
@peterblazejewicz ok i see. So to try canary users would have to `git clone` and then `npm link`. That makes sense. I think the flow could be like this.

 - Make changes in `canary` branch for current canary release
 - When a release happens create a new branch starting from `canary`

@rustd any concerns posting the .zip files for canary releases two days before the canary release goes out?

**Comment by peterblazejewicz** [comment]
closing as beta8 has arrived
