### ISSUE TITLE
Upgrade to Travis Container-based Infrastructure

### ISSUE THREAD

**Issue by shirhatti** [OmniSharp/generator-aspnet#359]
The newer [Travis Container-based Infrastructure has faster builds](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade).
It should be a trivial upgrade.

**Comment by sayedihashimi** [comment]
>It should be a trivial upgrade. 

@shirhatti can we expect a PR sometime soon? :)
