### ISSUE TITLE
Nancy Template server port and server.urls unification

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#361]
The Nancy project template is the only one that is using 5001 port:
https://github.com/OmniSharp/generator-aspnet/blob/670772e5978489ac9c7185d994531489bf496b34/templates/projects/nancy/project.json#L8
I think it would be better to unify all ports (at least for *kestrel*) to point to the same, 5000 port as used in other hosting.ini files:
```
server.urls=http://localhost:5000
```
https://github.com/OmniSharp/generator-aspnet/search?q=5000&type=Code&utf8=%E2%9C%93
Should this be reported to VS Tooling too?

**Comment by sayedihashimi** [comment]
Agreed on using 5000. No need to report it to VS.

**Comment by peterblazejewicz** [comment]
Merged. Thx!
