### ISSUE TITLE
Output specific message per project in the `end` method

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#363]
Based on discussion from this issue: #342

> Maybe we should have a specific message per project now?

The task is to split usage tips shown in `end` priority method depending on project type. So we no longer shown all usage tips, but only those related to project type. The common is `cd` to remind user to switch into output directory. The others depends on project type.

**Comment by sayedihashimi** [comment]
+1

**Comment by Spinarooni** [comment]
I can tackle this.

**Comment by sayedihashimi** [comment]
Thanks @spinarooni. Should I send u an invite to join the organization? You're more than welcome to one after all your efforts. I really appreciate all your hard work.

**Comment by Spinarooni** [comment]
@sayedihashimi Sure, send the invite.

**Comment by sayedihashimi** [comment]
@Spinarooni ok invite sent

**Comment by Spinarooni** [comment]
Outputs:

### Empty Application, Web Application / Basic, Web API, Nancy ###
	
	Your project is now created, you can use the following commands to get going
	    cd "EmptyApplication"
	    dnu restore
	    dnu build (optional, build will also happen when it's run)
	    dnx kestrel or dnx web for web projects

### Console Application ###

	Your project is now created, you can use the following commands to get going
	    cd "ConsoleApplication"
	    dnu restore
	    dnu build (optional, build will also happen when it's run)
	    dnx ConsoleApplication for console projects

### Class Library ###

	Your project is now created, you can use the following commands to get going
	    cd "ClassLibrary"
	    dnu restore
	    dnu build (optional, build will also happen when it's run)

### Unit Test Project ###

	cd "UnitTest"
	    dnu restore
	    dnu build (optional, build will also happen when it's run)
	    dnx test for unit test projects

One thing with the Class Library project, would it be best to remove the "build will also happen when it's run" part of the build message for that project?  Thoughts?

**Comment by peterblazejewicz** [comment]
@Spinarooni 
Without *or* or *for* - I think it would be better and clear message, so:
```
cd "EmptyApplication"
dnu restore
dnu build (optional, build will also happen when it's run)
dnx kestrel
```
```
cd "ConsoleApplication"
dnu restore
dnu build (optional, build will also happen when it's run)
dnx ConsoleApplication
```
```
dnu restore
dnu build (optional, build will also happen when it's run)
dnx test
```
So just instructions.

I could think about using `process.platform` to detect if we are on Windows, so we could output:
```
dnx web
```
on Windows for web projects as they could be hosted by IIS not Kestrel.
Some guy from MS should do a copy proof this as they could work on documentation for docs.asp.net on the same subject

**Comment by Spinarooni** [comment]
@peterblazejewicz Thoughts on this commit: https://github.com/Spinarooni/generator-aspnet/commit/c909495f279c73a8548cce78058c8b21525effd4.  I've added a check for Win32 and changed the messages as you suggested.

**Comment by peterblazejewicz** [comment]
Yes, something like this. Mind submitting PR? (after squashing commits and fixing a small typo in commit message).

**Comment by Spinarooni** [comment]
@peterblazejewicz PR sent,

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I'll update animated gif to reflect changes.

**Comment by sayedihashimi** [comment]
Thanks @Spinarooni and @peterblazejewicz
