### ISSUE TITLE
Can we add `Dockerfile` subgenerator?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#364]
I've been using aspnet/aspnet-docker based images to host generator-aspnet web appplications.
If we start adding a Dockerfile template subgenerator the users could get at some point in the future the same features that are coming to VS (dockerizing ASP.NET 5 applications):
http://docs.asp.net/en/latest/publishing/docker.html
http://www.hanselman.com/blog/PublishingAnASPNET5AppToDockerOnLinuxWithVisualStudio.aspx

Using official MS Docker image for ASP.NET 5:
https://hub.docker.com/r/microsoft/aspnet/
user could (assuming she has Docker installed) run application in container:
```
docker build -t my-app .
...
Successfully built 0be1d149ce39
```
```
docker run -i -t -p 5000:5000 my-app
Application started. Press Ctrl+C to shut down.
```
![image](https://cloud.githubusercontent.com/assets/14539/10005957/789c05ca-60ba-11e5-99d6-4f505e30e360.png)

The required changes:
```patch
diff --git a/Dockerfile/USAGE b/Dockerfile/USAGE
new file mode 100644
index 0000000..d7c398d
--- /dev/null
+++ b/Dockerfile/USAGE
@@ -0,0 +1,8 @@
+Description:
+	Creates a new Docker configuration file
+
+Example:
+	yo aspnet:Dockerfile
+
+	This will create:
+		Dockerfile
diff --git a/Dockerfile/index.js b/Dockerfile/index.js
new file mode 100644
index 0000000..1ac80fc
--- /dev/null
+++ b/Dockerfile/index.js
@@ -0,0 +1,13 @@
+'use strict';
+var util = require('util');
+var ScriptBase = require('../script-base-basic.js');
+
+var Generator = module.exports = function Generator() {
+  ScriptBase.apply(this, arguments);
+};
+
+util.inherits(Generator, ScriptBase);
+
+Generator.prototype.createItem = function() {
+  this.generateStandardFile('Dockerfile', 'Dockerfile');
+};
diff --git a/templates/Dockerfile b/templates/Dockerfile
new file mode 100644
index 0000000..2028286
--- /dev/null
+++ b/templates/Dockerfile
@@ -0,0 +1,13 @@
+FROM microsoft/aspnet:1.0.0-beta7
+
+COPY project.json /app/
+
+WORKDIR /app
+
+RUN ["dnu", "restore"]
+
+COPY . /app
+
+EXPOSE 5000
+
+ENTRYPOINT ["dnx", "-p", "project.json", "kestrel"]
diff --git a/test/subgenerators.js b/test/subgenerators.js
index 98e22e7..a35576c 100644
--- a/test/subgenerators.js
+++ b/test/subgenerators.js
@@ -48,6 +48,11 @@ describe('Subgenerators without arguments tests', function() {
     util.fileCheck('should create tsconfig.json file', 'tsconfig.json');
   });
 
+  describe('aspnet:Dockerfile', function() {
+    util.goCreate('Dockerfile');
+    util.fileCheck('should create Dockerfile file', 'Dockerfile');
+  });
+
 });
 
 /*
```

**Comment by peterblazejewicz** [comment]
btw: the home samples do contain Docker files:
https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta7

**Comment by spboyer** [comment]
:shipit: use this same file, I have a blog ready to go in this

**Comment by spboyer** [comment]
Should also add to the core projects, can assign to me

**Comment by peterblazejewicz** [comment]
@spboyer 
You're welcome. All in your hands.

**Comment by sayedihashimi** [comment]
Sounds great to me adding @glennc to make sure we use the latest docker file.

**Comment by glennc** [comment]
Would you update this every time we release a new image? So this always drops you a Dockerfile for whatever the latest release of ASP.NET is?

**Comment by peterblazejewicz** [comment]
@glennc 
`Yes sir`, we do it and we track announcements forum https://github.com/aspnet/Announcements for *beta* releases (I'm not implying that Docker updates should be announced there though). If you git it a green light, we will just monitor relevant forum.

**Comment by spboyer** [comment]
@glennc we could just put an image on DockerHub with the tag `microsoft/aspnet:1.0.0-latest` instead of the `microsoft/aspnet:1.0.0-beta7` then the dockerfile would always get the the most recent image.  Of course I know that the local cache would prevent too.

**Comment by glennc** [comment]
@peterblazejewicz Sounds fine, just clarifying my understanding :).

@spboyer I think @ahmetalpbalkan had a Dockerfile like that for a while and didn't stay with it. Perhaps because it was too unstable?

**Comment by ahmetalpbalkan** [comment]
True. It was breaking a lot and unless someone pushes a button periodically there's no way to rebuild a docker image —it simply won't be a nighly.. If your Dockerfile here needs a nighly build, just install aspnet in your Dockerfile and set the feeds correctly and build the image with --no-cache argument.

**Comment by glennc** [comment]
Just realized I most likely misunderstood @spboyer. We could push twice with two different tags. Once for beta7 and once as latest. When we do beta8 we do the same thing so aspnet:latest is always the latest stable(ish) release.

I've seen people doing this but not tried it out myself. Seems like it would work well enough, though as he said caching is probably a minor inconvenience for some.

**Comment by peterblazejewicz** [comment]
> I've seen people doing this but not tried it out myself. Seems like it would work well enough, though as he said caching is probably a minor inconvenience for some.

@glennc 
We are to release it *as is* shortly - so you will get some feedback back (that's the plan here).  I'm sure you guys will cook the perfect solution.

**Comment by peterblazejewicz** [comment]
Google has nicely indexed project Dockerfile addition:
https://www.google.com/search?q=aspnet+docker+generator&oq=aspnet+docker+generator
