### ISSUE TITLE
TypeScript / Angular / etc. flavors?

### ISSUE THREAD

**Issue by cveld** [OmniSharp/generator-aspnet#365]
What is your current planning to eventually include all kinds of asp.net dnx flavors into the generator stack? For example to generate a TypeScript / Angular / dnx flavored project.
Should we be expecting some plumbing mechanism so that community contributions can be added?

**Comment by peterblazejewicz** [comment]
I'm keeping bumping topics for MS Tooling team:
https://github.com/aspnet/tooling
I think that general consent is to try keeping generator in sync with content provided by MS Visual Studio templates first - so people without VS can do the same stuff. But we try to push ideas to tooling team.
From what I watched on community standup  (https://live.asp.net/), especially by Damian Edwards comments about upcoming features to tooling, it seems that at some point some AngularJS + TypeScript will be shipped with VS, so they will certainly land here. I mean: full application/project templates. Note that one could find pieces of AngularJS and TypeScript in subgenerators already.
The community standup Hangout live stream is a good place to post questions directly to Damian Edwards, Scott Hanselman or Jon Gallowey and other folks involved in shaping ASP.NET5 features (and people do ask direct questions like your ones).
The main obstacle at the moment for more client-side content is that Tooling team has to figure out a clean way to work with dependencies (Bower) and tooling (Gulp task). At the moment it is still not yet clear how it will be promoted (we have discussion about this topic here and on tooling forum).

**Comment by peterblazejewicz** [comment]
> Question: Will there be some AngularJS integration by default in ASP.NET 5 default templates?
Not sure.... there was some initial investigation in the MusicStore / SPA example as an exploration of server-side generation of Angular templates.  The team plans to circle back and spend time on it, but it is not known if that will become a default.

http://blogs.msdn.com/b/webdev/archive/2015/09/22/asp-net-community-standup-september-15-2015.aspx
Let's keep pushing the questions :)

**Comment by sayedihashimi** [comment]
Thanks for the note.

I think we have two high level optoins here.

 - Update `yo aspnet` to have options to allow users to select options like typescript/angular
 - Create a new generator, for example `generator-aspnet-angular`

In the past when we've discussed the first option (adding options) the response from the community was that we should be more opinionated and it would be better to create separate generators for scenarios like this.

From the Microsoft perspective we have discussed this idea, but have no specific plans for this anytime soon. I wouldn't wait for the Microsoft team to put something together. I think there is more interest, and likely more expertise, in the community here. As a side benefit, if we are able to put together a good Angular template then we can work with the VS team to get the templates added to VS sooner.

For Angular, I think the best thing to do would be create a new generator `generator-aspnet-angular` and then publish that. If we can find community members interested in this, I can setup a repo here in the OmniSharp org and I can automate the publish process to npmjs.org.

Thoughts?

**Comment by peterblazejewicz** [comment]
There are excellent generators for Angular, including official:

**Comment by peterblazejewicz** [comment]
There is official Angular generator and community driven excellent one: https://github.com/yeoman/generator-angular
I think at some point there will be enough people to contribute solution that use ASP.NET 5 one (I could help with one)

**Comment by sayedihashimi** [comment]
@peterblazejewicz are you saying we should try and update generator-angular with an asp.net 5 option? Or are you saying whatever Angular template we create should be based on generator-angular?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I'm at work, so maybe I was not clear. I'd left this topic open to get ideas from community. If there is enough people interested (and no other related project emerges) I'd add one to OmniSharp umbrella organization. But only if there is enough people involved to make that new project real thing. That other existing generators for Angular are really best on the market - the only difference is that none of them follow ASP.NET 5 conventions about structure and underlying server and tools implementation (no Kestrel support, no build tools based on DNX).
Thanks!

**Comment by sayedihashimi** [comment]
@peterblazejewicz 
>But only if there is enough people involved to make that new project real thing

I think this is the critical part. It would be ideal to identify someone whose interested in owning this. We can help get them started and coordinate when changes are made.

Whose interested in owning `generator-aspnet-angular`, @peterblazejewicz and I (and others I'm sure) will be here to help.

cc @shanselman

**Comment by luisrudge** [comment]
IMO, generator-aspnet shouldn't have anything more than aspnet stuff. generator-angular, generator-react, generator-X will do a better job updating the generator to reflect best practices in each and every one of those technologies. There's nothing preventing someone to use generator-aspnet and generator-angular in the same app, so I don't see why generator-aspnet has to have all of that.

**Comment by peterblazejewicz** [comment]
@luisrudge Thanks!

**Comment by peterblazejewicz** [comment]
@cveld 
From today\s standup:
https://www.youtube.com/watch?v=wWfpAY4c3dg&feature=player_embedded#t=1785
Hope this answer the topic.
Thanks!
