### ISSUE TITLE
Make project README more consistent and focused

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#378]
I've made a PR related to sorting, clearing and ordering of some documentation sections (mostly subgenerators list sorting and subsections for subgenerators): #377 and no matter if it will be merged/accepted I think the project documentation README file should be now reviewed and rewritten to be more focused on generator itself. 
For example these parts could be moved from main README to WIKI section:
- parts of template project descriptions with past betas references:
https://github.com/OmniSharp/generator-aspnet/blob/master/README.md#template-projects
- parts placing generator in spectrum of other scaffolding tools and other, related (or not) projects:
https://github.com/OmniSharp/generator-aspnet/blob/master/README.md#related-yeoman-generators

Such changes could make a project documentation shorter, cleaner and better fitted for first-time users, bloggers, etc.

Thanks!

**Comment by sayedihashimi** [comment]
+1 thanks

**Comment by peterblazejewicz** [comment]
after 'beta8'
