### ISSUE TITLE
ASP.NET Beta8: Empty WebApp Template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#382]
Samples: http://1drv.ms/1PSX6FB

**Comment by peterblazejewicz** [comment]
me
Thanks!

**Comment by peterblazejewicz** [comment]
@rustd 
Not exactly sure here:
- the `hosting.ini` is removed
- the `project.json` does not contain command for non IIS-based container:
```
 "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
```
This won't work without VS I think.

**Comment by sayedihashimi** [comment]
The web command is using Kestrel so it should work xplat. Not sure where the port number went though.

**Comment by rustd** [comment]
Port number is 5000 by default in runtime. This should work without VS

**Comment by spboyer** [comment]
@rustd what if the port, is in use?  What happens in the scenario where I am needing to run multiple applications at once on a DEV machine and need to test?  can use the same port in that scenario.  This must be a configurable value.

**Comment by sayedihashimi** [comment]
I agree, for vs since IIS Express is used a random port is selected. We should have the port in a file somewhere

**Comment by peterblazejewicz** [comment]
@rustd 
I'm still not convinced, the `beta8` branch on @aspnet/home uses kestrel in `project.json`:
https://github.com/aspnet/Home/blob/glennc/beta8/samples/1.0.0-beta8/HelloWeb/project.json
cc @glennc

**Comment by peterblazejewicz** [comment]
That's important e.g. for Docker as one needs to pass cmd command:
https://github.com/aspnet/Home/blob/glennc/beta8/samples/1.0.0-beta8/HelloWeb/Dockerfile#L9

**Comment by peterblazejewicz** [comment]
Is there announcement for change in execution, number of parameters and default port number?
https://github.com/aspnet/Announcements/milestones/1.0.0-beta8
The aspnet/kestrel uses `kestrel` in `project.json` too :imp: 
https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/project.json#L21

**Comment by peterblazejewicz** [comment]
I think I can see that I've misread (a hard day's evening :splash:). I understand that:
```
web
```
command is new `kestrel`:
```
"web": "Microsoft.AspNet.Server.Kestrel"
```
But still we need some :+1:  from VS team before we proceed (as we have to update Dockerfile, hints in generators, etc), etc.
Thanks!

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/7ab107f170de0a566dbbed9ab610c9f99b9e3151
