### ISSUE TITLE
ASP.NET Beta8: WebApp template (No Auth)

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#384]
Samples: http://1drv.ms/1PSX6FB

**Comment by Spinarooni** [comment]
@peterblazejewicz @sayedihashimi I noticed that the renamed config.json, which is now appsettings.json, is empty.  Do we want that empty in the generator or is SiteTitle used somewhere?

	{
	  "AppSettings": {
	    "SiteTitle": "WebApplicationBasic"
	  }
	}

**Comment by rustd** [comment]
This file should be empty.
We removed SiteTitle from the templates and it is not being used anywhere.

**Comment by Spinarooni** [comment]
I also noticed a change to the project.json file with the `publishExcludes` property.

Beta 7:

	  "publishExclude": [
	    "node_modules",
	    "bower_components",
	    "**.xproj",
	    "**.user",
	    "**.vspscc"
	  ], 

Beta 8:

	  "publishExclude": [
	    "**.user",
	    "**.vspscc"
	  ],

Is this intentional?

**Comment by peterblazejewicz** [comment]
The change with `publishExclude` can be seen in all beta8 web templates I think

**Comment by Spinarooni** [comment]
I don't see why you'd want to include those in a publish though:
	
	"node_modules",
	"bower_components",
	"**.xproj",

**Comment by peterblazejewicz** [comment]
closed via: 
https://github.com/OmniSharp/generator-aspnet/commit/9d839256c6b19d07f6f2bb14fb1b7ebb576491ab
The content of configs will be discussed, the `beta8` is not yet in the wild
