### ISSUE TITLE
ASP.NET Beta8: WebApp template (Auth)

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#385]
Samples: http://1drv.ms/1PSX6FB

**Comment by peterblazejewicz** [comment]
Me!

**Comment by peterblazejewicz** [comment]
bwt: The EF migration files are named in example:
`inital`
instead of:
`initial`

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/2c2f992a6f2368f2a2c20980e6d368440ae569f3
