### ISSUE TITLE
ASP.NET Beta8: Update Dockerfile subgenerator

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#395]
The example from implementation aspnet/home is useful, though not yet merged. It shows obvious routes:
https://github.com/aspnet/Home/blob/glennc/beta8/samples/1.0.0-beta8/HelloWeb/Dockerfile

We use that subgenerator template in all other web projects.

**Comment by spboyer** [comment]
I am leaving the port at 5000, even though @glennc changed it to 5004 in the HelloWeb sample above.

**Comment by peterblazejewicz** [comment]
I assumed it will be yours :dancer: 
Sure thing with port

**Comment by peterblazejewicz** [comment]
> I am leaving the port at 5000, even though @glennc changed it to 5004 in the HelloWeb sample above.

ref for comment: https://github.com/OmniSharp/generator-aspnet/issues/382#issuecomment-146294466

**Comment by spboyer** [comment]
Also note that the templates for beta8 remove the `kestrel` command and now only have the `web` command _name_ .  2 Options here.  Either change either *change* the ENTRYPOINT command to `web` or on all of the templates add a _copy_ of the `web` command and give it a `kestrel` name so you can call either command from the command line to execute the project.  i.e.

```
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "kestrel": "Microsoft.AspNet.Server.Kestrel"
  },
```

I have just renamed the command in the PR for Docker. 

@sayedihashimi @glennc @pranav

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/9cf93b7825648dd476aa68be0ed8f76db57dc2c6
