### ISSUE TITLE
ASP.NET 8: Add `nuget.config` subgenerator [question]

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#398]
Can we add this? The reasoning behind this:
- add an option for people to use unstable, future branches > so #183 that could be closed
- whenever generator is to be updated `nuger.config` template file content would be tremendously useful (I find myself going to a post to copy template content)

The content of the file should be the same as used in current release, here for beta8:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="aspnetrelease" value="https://myget.org/f/aspnetbeta8/api/v2" />
  </packageSources>
</configuration>
```
It will be a subgenerator, so filename escaped to avoid scanning in project:
```
nuget_config
```
renamed to:
```
nuget.config
```
during generation

The CLI:
```
yo aspnet:nuget
```

Thoughs?

**Comment by sayedihashimi** [comment]
I think this is a good idea. I'm not sure about the exact content. How about having the following for default?

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    
    <!-- uncomment to use another feed for prerelease packages -->
    <!--
    <add key="aspnetrelease" value="https://myget.org/f/aspnetbeta8/api/v2" />
    -->
  </packageSources>
</configuration>
```

The idea is that when you use the subgenerator, you get the same feed as default when VS is used. We can also add aspnetrelease, and others, as comments. Thoughts?

**Comment by peterblazejewicz** [comment]
I'm not an expert, but I'll update #401 accordingly

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/f9aacc2a96cc0ab60ffbdc066f1e2e8b2f6757b1
