### ISSUE TITLE
Install Bower to bower_components folder then publish to wwwroot using Gulp

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#400]
Issue created to discuss topics from PR (https://github.com/OmniSharp/generator-aspnet/pull/268#issuecomment-146661131):
https://github.com/OmniSharp/generator-aspnet/pull/268

> I've made quite a lot of changes to do Bower properly (in WebSimple), and keep wwwroot as a build target instead of a source+public directory.
> I've only done it for Gulp so far, and I'm opening this PR to check whether people like before I spend the time doing it for the Grunt option too.
> So, good or bad?

**Comment by peterblazejewicz** [comment]
relevant thread on aspnet/tooling: https://github.com/aspnet/Tooling/issues/190

**Comment by sayedihashimi** [comment]
Let's see what @shanselman @damianedwards and @madskristensen think about this.

FYI @peterblazejewicz has prototyped the changes at https://github.com/peterblazejewicz/aspnet5-web-gulp-babel-ts/tree/master/src-es5 where he has some good comments of what he did.

**Comment by madskristensen** [comment]
I like the user of **gulp-main-bower-files**. Since people using the yo generators are probably more accustomed to Bower and Gulp I think it makes perfect sense

**Comment by peterblazejewicz** [comment]
recently I'm using `postrestore` as people are trapped in situation than NPM and Bower are never installed, `clean` and `min` are not invoked while people are trying to use `Development` environment - and get no client side dependencies. Most generators scaffold client side content after base content - hence `postrestore` seems to be perfect without VS as people have to call `dnu restore` at the start of the project.

**Comment by scottaddie** [comment]
I support the `postrestore` idea as well, for the same reason. I've been handling this issue the same way, as `prepublish` didn't seem like the optimal place to do `npm install` and `bower install`. I absolutely need my client-side dependencies, long before I think about doing a `dnu publish`.

**Comment by Spinarooni** [comment]
Grunt has a similar plugin for copying the main bower files from bower_components: [main-bower-files](https://www.npmjs.com/package/main-bower-files)

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
