### ISSUE TITLE
Should the '.dockerignore' be added to Dockerfile subgenerator?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#406]
For reference what it is:
https://docs.docker.com/reference/builder/

@spboyer 
Shayne, the MS examples do not use it, but I assume we could follow best practises. We do not need to copy all the stuff to container? This is not so useful at the current implementation as Bower deps get installed into `wwwroot`, so only `node_modules` and other stuff could be referenced, but maybe in near feature?
:question: 
Thanks!

**Comment by spboyer** [comment]
Let's put it aside at the moment.

**Comment by moander** [comment]
Reopen?

**Comment by peterblazejewicz** [comment]
@moander Go ahead and create new one. Current implementation copy all content:
```
COPY . /app
```
