### ISSUE TITLE
Use explicit packages version numbers in console application package.json

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#408]
> we should specify the version numbers when we hear back from @rustd on the values.

https://github.com/OmniSharp/generator-aspnet/commit/5b8021db065a6aa28d1a44b2fb3e6b2cb3a89ed9

**Comment by sayedihashimi** [comment]
@rustd do you know the final version numbers for console app? 

We are blocked from releasing until we get this updated.

**Comment by rustd** [comment]
"dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23409",
        "System.Collections": "4.0.11-beta-23409",
        "System.Console": "4.0.0-beta-23409",
        "System.Linq": "4.0.1-beta-23409",
        "System.Threading": "4.0.11-beta-23409"
}

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
#419

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/140849df8f7a9f8c6f382a190d73a79c7cc18842
