### ISSUE TITLE
Add GulpFile subgenerator

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#41]
I think that people will start using GulpJS with vNext project very soon, though VS tools appears to officially support GruntJS at the moment.
I'm referring also to this article:
https://www.tattoocoder.com/gulp-typescript-in-asp-net-5/

The contents of template file could be similar to the GruntJS' file template:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/gruntfile.js

for example:
```JavaScript
/*
This file is the main entry point for defining Gulp tasks and using Gulp plugins
To learn more visit: https://github.com/gulpjs/gulp/blob/master/docs/README.md
*/
'use strict';

var gulp = require('gulp');

// The default task (called when you run `gulp` from CLI)
gulp.task('default', function() {
  console.log('Running default Gulp task: replace with your own code!!!');
});


```

/cc @spboyer

**Comment by spboyer** [comment]
+1 assign to me

**Comment by sayedihashimi** [comment]
+1
Adding @rustd and @madskristensen in case they have comments regarding the contents of the gulp template.

**Comment by spboyer** [comment]
Added
