### ISSUE TITLE
Visual Studio templates now open source

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#417]
In case you haven't already heard the source for Visual Studio templates are now on github, see the announcement https://github.com/aspnet/Announcements/issues/79.

If you notice any issues in VS templates please file issues in that repo.

This is just an FYI.

**Comment by sayedihashimi** [comment]
I'll leave this open for a few days so that everyone can see this, and then close it out later.

**Comment by peterblazejewicz** [comment]
This could be closed after `rc1` and this PR: https://github.com/OmniSharp/generator-aspnet/pull/484

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/19db1bbf0d895cecd99d282a045bc47c35f51234
