### ISSUE TITLE
a beta8 `web.config` seems to be included in templates only because of VS tooling

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#424]
from: https://github.com/OmniSharp/generator-aspnet/issues/386#issuecomment-148505019

> You’ll notice that the ASP.NET 5 project templates in Visual Studio have been updated to include the following web.config file ....

http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx

Inclusion of this file by default adds noise for users I think. There is no web.config both in aspnet/samples:
https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta8
and in docs.asp.net:
https://docs.asp.net/en/latest/search.html?q=web.config&check_keywords=yes&area=default

@sayedihashimi 
We could support  points you've raised of providing better hosting support in two different ways:
- add `web.config` as part of project structure creation #418
- add 'WebConfig subgenerator (with better USAGE description on why that file is added)

**Comment by Benjiiim** [comment]
If you let me do so, I +1 this! :-)

And the web.config is not the only part that should not be included to my mind. This is true for
- The Microsoft.AspNet.IISPlatformHandler dependency in project.json
- The UseIISPlatformHandler in the pipeline configuration

And for other reasons, these files should not be included as well by defaut to my mind:
- The docker file
- The readme file

I do think that the Empty Template should be empty, with only the minimum required for a Hello World with kestrel.
Having an other template, an option on existing templates or something else to tell that we want to generate the artifacts needed to be hosted on Docker or to use IIS would be great.

My 2 cents...

**Comment by sayedihashimi** [comment]
I'm fine removing items as long as the project still works when opened in Visual Studio. I think VS should handle cases when the hosting files/entries are removed but someone should double check before merging.

**Comment by peterblazejewicz** [comment]
marked for review with RC1

**Comment by peterblazejewicz** [comment]
I won't be able to do this. It requires Windows OS + VS (I can't do this at work)

**Comment by peterblazejewicz** [comment]
Let's not touch this for RC1

**Comment by Spinarooni** [comment]
@peterblazejewicz I tested this on my Win 7 machine with VS 2015 Enterprise.  I removed the web.config and when I tried to run it under IIS Express it recreated the web.config file.

**Comment by peterblazejewicz** [comment]
@Spinarooni Thanks!
/cc
@sayedihashimi

**Comment by peterblazejewicz** [comment]
The role of `web.config` has been changed for RC2 and this thread seems to be no longer relevant in the context of RC2/dotnet. `web.config` is now part of configuration options in `project.json`. See also:
https://github.com/aspnet/Announcements/issues/173
https://github.com/aspnet/Templates/pull/497 (discussion, changes)
closing and marking as part of RC2
Thanks!
