### ISSUE TITLE
Config subgenerator needs to be updated to create an appsettings.json file?

### ISSUE THREAD

**Issue by Spinarooni** [OmniSharp/generator-aspnet#426]
In Beta 8 the config.json file was renamed to appsettings.json.  Is the config.json file used elsewhere?

**Comment by peterblazejewicz** [comment]
I'd wait and see. People are accustomed to `config.json` and the official docs still use `config.json`:
https://docs.asp.net/en/latest/fundamentals/configuration.html
One could find it in official MS source code on github/aspnet. The source code is even more verbose:
https://github.com/aspnet/Configuration/blob/ff1dc034ef9e376b684194ce4193af7049d98542/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationFileParser.cs#L27
The change was not announced, but is probably to stay. I'd left it until it is replaced in official docs.

**Comment by scottaddie** [comment]
FYI, the `config.json` default file name used in the Beta 8 tooling's item template for VS has been renamed to `appsettings.json` for RC1. It was indeed a defect. See [this issue](https://github.com/aspnet/Templates/issues/261) in the Templates repo.

**Comment by peterblazejewicz** [comment]
@scottaddie Thanks for the reference.
Even more obvious why we should left it as is, till rc-1 I think.
