### ISSUE TITLE
Add alias "JavaScript" for JavaScript generator 

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#43]
I think generator should follow its own conventions (`CoffeeScript`) - so maybe there should be `aspnet:JavaScript` subgenerator that can be used as:
```sh
yo aspnet:JavaScript app
```
At the moment there is a `JScript` subgenerator - with a name that could not exactly correctly explain what kind of script is to be created in my opinion: http://en.wikipedia.org/wiki/JScript (the link is just for reference)

Aliases to subgenerators can be created by adding new subgenerator with correct (expected) name which uses existing subgenerator as module.
The problem is common, for example there was similar issue on Polymer generator I'm using where not trully fortunate name `el` was picked as name for subgenerator that creates `element` causing confusions:
https://github.com/yeoman/generator-polymer/issues/87
https://github.com/yeoman/generator-polymer/commit/b0d5102a228e4ec158e2b708e07b003c14d9dd31

**Comment by spboyer** [comment]
I agree, I'll add this in my next PR. Adding a Typescript template as well

**Comment by sayedihashimi** [comment]
+1

**Comment by spboyer** [comment]
Added.
