### ISSUE TITLE
README.md links do not work

### ISSUE THREAD

**Issue by ttilberg** [OmniSharp/generator-aspnet#435]
There are a bunch of links throughout the various README.md files that reference urls like: 

* [The 'wwwroot' explained](http://go.microsoft.com/fwlink/?LinkId=518008)
* [Configuration in ASP.NET 5](http://go.microsoft.com/fwlink/?LinkId=518012)
* [Add Controllers and Views](http://go.microsoft.com/fwlink/?LinkID=398600)
- etc

A search to get oriented and see all the files this affects:

https://github.com/OmniSharp/generator-aspnet/search?utf8=✓&q=http%3A%2F%2Fgo.microsoft.com%2Ffwlink

None of these links work -- they just end up at the MS home page telling me to buy a Surface Pro.

**Comment by ttilberg** [comment]
My mistake, it appears to actually be an issue with how VS Code is sending the links to my browser (Safari). These links appear to work great when not ctrl+clicking from vscode. Sorry, closing.

**Comment by sayedihashimi** [comment]
@ttilberg so what's the issue with VS Code?

cc @chrisdias

**Comment by peterblazejewicz** [comment]
@ttilberg 
report here: https://code.visualstudio.com/Issues/List

**Comment by ttilberg** [comment]
I wasn't able to figure it out from my Mac last night, but I was able to reproduce and debug better in Windows. The problem ended up being:
The link `http://go.microsoft.com/fwlink/?LinkId=518008`
when ctrl+clicked from VS Code gets URL encoded:
`http://go.microsoft.com/fwlink/?LinkId%3D518008`

It appears that microsoft.com no longer correctly interprets that parameter and sends me home:

```
GET http://go.microsoft.com/fwlink/?LinkId%3D518008 HTTP/1.1
---
HTTP/1.1 302 Moved Temporarily
Location: http://www.microsoft.com

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="http://www.microsoft.com">here</a>.</h2>
</body></html>
```


I'll submit this to the VS Code tracker as suggested, but left it here for completion's sake.

**Comment by peterblazejewicz** [comment]
@ttilberg Thanks!
