### ISSUE TITLE
Add `CONTRIBUTING.md` to repo [wasn't there one?]

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#438]
There should be `CONTRIBUTING.md` file within root directory (the lettercase does not matter) - a built-in GitHub.com solution will show a link to that file when starting a topic/issues or PR to repository. 
The content can contain the same information as on WIKI: https://github.com/OmniSharp/generator-aspnet/wiki/How-to-Contribute
But I think we should take the same explicit expectations to commit message content as explained in aspnet/home or aspnet/Templates:
https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md
We should not enforce this via tools like [commitizen](https://www.npmjs.com/package/commitizen) but we at least should expect people to write about commits
@sayedihashimi 
You've authored a WIKI recently, what's your stance on this?
Thanks!

**Comment by sayedihashimi** [comment]
+1 I'm all for make it clear what the expectations for contributions

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
That's merged in https://github.com/OmniSharp/generator-aspnet/commit/49384f5addd9e95e1d7c854380de3a238dd25588
Shayne was reviewer
Thanks!
