### ISSUE TITLE
Unnecessary binaries in web sample

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#44]
I think web sample project:
https://github.com/OmniSharp/generator-aspnet/tree/master/samples/web
contains unnecessary build artefacts. They are usually excluded from C#/VisualStudio projects Git managed projects:
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore#L19
The other samples do not have build artefacts right now.

Is it OK for you guys to remove it?

as side note: the project's `.gitignore` could be also updated (via separated issue)

**Comment by spboyer** [comment]
bin folder has been removed from samples folder. in latest PR - https://github.com/OmniSharp/generator-aspnet/pull/59
