### ISSUE TITLE
How to install nuget package?

### ISSUE THREAD

**Issue by zhouhao27** [OmniSharp/generator-aspnet#445]
I'm new to dotnet development under OS X. I'm wondering how to add new nuget package in yo aspnet project? Thanks.

**Comment by scottaddie** [comment]
Take a look at the docs [here](https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html). I suspect that will answer many of your questions. In short, here's what you'd need to do:

1. Scaffold a new app using this Yeoman generator
2. Add a key-value pair for each NuGet package you'd like to use to the `dependencies` section of the `project.json` file in your project
3. Open a command shell and run `dnu restore` to install the packages listed in `project.json`

You can install a NuGet.config file with this generator, but it doesn't sound like that's what you're trying to accomplish.

**Comment by Spinarooni** [comment]
I'm on Linux Mint and am able to run the Nuget.exe using mono from the command line.  You'll need to download the exe from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe.  You'll also need to have Mono 3.2 or later installed.

**Comment by bagusflyer** [comment]
Thanks @scottaddie, I read the doc already. Actually I have no problem to run asp.net in my mac. But I don't know how to install NuGet package. For example, I want to use Swashbuckle (https://github.com/domaindrivendev/Swashbuckle). I have no idea how to add the dependency to project.son file.

**Comment by scottaddie** [comment]
Try manually adding the following anywhere within the `dependencies` section of `project.json`:

"Swashbuckle": "5.2.2"

These key-value pairs are nothing more than the official NuGet package name and a version number. After doing so, a `dnu restore` should install the package for you.

**Comment by peterblazejewicz** [comment]
> I'm wondering how to add new nuget package in yo aspnet project? Thanks.

1) use DNU 
The `dnu install` works just like `npm install`:
```
dnu install {package-name}
```
```
dnu install --help


Usage: dnu install [arguments] [options]

Arguments:
  [name]     Name of the dependency to add
  [version]  Version of the dependency to add, default is the latest version.
  [project]  Path to project, default is current directory

Options:
  -s|--source <FEED>          A list of packages sources to use for this command
  -f|--fallbacksource <FEED>  A list of packages sources to use as a fallback
  -p|--proxy <ADDRESS>        The HTTP proxy to use when retrieving packages
  --no-cache                  Do not use local cache
  --packages                  Path to restore packages
  --ignore-failed-sources     Ignore failed remote sources if there are local packages meeting version requirements
  --quiet                     Do not show output such as HTTP request/cache information
  --parallel                  Restores in parallel when more than one project.json is discovered.
  -?|-h|--help                Show help information
```
`dnu install` will both create record in dependencies section and install (restore) package

2) use IDEs

Both Atom editor with [OmniSharp Atom plugin](https://github.com/OmniSharp/omnisharp-atom) and [Visual Studio Code](https://code.visualstudio.com/) supports package dependencies installation, just open quote and start typing package name:
![image](https://cloud.githubusercontent.com/assets/14539/10799856/532e98ae-7daf-11e5-8a0e-959c6cb93d0e.png)
