### ISSUE TITLE
Update index.js to pull from release branch instead of master

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#45]
Currently [```index.js```](https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js) pulls the latest from the ```master``` branch.

I think we should change to this point to the ```release``` branch instead so that changes are only picked up when we make a release.

Once we implement #26 this will be a moot point, but I think that may take some time.

I'm planning to switch index.js to point to release likely later today. If you have any concerns please reply here. We can always revert if needed.

**Comment by peterblazejewicz** [comment]
LGTM
