### ISSUE TITLE
Change dockerfile

### ISSUE THREAD

**Issue by glennc** [OmniSharp/generator-aspnet#453]
I'd like to change the dockerfile being generated to not copy project.json, then restore, then copy the project.

The problem with this approach is that if you have run your app locally you will overwrite the lock.json with one from your local machine. This wasn't a problem back when we started creating samples, but it is an issue now.

With recent changes to some packages you will get a different Package graph on Linux vs other OSs. A package with a Linux specific implementation assembly for example. I think we should just copy the whole app and then run restore.

I am on my phone now, but can do a pr later if we agree on the plan.

**Comment by spboyer** [comment]
Thanks @glennc - pushed the changes.

**Comment by peterblazejewicz** [comment]
@glennc Thanks!
