### ISSUE TITLE
Links incorrect in generated README.md

### ISSUE THREAD

**Issue by allyjweir** [OmniSharp/generator-aspnet#459]
Just initialised a project (Web Application) using the generator and the links in 'CUSTOMIZE APP' were incorrect. For example, the 'Add Web APIs with MVC6' points to a non-existant URL`http://docs.asp.net/en/latest/mvc/index.html` whereas the current URL is `https://docs.asp.net/projects/mvc/en/latest/`.

A small fix to go through and correct them. I didn't do them myself as they were url-shortened using `go.microsoft.com` and I don't believe that is a public service.

Just something to help the beginners in the world!

**Comment by peterblazejewicz** [comment]
@allyjweir 
Thanks!
That's external content we have converted to *readme* format. I've created a ticket on related project:
https://github.com/aspnet/Templates/issues/312

**Comment by peterblazejewicz** [comment]
@allyjweir 
Fixed in upstream repo. They fixed shortened link
Thanks!
https://github.com/aspnet/Templates/issues/312#issuecomment-155972892
