### ISSUE TITLE
ASP.NET 5 RC1 Class Library update

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#462]
Samples:
http://1drv.ms/1QiuMQs

Feed:
https://www.myget.org/F/aspnetrc1

**Comment by peterblazejewicz** [comment]
Let me try

**Comment by peterblazejewicz** [comment]
closed via:
https://github.com/OmniSharp/generator-aspnet/commit/8b2f8c61ae576be2be158f9688dedd66113d4208
