### ISSUE TITLE
ASP.NET 5 RC1 Console App template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#463]
Samples:
http://1drv.ms/1QiuMQs

Feed:
https://www.myget.org/F/aspnetrc1

**Comment by peterblazejewicz** [comment]
Me, thanks!

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/e8050e9e44540931412852c26a9b2f82cbf0efcd
