### ISSUE TITLE
ASP.NET 5 RC1 Empty Web App template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#464]
Samples:
http://1drv.ms/1QiuMQs

Feed:
https://www.myget.org/F/aspnetrc1

**Comment by peterblazejewicz** [comment]
Me, thanks!

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/a94b019d9ffeb2f7332d6fc29cd01a69c4ae5b2b
