### ISSUE TITLE
ASP.NET 5 RC1 Web App with Authentication template

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#467]
Samples:
http://1drv.ms/1QiuMQs

Feed:
https://www.myget.org/F/aspnetrc1

**Comment by peterblazejewicz** [comment]
me!

**Comment by peterblazejewicz** [comment]
@rustd 
Is there "foo.txt" generated by new tools somehow? It contains output from build process like:
```
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16137


Building WebAppMembership for DNX,Version=v4.5.1
  Using Project dependency WebAppMembership 1.0.0
    Source: C:\temp\yorc1\WebAppMembership\project.json

  Using Package dependency EntityFramework.Commands 7.0.0-rc1-16297
    Source: C:\Users\pranavra\.dnx\packages\EntityFramework.Commands\7.0.0-rc1-16297
    File: lib\dnx451\EntityFramework.Commands.dll
...
```

**Comment by rustd** [comment]
foo.txt is not needed. Please delete it.

**Comment by peterblazejewicz** [comment]
@rustd 
Some content is not aligned with current aspnet/Templates content, for example content of `_Layout.cshtml` is somehow off-bit:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Views/Shared/_Layout.cshtml
I'll update according to aspnet/Templates

**Comment by peterblazejewicz** [comment]
The same off-bit for:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Views/_ViewImports.cshtml
