### ISSUE TITLE
Might be worth binding kestrel to all interfaces

### ISSUE THREAD

**Issue by atrauzzi** [OmniSharp/generator-aspnet#472]
I've just been working with the Docker-ized aspect of the ASP.NET project scaffolds and ran into issues with kestrel not binding correctly to the network interface inside the container.

I ended up having to do this to my `project.json`:

```
"commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://*:8080/",
```

(in my specific scenario, I wanted kestrel listening on 8080, but it's the `*` that's of interest here)

See more here: https://github.com/aspnet/aspnet-docker/issues/106

**Comment by spboyer** [comment]
@atrauzzi yes you need to expose the entry point of the application.  By default the port is 5000, so setting the `--server.urls http://*:5000` would be required for Docker.  Otherwise you get a ERR CONN REFUSED

**Comment by peterblazejewicz** [comment]
:bookmark: 
> Otherwise you get a ERR CONN REFUSED

As explained in @spboyer blog post:
http://tattoocoder.azurewebsites.net/asp-net-5-continuous-integration-with-travis-ci-tutum-docker-webhooks-and-azure/

I think the example should be as close as possible with latest docs:
https://docs.asp.net/en/latest/getting-started/installing-on-linux.html#create-a-container

**Comment by atrauzzi** [comment]
Yes, exposing the entry point is obvious.  What wasn't obvious was that kestrel bound to the wrong interface and so the runtime inside was inaccessible, despite the exposed port.

My suggestion here is to make the modification above to ensure the runtime inside the container actually is visible when the ports end up getting forwarded.

**Comment by sayedihashimi** [comment]
@glennc since we get the dockerfile content from you where is the correct place to have discussions about potential changes?

**Comment by peterblazejewicz** [comment]
Side note: people reading ASP.NET 5 docs, for example that section:
[Installing ASP.NET 5 On Linux](https://docs.asp.net/en/latest/getting-started/installing-on-linux.html?highlight=docker)
will most use Docker in a way described in the same docs:
[Install Docker/Create a container](https://docs.asp.net/en/latest/getting-started/installing-on-linux.html?highlight=docker#create-a-container)
and most likely will use `generator-aspnet`.
That's why we have been using `Dockerfile` `as is` in initial versions. I think we should stick with that 
(so the correct repo should be [aspnet/aspnet-docker](https://github.com/aspnet/aspnet-docker)

**Comment by atrauzzi** [comment]
Does that mean the docker configuration that this scaffold ships with will always be broken out of the box?

Because currently, there's simply no point to it.  Kestrel in the container is completely inaccessible until you make the change above to `project.json` which I'm sure countless people will get bit by.

**Comment by glennc** [comment]
Yeah, this was a recent change that @halter73 made to kestrel. It was a bug that Kestrel used to bind to more than just localhost when localhost was specified. However, the side effect of the change is that there is a lot of content out there that is setting people up to get this error and we haven't changed all of it yet.

So yes, I would change the Dockerfile created by the generator to bind on more than localhost. I am good with changing it to `*`. We can't scaffold an explicit IP so `*` is your only real option AFAIK.

**Comment by glennc** [comment]
Coming back to this I think we should add an environment variable for server.urls to bind to * in our Dockerfile. Otherwise nobody is going to work this out. If you specify it in project.json it will overwride the one in the file because it is a command line arg, otherwise you get *. Thoughts?

**Comment by peterblazejewicz** [comment]
@glennc 

> Coming back to this I think we should add an environment variable for server.urls to bind to * in our Dockerfile.

Do you mean at `aspnet/aspnet-docker` or in this project?

/cc @spboyer

**Comment by friism** [comment]
It looks like this change got it in and that this issue can be closed: https://github.com/OmniSharp/generator-aspnet/commit/c96874b887196007884cb5bdbc6d94b4fb48c769

**Comment by peterblazejewicz** [comment]
@friism 
Yes, thanks for heads-up! :bow:
