### ISSUE TITLE
ASP.NET 5 RC1 Update Dockerfile.

### ISSUE THREAD

**Issue by Spinarooni** [OmniSharp/generator-aspnet#473]
There were changes to the Dockerfile in RC1.

**Comment by peterblazejewicz** [comment]
@Spinarooni 
Reference please
Like this one? https://github.com/aspnet/Home/blob/glennc/rc1/samples/1.0.0-rc1/HelloWeb/Dockerfile
/cc @spboyer

**Comment by Spinarooni** [comment]
@peterblazejewicz Was basing the changes on the sample files from https://github.com/OmniSharp/generator-aspnet/issues/466

**Comment by peterblazejewicz** [comment]
My copy of RC1 files contains:
```
FROM microsoft/aspnet:1.0.0-beta8
``
That's not current one, but still topic is valid and I think Shayne has best experience

**Comment by spboyer** [comment]
There will be more than likely 2 base images in the Docker Hub to pull 
`microsoft/aspnet:1.0.0-rc1` and `microsoft/aspnet:1.0.0-rc1-coreclr` you can see the existing tags here: https://hub.docker.com/r/microsoft/aspnet/

**Comment by peterblazejewicz** [comment]
The upcoming images are on @glennc repo:
https://github.com/glennc/aspnet-docker
https://github.com/glennc/aspnet-docker/commit/06231091a12b3e6b356061c44ccc2ba60658b833

**Comment by peterblazejewicz** [comment]
The `latest` will be `mono` based:
https://github.com/glennc/aspnet-docker/commit/06231091a12b3e6b356061c44ccc2ba60658b833

**Comment by sayedihashimi** [comment]
@glennc what's the final dockerfile for `rc1`?

**Comment by glennc** [comment]
the on linked to is probably fine: https://github.com/aspnet/Home/blob/glennc/rc1/samples/1.0.0-rc1/HelloWeb/Dockerfile

Thought didn't @spboyer already merge a PR that changed it to be this?

**Comment by Spinarooni** [comment]
PR added.

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/04945281534d80b9e4627dbe02fcd947093bdee9
