### ISSUE TITLE
Add minimized version of site.js and site.css to projects

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#483]
The new templates are using minized version of JS anc CSS files, so we should review content and add these files to all related web projects:
For example:
https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/CommonAuth/Views/Shared/_Layout.cshtml

**Comment by Spinarooni** [comment]
Don't those get generated when gulp / grunt (?) min task are run?  If so, would we need them in the templates if that is the case?  I guess this gets back to needing to run gulp / grunt tasks after a build?

**Comment by peterblazejewicz** [comment]
As far as I know there is no agreed yet way to generate client-side deps when scaffolding ASP.NET 5 content. The project file still ships with `prepublish` event, which is really never called when scaffolding and or when restoring packages:
https://github.com/OmniSharp/generator-aspnet/blob/rc1/templates/projects/webbasic/project.json#L47
The thing is that they shipped `min.js`/`min.css` in new markup, so the expected files should be added I think to project contents.

**Comment by sayedihashimi** [comment]
We used to restore client pkgs on build but it slowed everything down. Instead the templates should be ready to go from file new and then pkgs are restored before any publish operation.

**Comment by peterblazejewicz** [comment]
> Instead the templates should be ready to go from file new and then pkgs are restored before any publish operation.

And the `site.min.css` and `site.min.js` are the only required pre-built content for templates to be run succesfully I think for Production/Staging env (unless there is a fallback because of CDN not available).

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/93ef88adbae11633e7b50913fbd91de02bedbbee
