### ISSUE TITLE
ASP.NET 5 RC1 Web App template with Authentication

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#486]
We made a change in the ASP.NET templates to not throw when you run the migrations in production.
Following is the change
https://github.com/aspnet/Templates/commit/96ed54d8a181a500ce357e1db764d6d6ea3a4992
We need to make this to the generator as well.
@peterblazejewicz FYI

**Comment by peterblazejewicz** [comment]
covered by: https://github.com/OmniSharp/generator-aspnet/pull/490

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/1f65f9777245dc29539dfafd2e1fbbfe777905ed
