### ISSUE TITLE
ASP.NET 5 RC1 final package versions

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#487]
This bug is tracking the final versions of the packages.
- ASP.NET 5 packages: 1.0.0-rc1-final
- DNX Class Project:
```html
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
```
- DNX Console Project:
```html
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
```

**Comment by rustd** [comment]
@peterblazejewicz I have updated the final package version above. Please make this change for RC1

**Comment by rustd** [comment]
@peterblazejewicz I added my notes to the PR. In the Empty, Web API, Web App Basic, Web App with Authentication. please update all package versions to be rc1-final.

**Comment by peterblazejewicz** [comment]
closed via: https://github.com/OmniSharp/generator-aspnet/commit/90e051c82ed7c056cd240e25e4e74e329b4ba060
