### ISSUE TITLE
Option for adding Controller or View 

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#49]
When generating a controller or view should there be an option for creating the other?

i.e. 

`yo aspnet:MvcController MyController -v`

generates
MyController.cs & MyController.cshtml 

also/or perhaps adding the additional option for names or conventions?

`yo aspnet:Mvc -c MyController -v MyView`

generates
MyController.cs & MyView.cshtml

**Comment by spboyer** [comment]
or does this get close to scaffolding i.e. - http://blogs.msdn.com/b/webdev/archive/2014/08/21/command-line-scaffolding-for-asp-net-vnext.aspx, is this a path to go down? or another generator?

**Comment by peterblazejewicz** [comment]
:+1: to the idea

My proposition:
```
yo aspnet:MvcGenerate Person
```
or:
```
yo aspnet:MvcScaffold Person
```
to get `Controllers/PersonController.cs`, `/Views/Person/Index.cshtml` (+CRUD), `Model/Person.cs`?

**Comment by sayedihashimi** [comment]
Command line scaffolding may not happen in an official manner. If people are supportive of this idea then so am I.

**Comment by firewater** [comment]
This would be a very useful feature. I am following [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model) except I'm using Visual Studio Code. In that tutorial, under the "Scaffolding a controller" section, it would be awesome if generator-aspnet could replicate those steps and end up with the controller, views, and CRUD as @peterblazejewicz suggested too. Keep up the good work, guys!

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
