### ISSUE TITLE
Update Unit Test template to use xUnit.net RC1

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#497]
xUnit.net released RC1 which works with ASP.NET 5 RC1 and .NET Core RC1
https://xunit.github.io/release-notes/2015-11-18.html
Please update the Unit test template in the generator-aspnet to this version of xunit

**Comment by rustd** [comment]
@peterblazejewicz FYI

**Comment by peterblazejewicz** [comment]
Thanks!

**Comment by peterblazejewicz** [comment]
@rustd Done PR - thanks!
