### ISSUE TITLE
Option to generate ViewComponent files

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#50]
I've managed to create and run vNext MVC ViewComponent - which is new and in my opinion undocumented fully upcoming feature:

https://gist.github.com/peterblazejewicz/b5915283a5ff23d468a6
http://www.asp.net/vnext/overview/aspnet-vnext/vc#intro

As there is not much documentation yet I'm not perfectly sure what is the best approach to write ViewComponents - but having simple example would be tremendous help. For example one that just uses view component class + view with static content, with no dependency injection, but with some insight from components authors in the boilerplate comment.

As far as I understand using ViewComponent requires a minimum two files:

```
/Components/MyComponent.cs
```

```
/Views/Shared/Components/MyComponent/Default.cshtml
```

We could generate them with:

```
yo aspnet:MvcViewComponent MyComponent
```

I could be wrong - but I think ViewComponent scaffolding is not yet covered in other tools as well.

**Comment by larsw** [comment]
https://github.com/OmniSharp/generator-aspnet/pull/71 partially solves this.

**Comment by spboyer** [comment]
@peterblazejewicz @larsw in order to solve the issue, it would have to also add the view correct? And the other item/restriction I would be concerned about is there is a constraint around the component having to be named "Components" - *"This folder must be named Components."*

**Comment by peterblazejewicz** [comment]
@spboyer 
I'm not exactly sure what are current constraints:
http://www.asp.net/vnext/overview/aspnet-vnext/vc#addv
Yes, we could scaffold entire component (class + view), so we should pick current implementation . As far as I understand we could place `ViewComponents` anywhere in generated project structure - but from this point we should follow conventions outlined in that article (unless there is newer one ofc).
They added a note about where to place `View`:
> Note: View Component views are more typically added to the Views\Shared folder, because VCs are typically not controller specific.

I could be wrong previously - at the time of adding issue, where `ViewComponent` class should be located and what is convention for folder and classes names.
Thanks!

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
