### ISSUE TITLE
EF 7 and SQLite - compiler error CS1061

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#503]
Error.

`EntityFrameworkServicesBuilder' does not contain a definition for 'AddSqlite' and no extension method 'AddSqlite' accepting a first argument of type 'EntityFrameworkServicesBuilder' could be found.`

![screen shot 2015-11-18 at 5 45 29 pm](https://cloud.githubusercontent.com/assets/7681382/11256886/7b4ed54c-8e1c-11e5-82c4-5513ce07545e.png)

**Comment by peterblazejewicz** [comment]
x-ref: https://github.com/aspnet/EntityFramework/issues/3779
