### ISSUE TITLE
Web Application doesn't work on ASP.NET RC 1 on OS X

### ISSUE THREAD

**Issue by jamescrowley** [OmniSharp/generator-aspnet#509]
Creating an empty web application works fine, but selecting the 'Web application' option doesn't generate a working project (on OS X at least). I get this instead when building:

    Unable to resolve dependency fx/mscorlib 
    Unable to resolve dependency fx/System 
    Unable to resolve dependency fx/System.Core 
    Unable to resolve dependency fx/Microsoft.CSharp (and so on)

Not yet experienced enough in vNext to know the cause. Thanks

**Comment by peterblazejewicz** [comment]
Do you use CoreCLR or Mono version of runtime? (`dnu --version` or `dnvm list`)
Thanks!

**Comment by peterblazejewicz** [comment]
I've created an issue on aspnet/home repo to investigate this: 
https://github.com/aspnet/Home/issues/1104
Thanks!

**Comment by peterblazejewicz** [comment]
The projects still require Mono runtime on OS X/Linux (all *nix/Darwin):

> For this particular case you need mono in order to build the 451 target
https://github.com/aspnet/Home/issues/1104#issuecomment-158539863

Thanks!

**Comment by jamescrowley** [comment]
I'm using CoreCLR. For some reason in the 'Empty' project, the dnx451 target is there too, but successfully builds

For those of you that come to this later... the solution that worked get it building on CoreCLR was to remove dnx451 from the list of frameworks in project.json.

**Comment by dmccaffery** [comment]
This is actually caused by a few factors:

When you call "dnu build" without specifying a target framework, it will attempt to build ALL targets specified in the project.json file.

For instance:

dnxcore50
dnx451

If you are currently using "dnu" from a CoreCLR version of the runtime, it will fail to build the dnx451 target framework as it is unable to resolve framework dependencies. The correct solution, for the time being is to do one of the following:

1) Build the dnxcore50 target (only) using the CoreCLR:

``` bash
dnvm use default -r coreclr && dnu build --framework dnxcore50
```

2) Build both targets using the CLR (or Mono):

``` bash
dnvm use default -r mono && dnu build
```

**Comment by dmccaffery** [comment]
I should note, that this only applies if you want your app to be able to run on both targets. If you are sure you will only ever use the CoreCLR, you can always remove the dnx451 target.

**Comment by peterblazejewicz** [comment]
@dmccaffery 
Thanks!

> dnvm use default -r coreclr && dnu build --framework dnxcore50

It does work very well

**Comment by rtaborda** [comment]
This problem also seems to happen if you target dnx46, even if it's the only target you have and if you're using mono. (I'm trying to build the app in Ubuntu using Mono 4.2.1.102 and runtime 1.0.0-rc1-final)
Any ideas why this happens? Or workaround?
