### ISSUE TITLE
Using containers for development

### ISSUE THREAD

**Issue by atrauzzi** [OmniSharp/generator-aspnet#513]
Hopefully I'm not breaking the intended use of this repo, I have a ticket over at the aspnet-docker repository that might be of interest: https://github.com/aspnet/aspnet-docker/issues/101

It was mentioned that the functionality I'm suggesting might be better handled by the @omnisharp team, and I noticed that you guys are planning on meeting up to discuss new ideas: https://github.com/OmniSharp/OmniSharp/issues/1

Overall, my suggestion is that it would be nice if there was some tooling in omnisharp and/or configuration made to containers to allow them to be used as development servers.

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
