### ISSUE TITLE
Missing _references.js file

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#514]
The Visual Studio "StarterWeb" template includes a `_references.js` file within the webroot folder to support JavaScript intellisense. Is there any interest in carrying this file over to this generator?

**Comment by peterblazejewicz** [comment]
They were not included as being purely VS-thing for IntelliSense support:
[JavaScript IntelliSense](https://msdn.microsoft.com/en-us/library/bb385682.aspx)
and there was no aspnet/Templates yet.
Now they are still primary VS JavaScript tooling support addition I think, as the other tools, including VS Code use different solutions:
[Say goodbye to ///-references](http://blogs.msdn.com/b/vscode/archive/2015/07/06/vs-code-es6.aspx)
[IntelliSense Support](https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson)

**Comment by scottaddie** [comment]
I believe you're correct in that the file serves no purpose outside of Visual Studio. Along the same lines, does it make sense to remove the "Clean" binding in gulpfile.js? See snippet below. I believe this is a VS-only concept as well, since Task Runner Explorer writes it to the file.

```xml
/// <binding Clean='clean' />
```

**Comment by peterblazejewicz** [comment]
We were removing all these artefacts. The exception was `web.config` under beta8 and later which was left to support IIS deployment.
Maybe we should rewrite all these VS related tooling concepts into VSCode? It works x-plat and has similar concepts.

**Comment by scottaddie** [comment]
I really like the idea of incorporating event bindings in VS Code. Command Palette's Run Task command is the equivalent to Task Runner Explorer in VS. Maybe a "Task Runner Explorer" extension could be written to read in those comments at the top of gulpfile.js and then take the appropriate action. I'd have to put some more thought into this to determine how it could work.
