### ISSUE TITLE
Remove unneeded dnx451 framework reference from the empty application project.json

### ISSUE THREAD

**Issue by johnmcbride** [OmniSharp/generator-aspnet#522]
When creating a new empty application using the aspnet generator, the project.json includes a reference to the dnx451 framework. This is un-needed to run the simple generated app and also could be confusing if the user runs "dnu build" and doesn't have the mono framework (dnx451) installed (or selected as default).

As a quick start, the template should target the just the "dnxcore50" since that would get installed by default in a new first time use scenario. 

Steps to recreate.
1.  Set the default to dnxcore (dnvm use 1.0.0-rc1-final -p -r coreclr)
2.  Create a new empty application via the generator (yo aspnet => select the empty application and give it a name)
3. Change into the created directory
4. Run "dnu restore"
5. Run "dnu build"
6. Observe the build error (also attached)

Current dnvm settings
![image](https://cloud.githubusercontent.com/assets/125551/11454848/d441d9fe-960c-11e5-9383-d627d623b297.png)

Build output
![image](https://cloud.githubusercontent.com/assets/125551/11454851/f38eb908-960c-11e5-9db6-ec47b94aa66e.png)
![image](https://cloud.githubusercontent.com/assets/125551/11454856/01e0a4da-960d-11e5-9b8b-3650b6403977.png)

**Comment by peterblazejewicz** [comment]
@johnmcbride 
Thanks for the feedback!
I'm afraid the content cannot be changed. That is default and documented structure of all *core* ASP.NET 5 applications:
http://docs.asp.net/en/latest/conceptual-overview/dotnetcore.html#building-applications-with-net-core
> The recommendation from the ASP.NET team is to target both frameworks with new applications. [...]

People are confused by that double-nature (including me) and the same problem you've described (running CoreCLR) has been already discussed:
https://github.com/aspnet/Home/issues/1104
https://github.com/OmniSharp/generator-aspnet/issues/509

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
