### ISSUE TITLE
Add shortcut command for installing dependencies

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#523]
While Visual Studio 2015 provides assistance to install the necessary NuGet, Bower, and npm dependencies, the same is not true for editors such as VS Code. If I scaffold a new web application and want to install the dependencies, there is 1 command required per package manager being used:
1. `dnu restore`
2. `npm i`
3. `bower i`

It would be handy to have a `package.json` script to run all 3 commands. It might look like this on Windows:

``` json
  "scripts": {
    "install-deps": "dnu restore && npm i && bower i"
  },
```

With this in place, simply run this in a command shell:

`npm run install-deps`

As an alternative, maybe a `project.json` script could be used to accomplish the same task. That could look something like this:

``` json
  "scripts": {
    "postrestore": [
      "npm install",
      "bower install"
    ]
  }
```

In this case, there's still just 1 command to run: `dnu restore`. This would be the more "ASP.NETish" way of doing it and would probably be preferred.

**Comment by peterblazejewicz** [comment]
> In this case, there's still just 1 command to run: dnu restore. This would be the more "ASP.NETish" way of doing it and would probably be preferred.

https://github.com/OmniSharp/generator-aspnet/issues/295
https://github.com/OmniSharp/generator-aspnet/issues/400
and others.

The influencers of asp/mvc should came with some solution for this problem, so it could be promoted later via docs.asp.net. We could help them. 

> the same is not true for editors such as VS Code.

We could ship pre-built VSCode tasks with each project, to offer the same support *full* VS is providing.

https://code.visualstudio.com/Docs/editor/tasks

(so basically swapping each VS tooling added feature to VSCode feature)
I'll look into this option after finally enabling VSCode back with RC1 on OS X:
https://github.com/Microsoft/vscode/issues/471

**Comment by spboyer** [comment]
There is a long debate on whether or not to auto install the dependencies when opening a project.  There are tasks in the npm scripts as @scottaddie  mentioned you can put in which is acceptable.  I like to leave it to the developer to decide how they like to accomplish this task.

Visual Studio devs prefer to have GUI over bash or command line, auto install over manual install.

My thought is to leave this as it is and not be opinionated on it. Or be opinionated and not do anything

**Comment by scottaddie** [comment]
In my opinion, this seems like an area in which deviating from the VS 2015 templates provides a tangible benefit. If, for example, I'm using VS Code, I have to execute 3 separate package manager commands to install the scaffolded project's dependencies.

By providing some sort of shortcut, you're saving the user a little bit of time straight out of the gate. In the case of the "StarterWeb" template, the generator already provides `dnu restore` as a suggested command once the project has been scaffolded:

![yo_project](https://cloud.githubusercontent.com/assets/10702007/11566440/0a7f896e-99a8-11e5-8865-996ab55b0915.png)

What this doesn't tell you is that `npm install` and `bower install` should also be executed. If the shortcut idea isn't something we'd like to implement, I would at least recommend listing `npm install` and `bower install` under `dnu restore`.

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
