### ISSUE TITLE
Dockerfile microsoft/aspnet:1.0.0-rc1 not found

### ISSUE THREAD

**Issue by AlexChesser** [OmniSharp/generator-aspnet#524]
1. use `yo aspnet` generate a webapplication  
2. run `docker build .`

Error Message: 
```
PS C:\Users\Alex\www\aspnet-docker\WebApplication> dk build .
Sending build context to Docker daemon 834.6 kB
Step 1 : FROM microsoft/aspnet:1.0.0-rc1
Pulling repository docker.io/microsoft/aspnet
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
Tag 1.0.0-rc1 not found in repository docker.io/microsoft/aspnet
```

note that LOCALLY editing the generated Dockerfile to repace line 1:
`FROM microsoft/aspnet:1.0.0-rc1`   
with   
`FROM microsoft/latest`  

will allow for a successful build *but* there is another issue (which I will create separately as I believe it is has a separate cause.

**Comment by peterblazejewicz** [comment]
@AlexChesser 
I believe this is just a bug (I haven't yet read other issues). The tag name is wrong.
TBD

**Comment by peterblazejewicz** [comment]
@AlexChesser 
can you let us know which version of generator-aspnet is installed on our machine?
There is a slight chance you've got a version which uses invalid tag:
https://github.com/OmniSharp/generator-aspnet/blob/8b5b8be19329af9ace04d71de1ea83c0328911c8/templates/Dockerfile.txt#L1
fixed after couple of days to correct one:
https://github.com/OmniSharp/generator-aspnet/blob/b06be7a37d754c77a90e119f8db0ec5eb9f6cbdb/templates/Dockerfile.txt#L1
Thanks!

**Comment by AlexChesser** [comment]
Hi @peterblazejewicz  - looks like you're right - I've tested with your latest generator where the tagname is `FROM microsoft/aspnet:1.0.0-rc1-final` instead of `FROM microsoft/aspnet:1.0.0-rc1` and this appears to be working fine now.

Safe to close.

**Comment by peterblazejewicz** [comment]
@AlexChesser 
Thanks!
