### ISSUE TITLE
Dockerfile re-downloads all dependencies on ANY code change

### ISSUE THREAD

**Issue by AlexChesser** [OmniSharp/generator-aspnet#527]
I've gone into some pretty deep detail in this issue over here https://github.com/aspnet/aspnet-docker/issues/123

And the team over at the aspnet-docker image would like to keep the image as the "lean base image" though they did provide some hints on how developers could improve their speed.

I've tweaked the order of operations in the Dockerfile over here:
https://github.com/AlexChesser/generator-aspnet/commit/0ec1932b2d4695178defb73900337993b8e5da81

What this effectively does is allow's for the user's dependencies to be installed on the base image and effectively cached so an application restart can be done in seconds rather than minutes.

**old-speed**
Start: 06:03:13.313
Finish: 06:06:40.640

**new-speed**
Start: 06:00:36:036
Finish: 06:00:45:045

I've also added a somewhat lengthy comment around why things are being put in that order. Specifically since the generators are often the first documentation that users read, and the thing about "why it is slow" has taken me a couple weeks understanding how to tun docker performance, I think bubbling that key point up to fresh developers is really useful.

PR incoming.

**Comment by AlexChesser** [comment]
Fixed in https://github.com/OmniSharp/generator-aspnet/pull/526

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
