### ISSUE TITLE
Project Templates

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#53]
the generator now works off of *samples* for the mvc and web project types.  Proposing that the Empty and Web project templates (from VS2015) be added or replace these as the core project templates for these types.  Would you also like to see a basic MVC API starter template?

@sayedihashimi

**Comment by spboyer** [comment]
also have the namespace for the project be the [name] argument or an --option when creating

i.e. `yo aspnet myAppName --ns MyNamspace` 

defaults to myAppName if --ns not defined

**Comment by peterblazejewicz** [comment]
As to projects - I'd like to see the same (or nearly the same) list of templates that is available via VS IDE in generators. That would allow me (or any other user keen to learn asp.net ) to just scaffold discussed project template and then follow existing blog/page from MS/evangelist even without installing VS IDE

**Comment by spboyer** [comment]
Starter Web project in VS2015 uses SQL Server, cannot use this option on non Windows machines for local development.  Should consider another option that is cross compat.

**Comment by peterblazejewicz** [comment]
Already added :)
