### ISSUE TITLE
Remove sqlite patch from Dockerfile when RC2 ships

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#532]
This is a task. The PR that patches Dockerfile with SQLite installation required for EntityFramework has been just merged: #530 
The `Microsoft.Data.Sqlite` will be changed in RC2 to support SQLite in version that ships by default in Ubuntu 14.04 used by `aspnet-docker`.
When RC2 ships the patch for non-standard sqlite version should be removed from Dockerfile:

https://github.com/aspnet/aspnet-docker/pull/122#issuecomment-162708193
https://github.com/aspnet/Microsoft.Data.Sqlite/pull/171

**Comment by sesispla** [comment]
As discussed in [aspnet/aspnet-docker#122 (comment)](https://github.com/aspnet/aspnet-docker/pull/122), one of the possible solutions is:
"the yo generators can either maintain their own bigger base images (based on the aspnet one) or they can generate Dockerfiles based on aspnet that optionally adds sqlite based on user choice."

Maybe is a good idea to check if the project type requires EF and ask for the concrete DB the user would like to use:
 ```
    _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |  marvellous ASP.NET Core |
    ( _´U`_ )    |      1.0 generator!      |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What type of application do you want to create? Web Application
? Which UI framework would you like to use? Bootstrap (3.3.6)
? Which database would you like to use? (Use arrow keys)
❯ SQL Server 
  Sqlite 
  None 
```

This would have impact on both Project.json and Dockerfile content, helping us keeping an slower Docker image footprint.

As discussed in #743, current sqlite3 mirror as configured by EF team is down, so we cannot currently offer 100% funcional solution...

Also, by comments on  [aspnet/aspnet-docker#122 (comment)](https://github.com/aspnet/aspnet-docker/pull/122) it is also not clear if the base docker image will ship with sqlite3 oob or not.

**Comment by peterblazejewicz** [comment]
That cannot be solved - there is still no solution for out-of-the-box SQLite on microsoft/dotnet image:
https://github.com/aspnet/EntityFramework/issues/5382#issuecomment-219769542

The topic is outdated as you've pointed:

> Also, by comments on aspnet/aspnet-docker#122 (comment) it is also not clear if the base docker image will ship with sqlite3 oob or not.

Let me close this one.
Thanks!
