### ISSUE TITLE
Should changes from RC1-update1 be incorporated in generator?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#533]
There was a RC1-update1 release recently:
https://github.com/aspnet/Home/issues/1151#issuecomment-162064799
http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx
https://github.com/aspnet/Home/tree/dev/samples/1.0.0-rc1-update1
The `latest` image of aspnet-docker points and uses rc1-update1 dnx.
There are not (AFAIK) update1 related changes on aspnet/Templates

@spboyer 
What do you think about docker image?

@sayedihashimi @rustd
Should we add updates? I don't know any outstanding issues with RC1, other then one linked on MS post:
https://github.com/aspnet/dnx/issues/3183

**Comment by spboyer** [comment]
The docket image has changed related, meaning it has the latest coreclr and mono based install bits. There should be an update of the generator release imo

**Comment by peterblazejewicz** [comment]
Thx Shayne!
