### ISSUE TITLE
Create TypeScript JSX Sub-generator

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#540]
In VS 2015, there is an item template available for a TypeScript JSX (.tsx) file. This project already provides subgenerators for TypeScript (.jsx) and TypeScript (.ts) files, so it would seem to make sense to add this. Any interest in adding support for it here? If so, I'll submit a PR for it.

**Comment by peterblazejewicz** [comment]
Can the source of this be somehow found? The sources here are somehow based on existing templates from variety of sources.

**Comment by scottaddie** [comment]
Unfortunately, the item templates aren't yet open source (see https://github.com/aspnet/Templates/issues/32), so there's not much we can do. My proposal is to simply create a .tsx file with the following comment:

```javascript
// A '.tsx' file enables JSX support in the TypeScript compiler, 
// for more information see the following page on the TypeScript wiki:
// https://github.com/Microsoft/TypeScript/wiki/JSX
```

This is what the item template in VS 2015 currently produces. Thoughts?

**Comment by peterblazejewicz** [comment]
:+1: 
Go ahead

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
