### ISSUE TITLE
Create clean & min tasks for Gruntfile.js

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#544]
When running `yo aspnet --grunt` and scaffolding a web project, a `Gruntfile.js` file is created in place of `gulpfile.js`. With Gulp, `min` and `clean` tasks are provided. The same is not true for Grunt. Is there any interest in adding `min` and `clean` tasks which replicate exactly what's done for Gulp?

**Comment by peterblazejewicz** [comment]
As generator follows closely VS Templates, that is unfortunate result of templates dropping Grunt completely:
https://github.com/OmniSharp/generator-aspnet/issues/286
https://github.com/OmniSharp/generator-aspnet/blob/53d0ee7bffe246328c761b3b4a3f8427e2744152/templates/projects/web/gruntfile.js

Do you think we should develop this feature? We could just follow content from official docs.asp.net:
http://docs.asp.net/en/latest/client-side/using-grunt.html

**Comment by scottaddie** [comment]
I'm looking at this from the perspective of a Grunt user. Such a user might wonder why Gulp receives special treatment or a better starting point in the generator. Sure, it's the default task runner in the templates, but I'd expect a better starting point after scaffolding a web app.

If we do decide to develop it, I'd simply convert what's provided in `gulpfile.js` over to Grunt tasks. Many of the plugins mentioned in the official doc would be used.

**Comment by peterblazejewicz** [comment]
It won't be so smooth as Grunt requires additional temp output directory (I've an old feature branch with this on machine). 
I've mixed opinion on which way to follow, I'd always use one better documented. The gulp is better documented in a way used in templates simply:
http://docs.asp.net/en/latest/client-side/using-gulp.html
The '--grunt' option is left here as not used in VS Templates and is purely this project only, so it's up to contributors to decide how to implement it.
I'd help with implementation.

**Comment by scottaddie** [comment]
I agree that the implementation won't be quite as nice as Gulp, due to the file vs. stream difference between the 2 task runners. To replicate what's provided for Gulp, I think we'd need the following npm modules:

1. `grunt`
2. `grunt-contrib-clean`
3. `grunt-contrib-concat`
4. `grunt-contrib-cssmin`
5. `grunt-contrib-uglify`

In the upcoming RC2 release, a Gulp watch task is being added as well. That means we'd need to pull in `grunt-contrib-watch` to replicate that behavior.

**Comment by peterblazejewicz** [comment]
The `.gitignore` will have to be updated with directory of `temp` folder to avoid committing artefacts I think. We use one based on github/gitingores:
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/gitignore.txt
and this hidden Grunt gem:
https://github.com/github/gitignore/blob/master/Node.gitignore#L17-L18

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
