### ISSUE TITLE
Generated Dockerfile seems off

### ISSUE THREAD

**Issue by carolynvs** [OmniSharp/generator-aspnet#556]
I have generator-aspnet 0.0.91 installed. After generating a web application, I am encountering a few unexpected problems.

First, the base image used (microsoft/aspnet:1.0.0-rc1) doesn't appear to exist anymore? So I tried 1.0.0-rc1-final.

Then I run into the sqlite / docker bug that I thought was already patched (#525). 

The generated Dockerfile is below (with my tag change)

```
FROM microsoft/aspnet:1.0.0-rc1-final

COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]

EXPOSE 5000/tcp
ENTRYPOINT ["dnx", "-p", "project.json", "web"]
```

The template on master https://github.com/OmniSharp/generator-aspnet/blob/master/templates/Dockerfile.txt seems to have the sqlite fix:

```
RUN printf "deb http://ftp.us.debian.org/debian jessie main\n" >> /etc/apt/sources.list
RUN apt-get -qq update && apt-get install -qqy sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*
```

I'm not sure why my Dockerfile doesn't have the fix. Perhaps the version published to node is out of date?

Or maybe the sqlite fix is not need anymore? I just tried another image tag `microsoft/aspnet:1.0.0-rc1-update1-coreclr` and it ran fine. Perhaps the generator just needs to use that instead?

Sorry, lots of questions and not sure what the right answer is. :smiley:

**Comment by peterblazejewicz** [comment]
Hi,
That's because NPM version is a little off behind the master. We have been discussing that today and it should be updated shortly, sorry!
You could use current master which contains updated Docker template:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/Dockerfile.txt
Sorry for inconvience!

**Comment by carolynvs** [comment]
Thanks for the quick update! I wasn't sure which was the right text to use, or if I was off in the weeds. :+1:

**Comment by peterblazejewicz** [comment]
@carolynvs 
The NPM is updated to 0.0.92
Thanks!
