### ISSUE TITLE
Expand tests coverage to cover features added with #555

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#559]
The #555  has been merged and the test coverage should be expanded to better cover use-cases for this  features. Adding them requires scaffolding support during test for application with option and arguments, which is not yet in test utils. 
- refactor test utils to add options/arguments support to mocked app generator
- update tests

Thanks!

**Comment by jackjwilliams** [comment]
Has this not been done? When I wrote tests for the Semantic UI integration I could have sworn I saw tests for the options/args, or even added support for the "uiframework" argument. If not, can you explain more about what it is you want done?

**Comment by peterblazejewicz** [comment]
You've added generator specific tests:
https://github.com/OmniSharp/generator-aspnet/blob/39e9c3121fe2c60f22a3ab7c52e38a0eaa144be3/test/test-core.js#L336
This topic is aobut covering (refactoring) tests that act on all options/arguments (we should correctly handle all allowed arguments and bail out on all others. The code has limited list of allowed arguments, but that is not covered by tests yet)

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
