### ISSUE TITLE
kestrel on docker is not accessible

### ISSUE THREAD

**Issue by ipinak** [OmniSharp/generator-aspnet#562]
When using Docker, Kestrel runs on `localhost` which makes it inaccessible. It should run on `0.0.0.0` instead.

**Comment by spboyer** [comment]
Add `--server.urls=http://0.0.0.0:5000` To the commands section of your project.json

**Comment by ipinak** [comment]
Thanks, but I know the solution. I was thinking to create a pull request to fix this. Without it you cannot access the web app.

**Comment by anthonychu** [comment]
Can this be solved is by changing the container entry point so it's not dependent on the "web" command in project.json at all? Something like:

    ENTRYPOINT ["dnx", "-p", "project.json", "Microsoft.AspNet.Server.Kestrel", "--server.urls", "http://0.0.0.0:5000"]

The way I see it right now, if someone doesn't know to change localhost to 0.0.0.0 in project.json, they'll be banging their head for a while. The above change would make the Dockerfile more plug-and-play for most aspnetcore apps, IMO.

**Comment by peterblazejewicz** [comment]
@anthonychu 
We have been discussing this in separate PR:
https://github.com/OmniSharp/generator-aspnet/pull/563#issuecomment-185315343
I'm keen to just update docs.asp.net with note about this problem, not actual files like config or Dockerfile in templates, as the templates are closely related to aspnet/Templates and to content documented in docs.asp.net
