### ISSUE TITLE
Issue and Pull Request templates - changes for project contributors

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#565]
The GitHub added feature to help with project management:
https://github.com/blog/2111-issue-and-pull-request-templates
- [x] `.github` directory to minimize clutter in root folder
- [x] `CONTRIBUTING` file review and move to `.github`
- [x] `ISSUE_TEMPLATE` - add file to `.github`
- [x] `PULL_REQUEST_TEMPLATE` - add file to `.github`

**Comment by sayedihashimi** [comment]
+1 thanks Peter
