### ISSUE TITLE
New Generator that creates controller and model at the same time

### ISSUE THREAD

**Issue by nicolastakashi** [OmniSharp/generator-aspnet#567]
It would nice to have a generator that can create a controller and model at the same time, for example:
- When working with ASP.NET Web API create a controller that have a controller actions return typed;
- When work with ASP.NET MVC create a controller, model, view and have a controller typed actions;

**Comment by sayedihashimi** [comment]
Seems like a reasonable suggestion, let's see what others think.

**Comment by nicolastakashi** [comment]
@sayedihashimi I think That It can help us go fast During coding time, doing simple things but that get a long time our.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
The item templates are not open-sourced if I remember well. Will find a reference if required. If I'm not wrong, this issue discuss item templates:
https://github.com/aspnet/Templates/issues/32

**Comment by sayedihashimi** [comment]
@peterblazejewicz thanks. I'll see if we can open source the item templates. Item templates have much less churn than project templates. For empty view/controller/model I don't expect the content to change.

We already have sub generators for MvcController, MvcController and Class.

If I understand the proposal correctly when you invoke this new sub generator it will just call those sub-generators with specific names. For example

```yo aspnet:ModelViewController Person```.

That will then call

```
yo aspnet:Class person
yo aspnet:MvcController person
yo aspnet:MvcView person
```

I'm not sure if the class should go into the root directory or the models folder though in this case.

**Comment by nicolastakashi** [comment]
@sayedihashimi I think that in this case the class should go into models folder, because we talk about view models, so i think it is good choice put there..

**Comment by spboyer** [comment]
I opened this dialog a while back in this issue -> https://github.com/OmniSharp/generator-aspnet/issues/49

**Comment by nicolastakashi** [comment]
So how we can put this idea in some release? Somebody have any question or idea about this case?

**Comment by peterblazejewicz** [comment]
This topic has at least one blockers:
https://github.com/aspnet/Templates/issues/32
This one is important to know what structure is created with particular *add new item* action.

**Comment by sayedihashimi** [comment]
@peterblazejewicz I'm not sure if I'm following you here. The items you listed are pretty static so not being oss shouldn't be a blocker, but I may be missing something.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Looks I'm a blocker :) What I mean: that would be best option if there is a repo with a source of such items at first place.

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
