### ISSUE TITLE
Suggestion: Rename the "Empty Application" to "Web Empty Application"

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/generator-aspnet#587]
The yomen generators have options for "Empty, Console, Web, Web Basic, Web API, Nancy, Class Lib, and Unit test". Given the broad reach of these templates, I would recommend that Empty be named more inline with how VS categorizes it and what it contains. Empty is not an empty project, but rather a barebones Web app.

**Comment by peterblazejewicz** [comment]
x-ref:
https://github.com/aspnet/Templates/issues/422
(and specifically 'empty' template discussion)
cc/ @sayedihashimi 
reposted from: https://github.com/aspnet/Templates/issues/481

**Comment by sayedihashimi** [comment]
Yes he has a valid point. I think "Empty Web Application" is the correct term that we should be using.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
`EmptyWeb`?
Following most used version from aspnet/Templates:
https://github.com/aspnet/Templates/tree/dev/src/BaseTemplates
