### ISSUE TITLE
Should project templates ship with VSCode tasks/launch configs with or after dotnet cli?

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#596]
I've watched last standup:
https://www.youtube.com/watch?v=fkzeOqSNtwQ&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=0
with Damien presenting debugging and running from VSCode via OmniSharp plugin all without VS.
As far as I understand (I don't have yet dotnet runtime installed to avoid problems with maintaining RC1 builds), this will be simply possible by scaffolding launch/config VSCode settings after opening example project. We could ship that json files with templates.
That would allow to quickly add IDE support to projects.

Thanks!

**Comment by spboyer** [comment]
VSCode will auto add these for you

**Comment by peterblazejewicz** [comment]
Thanks Shayne!
