### ISSUE TITLE
ASP.NET Core RC2 Empty Web Application

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#597]
This is an initial sample to get the generators unblocked. Attaching the sample below
[WebApplication1.zip](https://github.com/OmniSharp/generator-aspnet/files/230663/WebApplication1.zip)

.NET CLI
.NET Command Line Tools (1.0.0-rc2-002392)
Install Location: https://github.com/dotnet/cli#installers-and-binaries

NuGet Feed
https://www.myget.org/F/aspnetrelease/api/v3/index.json
https://api.nuget.org/v3/index.json

//cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
Me
Thanks!

**Comment by peterblazejewicz** [comment]
I've got warnings when building sample:

> /Users/piotrblazejewicz/Downloads/WebApplication1/project.json(8,68): warning NU1007: Dependency specified was Microsoft.AspNetCore.Server.IISIntegration >= 1.0.0-rc2-20581 but ended up with Microsoft.AspNetCore.Server.IISIntegration 1.0.0-rc3-20636.
/Users/piotrblazejewicz/Downloads/WebApplication1/project.json(9,61): warning NU1007: Dependency specified was Microsoft.AspNetCore.Server.Kestrel >= 1.0.0-rc2-20581 but ended up with Microsoft.AspNetCore.Server.Kestrel 1.0.0-rc3-20636.

**Comment by rustd** [comment]
Please ensure that you are only using these feeds and delete any cached packages.

**Comment by peterblazejewicz** [comment]
```
Feeds used:
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
    https://api.nuget.org/v3/index.json
```

**Comment by peterblazejewicz** [comment]
Also the dotnet restore spills the error:
```
Errors in /Users/piotrblazejewicz/Downloads/WebApplication1/project.json
    Package Newtonsoft.Json 7.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 7.0.1 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```
(though restore completes, builds and runs)

**Comment by rustd** [comment]
Can you please update the tools section as follows and see if the error still happens on restore?


```json
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-rc2-20581",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },
```

Sorry for the back and forth but we are still working through some issues and wanted to unblock the generators early.

**Comment by peterblazejewicz** [comment]
understandable - no worries :)

**Comment by peterblazejewicz** [comment]
@rustd 
This seems to fix problem with Newtonsoft package errors. All I see now are warnings (warning NU1007).
It seems to be OK to proceed further now with templates. Let me know. Thanks!

**Comment by rustd** [comment]
Thanks! It should be ok to proceed. Can you please specify the warning here?

**Comment by peterblazejewicz** [comment]
> Compiling WebApplication1 for .NETCoreApp,Version=v1.0
/Users/piotrblazejewicz/Downloads/WebApplication1/project.json(8,68): warning NU1007: Dependency specified was Microsoft.AspNetCore.Server.IISIntegration >= 1.0.0-rc2-20581 but ended up with Microsoft.AspNetCore.Server.IISIntegration 1.0.0-rc3-20636.
/Users/piotrblazejewicz/Downloads/WebApplication1/project.json(9,61): warning NU1007: Dependency specified was Microsoft.AspNetCore.Server.Kestrel >= 1.0.0-rc2-20581 but ended up with Microsoft.AspNetCore.Server.Kestrel 1.0.0-rc3-20636.

**Comment by peterblazejewicz** [comment]
We need to lock down deps

**Comment by rustd** [comment]
You are using feeds which are point to RC3 or the RC3 packages are cached. If you clear off the local cached packages and only use the above 2 feeds then this should not happen

**Comment by peterblazejewicz** [comment]
@rustd 
Fixed by removign .dxn/.nuget packages and caches  and with an exact NuGet:
https://github.com/OmniSharp/generator-aspnet/issues/602#issuecomment-213738780
