### ISSUE TITLE
ASP.NET Core RC2 Web Application with no Authentication

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#598]
This is an initial sample to get the generators unblocked. Attaching the sample below
[NoAuthWeb.zip](https://github.com/OmniSharp/generator-aspnet/files/230670/NoAuthWeb.zip)

.NET CLI
.NET Command Line Tools (1.0.0-rc2-002392)
Install Location: https://github.com/dotnet/cli#installers-and-binaries

NuGet Feed
https://www.myget.org/F/aspnetrelease/

//cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
Assigned. Thanks!
