### ISSUE TITLE
.NET Core Class Library template for RC2

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#599]
This is an initial sample to get the generators unblocked. Attaching the sample below
[ClassLibrary1.zip](https://github.com/OmniSharp/generator-aspnet/files/230672/ClassLibrary1.zip)

.NET CLI
.NET Command Line Tools (1.0.0-rc2-002392)
Install Location: https://github.com/dotnet/cli#installers-and-binaries

NuGet Feed
https://www.myget.org/F/aspnetrelease/

//cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
Assigned to me. Thanks!
