### ISSUE TITLE
can not install yeoman

### ISSUE THREAD

**Issue by ChuanjenWang** [OmniSharp/generator-aspnet#605]
### Short issue description

ChuanJen-Wangs-MacBook-Pro:~ ChuanJen$ npm install -g yo
npm ERR! tar.unpack error reading /Users/ChuanJen/yo
npm ERR! addLocal Could not install /Users/ChuanJen/yo
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ChuanJen/npm-debug.log

### Steps to reproduce the behavior

----
#### NodeJS version
```
node --version
```

#### Yeoman version
```
yo --version
```

#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
have you run `npm cache clean` as pointed in error log? (this is NPM issue btw)

**Comment by peterblazejewicz** [comment]
Thanks!
