### ISSUE TITLE
Review Semantic UI version for RC2 updates

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#613]
The Semantic UI part needs some review.
Most important is to review and rewrite custom TagHelper implementation in RC2, which is now failing to build properly.

Related RC2 PR:
https://github.com/OmniSharp/generator-aspnet/pull/612

/cc @jackjwilliams 
When you have time, can you look into my changes in #612? 
It will require a full dotnet development installed. Also info here: #602

**Comment by jackjwilliams** [comment]
@peterblazejewicz Yes I'll take a look, thanks.

**Comment by jackjwilliams** [comment]
@peterblazejewicz I have a proposed fix, but do not have permissions to push to #612

**Comment by peterblazejewicz** [comment]
@jackjwilliams Josh, yes, I just need a gist if you got it working. I've tried to nail down which package should be updated (the error is through `microsoft.aspnet.html.abstractions` which does not translate easily to `microsoft.aspnetcore.mvc.abstractions` at all). The build phase fails on menu helper thing.
I'm on the mac and don't have any IDE to help with this.
Have I missed a package rename on aspnet/Templates for this bit, btw?

**Comment by peterblazejewicz** [comment]
correction: this note helps to install VSCode C# dotnet features on OS X:
https://github.com/gregg-miskelly/omnisharp-vscode/blob/daily-build-docs/debugger.md

**Comment by jackjwilliams** [comment]
Yeah even with VS2015, I don't believe the tooling is ready for it yet so I had to do some guesswork.

Here is the gist

https://gist.github.com/jackjwilliams/4165ba5a9f1cb1f635c55895eba87e51

**Comment by peterblazejewicz** [comment]
@jackjwilliams 
It works!
![image](https://cloud.githubusercontent.com/assets/14539/14768812/bbcd0296-0a4b-11e6-956c-61f3c0a52754.png)

Thanks!

**Comment by peterblazejewicz** [comment]
I've updated #612 PR

**Comment by jackjwilliams** [comment]
Good deal! Don't forget to update the file in both web and webbasic overrides.

Thanks

**Comment by peterblazejewicz** [comment]
Yeah, first `webbasic`. The `web` is not yet ready I think, but should be updated soon. Thanks again!

**Comment by jackjwilliams** [comment]
No problem, let me know if there's anything else I can do.
