### ISSUE TITLE
Update documentation describing generated samples

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#63]
The generator README is missing basic description what we are generating in case of full samples:
```
Empty Application 
  Console Application 
  Web Application 
  MVC Application 
  Nancy ASP.NET Application 
  Class Library 
  Unit test project 
```
A @VisualStudio contains a small help block in wizard when using given template - we could use something similar I think.

**Comment by VisualStudio** [comment]
I don't understand because I'm just a program.

**Comment by GoIIy** [comment]
Me no understand.

**Comment by peterblazejewicz** [comment]
![newproj1](https://cloud.githubusercontent.com/assets/14539/6143923/ede53c50-b1d0-11e4-807d-0afde6a201ee.jpg)

**Comment by larsw** [comment]
Ok, what has to be done here (e.g. where should the help texts be output)?

**Comment by peterblazejewicz** [comment]
We could update README (or introduce another file) - so one could read for example what is "Web Application" project now - while the release article for CTP 6 states this is "Starter Web":
http://blogs.msdn.com/b/webdev/archive/2015/02/23/aspnet-5-updates-for-feb-2015.aspx
Maybe that is not a task for now yet, as the features are still in flux, but definitely something for near future.
If someone has some ASP .NET application the MVC application (template) is better known/recognised - not sure for new terms.

**Comment by peterblazejewicz** [comment]
I'm closing this in favor of #95
Thanks!
