### ISSUE TITLE
Node 6 compatibility during development

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#654]
### Short issue description

Some tests fails when switched to Node 6. All failed tests fail with message like:

```
Uncaught TypeError: Path must be a string. Received null
```

thrown in internal generator implementation (but could be due to arguments our code pass to genertor).

TBI

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
