### ISSUE TITLE
What's Missing?  

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#66]
What's missing? What do you need here to make it better?
- more templates
- larger examples, starters

**Comment by peterblazejewicz** [comment]
#1
blogs/articles with content built with generator. This will show (or prove) how it could be used in real world scenario of at least something simple
#2
some description on how it fits into C#/.NET envisioned platform - something with clear copy statements what this tool is for, how it can be used on its own, more than on current OmniSharp project landing page:
http://www.omnisharp.net/

So yes, it fits exactly into *starters* category (I remember we have already talked about this).

I'll be attending online C# course and I want to take it using solely on *nix platform (the course won't be using MS/SQL framework) so I'll get some experience with day-to-day tool use (at work I'm on Windows OS).

And more stable vNext releases

**Comment by sayedihashimi** [comment]
Adding @shanselman to see if he had thoughts, I'll reply back as well soon

**Comment by luisrudge** [comment]
We need to have a version with gulp + kmon or https://github.com/tugberkugurlu/gulp-aspnet-k available! That would be awesome.

**Comment by ctolkien** [comment]
I've some opinions on what would need to be in a "standard" gulp/grunt file (inc. gulp-aspnet-k), less, sourcemaps,  watching, image optimisation, etc. (i.e, replicating a lot of what web essentials would/used to do). Not really sure where the line should be drawn however, with regard to "clean slate", vs. getting up and running with something productive.

**Comment by sayedihashimi** [comment]
How about modifying the existing generator to expose a grunt or gulp option? Then generate equivalent experiences using either.

Thoughts?

**Comment by luisrudge** [comment]
@sayedihashimi yeah. That's what I thought. @ctolkien the great thing about yo is that we can have options for that. Maybe we can ask the user: Do you want to enable image optimization? Do you want less or saas?

**Comment by spboyer** [comment]
The default template has "some" grunt functionality in there. I will take on the task of putting in the gulp functionality. 

I have been working on an adaptation already using @johnpapa gulp patterns for angular. https://github.com/johnpapa/gulp-patterns

**Comment by luisrudge** [comment]
please don't createa gulp file with 700 lines of code.
https://github.com/johnpapa/gulp-patterns/blob/master/gulpfile.js

**Comment by sayedihashimi** [comment]
I'd like to have a gulp file that is equivalent to the grunt file that VS ships. We can create sub-generators for advanced content like that.

**Comment by luisrudge** [comment]
Yeah. I agree with that

**Comment by spboyer** [comment]
@sayedihashimi  @luisrudge Issue added - https://github.com/OmniSharp/generator-aspnet/issues/80

**Comment by sayedihashimi** [comment]
Can we close this?

**Comment by spboyer** [comment]
Closing do to dormant activity
