### ISSUE TITLE
Semantic UI review for RC2

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#660]
@jackjwilliams 
Josh, would you mind reviewing via PR a RC2 branch which contains updated web/webbasic content
for RC2?
https://github.com/OmniSharp/generator-aspnet/tree/rc2
I've just pushed and merged a PR (#659) into RC2 branch with changes required to run it on RC2 via `dotnet` cli and I've got it working just like BS version on my mac (OS X 10.*)
Appreciated
Thanks!

**Comment by jackjwilliams** [comment]
@peterblazejewicz Sure, is there anything specific you want me to review? You say you have already merged PR #659 which looks like it has most of the needed changes for the web project. 

Are you just wanting me to look over #659 or create a new PR?

**Comment by peterblazejewicz** [comment]
Well, just fetch 'RC2' branch and when used locally (via npm link) get `web` and `webbasic` project types with Semantic UI. Watch for things I could missed.
If there is anything to correct, just created topic branch from RC2 (not-master) and make PR.
Thanks!

**Comment by jackjwilliams** [comment]
@peterblazejewicz Gotcha, I'll try to take a look tonight!

Thanks

**Comment by jackjwilliams** [comment]
@peterblazejewicz One thing I see (not related to Semantic UI) is that we need to update our intro animated gif (it still shows the old flow).

**Comment by jackjwilliams** [comment]
@peterblazejewicz Everything looks good on my end, however, when RC2 tooling becomes available for VS2015 I would like to run through all the scenarios (External Auth, Two-Factor auth, etc...). I tried without the tooling but I don't have the time for all that right now.

**Comment by peterblazejewicz** [comment]
> One thing I see (not related to Semantic UI) is that we need to update our intro animated gif (it still shows the old flow - doesn't show UI Framework selection or new Core command usage).

It can be part of booked update:
https://github.com/OmniSharp/generator-aspnet/issues/604

**Comment by peterblazejewicz** [comment]
> Everything looks good on my end, however, when RC2 tooling becomes available for VS2015 I would like to run through all the scenarios (External Auth, Two-Factor auth, etc...)

Sure thing. I'm closing this issue for now.
Thanks!
