### ISSUE TITLE
Nancy generator is outdated

### ISSUE THREAD

**Issue by joaomoreno** [OmniSharp/generator-aspnet#67]
I used this generator to scaffold a Nancy application. I ended up with something that could be run (`k kestrel`) but not built (`kpm restore; kpm build`). It couldn't find the Nancy namespace when building.

I looked at @jchannon's [generator-nancy](https://github.com/jchannon/generator-nancy) and tried it out. It produced a seemingly healthier scaffold which I can both run and build successfully.

Why not incorporating [generator-nancy](https://github.com/jchannon/generator-nancy) into this project?

**Comment by jchannon** [comment]
Pretty sure the dependencies are exactly the same so would be interested to
know what the diffs are

**Comment by joaomoreno** [comment]
It seems to only be in the `project.json`:

``` diff
diff aspnet-nancy/project.json nancy-nancy/project.json
3,5c3,5
<         "Kestrel": "1.0.0-alpha4",
<         "Microsoft.AspNet.Owin": "1.0.0-alpha4",
<         "Nancy": "1.0.0"
---
>         "Kestrel": "1.0.0-*",
>         "Microsoft.AspNet.Owin": "1.0.0-alpha2",
>         "Nancy": "0.23.2"
11,12c11,13
<         "aspnet50": {},
<         "aspnetcore50": {}
---
>         "aspnet50": {
>             "System.Runtime": ""
>         }
```

**Comment by jchannon** [comment]
hmm, baffled,

**Comment by joaomoreno** [comment]
I take it back. Both templates have something broken. I cannot run the template generated by [generator-nancy](https://github.com/jchannon/generator-nancy).

```
➜  NancyApp git:(master) k kestrel
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IServiceManifest' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IServiceManifest] (IServiceProvider provider) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Hosting.HostingServices.Import (IServiceProvider fallbackProvider) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Hosting.HostingServices.Create (IServiceProvider fallbackServices, IConfiguration configuration) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
```

**Comment by jchannon** [comment]
what version of kre do you have?

**Comment by joaomoreno** [comment]
```
➜  NancyApp  kvm list

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
  *    1.0.0-beta2          mono    ~/.k/runtimes        default
       1.0.0-beta3-11030    mono    ~/.k/runtimes
```

**Comment by jchannon** [comment]
same as me

**Comment by joaomoreno** [comment]
You don't see any difference when generating from both templates?

**Comment by jchannon** [comment]
Ah I get a failure on kpm build with aspnet generator. Hmmm

**Comment by sayedihashimi** [comment]
I think there may be an issue with the Nancy generator in aspnet. I was thinking to update all templates to work with ```beta3``` once it gets released.

**Comment by peterblazejewicz** [comment]
x-ref: #60 
x-ref: #59 specifically: https://github.com/OmniSharp/generator-aspnet/pull/59#issuecomment-74432931

**Comment by larsw** [comment]
https://github.com/OmniSharp/generator-aspnet/pull/69

Upgraded the MVC, Web and Nancy projects to point at the beta3 bits, but more work has to be done in order to get the generated Nancy projects building (MVC + Web ok).

**Comment by spboyer** [comment]
Nancy templates updated and publish in v 0.0.31, tested and built with beta3

**Comment by peterblazejewicz** [comment]
:clap: does work. It builds, thanks!

**Comment by sayedihashimi** [comment]
Thanks everyone, closing now since its released

**Comment by joaomoreno** [comment]
Verified that I can run (`k kestrel`) and build (`kpm build`) the new release.
