### ISSUE TITLE
Update Docker template for RC2

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#685]
There is no AFAIK updated Docker image for use with dotnet/aspnet under RC2.
The current `microsoft/dotnet` is old and content from RC2 branch won't work on this image:
```
dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```
The template needs to ship with SQLite path (as the current one) in order to allow runing starter web projects out-of-the-box.

**Comment by glennc** [comment]
The microsoft/dotnet images will be updated for RC2. See: https://github.com/dotnet/dotnet-docker/pull/36

**Comment by peterblazejewicz** [comment]
Thanks! Subscribed!

**Comment by spboyer** [comment]
Just did a PR for this.

**Comment by benjoyce** [comment]
I had some issues with this recently.  I'm new to Yeoman and Docker so correct me if I'm wrong, but using "yo aspnet" produces a Dockerfile that doesn't work with RC2.  To get it to work I publish first using "dotnet publish" and then updated my Dockerfile's FROM, RUN and ENTRYPOINT lines.

Here's my Dockerfile:

----- 8< -----
FROM microsoft/dotnet
RUN printf "deb http://ftp.us.debian.org/debian jessie main\n" >> /etc/apt/sources.list
RUN apt-get -qq update && apt-get install -qqy sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]

EXPOSE 5000/tcp
#ENTRYPOINT ["dotnet", "-p", "project.json", "Microsoft.AspNet.Server.Kestrel", "--server.urls", "http://0.0.0.0:5000"]
ENTRYPOINT dotnet bin/Debug/netcoreapp1.0/publish/aspnetcore.dll
#aspnetcore is the name of my test project.

----- >8 -----
Hope this helps someone.
