### ISSUE TITLE
.NET Core RC2 Class Library Project

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#689]
This is a close to final sample for RC2. Attaching the sample below
[ClassLibrary1.zip](https://github.com/OmniSharp/generator-aspnet/files/260037/ClassLibrary1.zip)

.NET CLI
 .NET Command Line Tools (1.0.0-rc2-002673) or higher
 Install Location: https://github.com/dotnet/cli#installers-and-binaries

NuGet Feed
https://www.myget.org/F/aspnetrelease/api/v3/index.json
https://api.nuget.org/v3/index.json

//cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
closed via: bff4701
