### ISSUE TITLE
ASP.NET Core RC2 Empty Web Application

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#691]
This is a close to final sample for RC2. Attaching the sample below:
[EmptyWeb.zip](https://github.com/OmniSharp/generator-aspnet/files/260047/EmptyWeb.zip)

.NET CLI
 .NET Command Line Tools (1.0.0-rc2-002673) or higher
 Install Location: https://github.com/dotnet/cli#installers-and-binaries

NuGet Feed
https://www.myget.org/F/aspnetrelease/api/v3/index.json
https://api.nuget.org/v3/index.json

//cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
The `restore` outpus some failures (false positive) but otherwise the project restore, build and run work fine

**Comment by peterblazejewicz** [comment]
closed via 	bd0d2a5

**Comment by rustd** [comment]
I think this is because you could have multiple feeds or cached packages. This is fine.
