### ISSUE TITLE
Verification of yeoman generators for RC2

### ISSUE THREAD

**Issue by javiercn** [OmniSharp/generator-aspnet#698]
We are doing some verification on the Yeoman generators for the RC2 release of ASP.NET. I'm opening this bug to track all the feedback I collected from the verification process. I did the verification against the master branch on 05/04/2016 using dotnet cli rc2 2611 on an Ubuntu machine. I'll be opening individual bugs for these and put a pointer to those bugs in this issue.

## Empty web application
  * Startup.cs is out of date, UseDefaultHostingConfiguration has to be removed from the template.
  * There are warnings when running dotnet build/run
    ```
    
      Compiling EmptyWebApplication for .NETCoreApp,Version=v1.0
      /home/javier/work/EmptyWebApplication/project.json(44,15): warning DOTNET1015: The 'content' option is deprecated. Use 'publishOptions' to publish or 'copyToOutput' in 'buildOptions' to copy to build output instead.
      /home/javier/work/EmptyWebApplication/project.json(49,15): warning DOTNET1015: The 'exclude' option is deprecated. Use 'exclude' within 'compile' or 'embed' instead.
      /home/javier/work/EmptyWebApplication/project.json(3,26): warning DOTNET1015: The 'compilationOptions' option is deprecated. Use 'buildOptions' instead.
    ```
  * Docker file is out of date.
    ```
    FROM microsoft/aspnet:1.0.0-rc1-update1

    RUN printf "deb http://ftp.us.debian.org/debian jessie main\n" >> /etc/apt/sources.list
    RUN apt-get -qq update && apt-get install -qqy sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*

    COPY . /app
    WORKDIR /app
    RUN ["dnu", "restore"]

    EXPOSE 5000/tcp
    ENTRYPOINT ["dnx", "-p", "project.json", "Microsoft.AspNet.Server.Kestrel", "--server.urls", "http://0.0.0.0:5000"]
    ```
  * README.md on wwwwroot probably should be on the root folder, not on wwwroot. 
  * project.json is out of date and emits warnings on compilation.
  * project.json postpublish script is missing --framework %publish:FullTargetFramework%

## Console Application
 * Could have Console.WriteLine("Hello world") so that people doing dotnet run on the thing know that works.

## Web Application
 * It hasn't been updated to RC2 (I figured out this is in the RC2 branch, i'll do another pass later this week).
## Web Application basic
 * Restore fails
   * dotnet-razor-tooling needs to be replaced with Microsoft.AspNetCore.Razor.Tools
   * The following packages fail to restore (I think this will be resolved when the packages are on nuget)
   ```
   Errors in /home/javier/work/Generators/WebApplicationBasic/project.json
   Unable to resolve 'Microsoft.AspNetCore.Diagnostics (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.AspNetCore.Mvc (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.AspNetCore.StaticFiles (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.Extensions.Configuration.Json (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.Extensions.Logging.Console (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.Extensions.Logging.Debug (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.VisualStudio.Web.BrowserLink.Loader (>= 14.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.AspNetCore.Razor.Tools (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   Unable to resolve 'Microsoft.AspNetCore.Razor.Tools (>= 1.0.0-rc2-20581)' for '.NETCoreApp,Version=v1.0'.
   ```
   * Imports for razor tools should be "portable-net45+wp80+win8+wpa81+dnxcore50" (this might change)
 * Build failures
   *  UseDefaultHostingConfiguration should be removed from Program.cs
   *  project.json is missing a package "Microsoft.Extensions.Configuration.EnvironmentVariables.
   *  Dockerfile needs to be updated.
## Web API application
 * UseDefaultHostingConfiguration needs to be removed.
 * Microsoft.Extensions.Configuration.EnvironmentVariables is missing from project.json
## Class library
 * The comment in Class1.cs is out of date
## Unit test
 * Project is not updated to RC2.

## Sub generators
 * nuget is ok. (I think this shoudld go in the default generated templates, as its useful for configuration).
 * PackageJson is ok, it emits warnings for description, repository and license but there's nothing we can do.
 * AppSettings it's ok.
 * Class is ok
 * .gitignore is ok.
 * Interface is ok.
 * JavaScript is ok.
 * JSON is ok.
 * Middleware it would be nice if the generator can examine the project.json file above it and modify it itself to add any required package. Also, this generator should generate two files, one with the middleware and another one with the extensions so that there is one class per file.
 * MvcController the comment on the template is too much if this template is to be used extensively, its only useful the first time and it becomes litter that needs to be cleaned up after that every time. Also it would be nice if the generator adds the Controller suffix by default if not present. The first time I tried I invoked my generator with yo aspnet:MvcController Home and I ended up with just Home.cs. It would be nice if the generator understands the default convention for MVC.
 * Views looks ok to me, but the comment again seems unnecessary. Maybe all these things can be put together on a file that we add to the default templates? Something like GettingStarted.txt
 * Program is ok.
 * readme is ok.
 * Startup the class should have two methods ConfigureServices(IServiceCollection services) and Configure(IApplicationBuilder app)
 * TagHelper could ask for the tag name to use in the HtmlTargetElement item or infer it from the name given to the file. It will also be nice if the generator finds the project.json file and adds the package dependency to it.
 * tfignore looks ok, but I haven't set up a TFS project to test it.
 * TypeScript is not very useful given that it just produces an empty file, if we are going to do this, for typescript it will be better if we had generators for specific things like classes, interfaces, AMD modules, etc.
 * TypeScriptConfig looks ok.
 * TypeScriptJSX should probably be named TypeScriptTSX to match the extension of TypeScript enabled React JSX files.
 * User secrets looks ok, I ran it twice and the second time it detected that it didn't need to update the project.json file
 * WebApiController looks good, we might want to remove the comment.
  
## Other sub generators
 * Angular generators are not very useful and we probably don't want to have them here. They don't ask for the name of the component you are creating and they infer the name of the module to follow the directory structure which as far as I know it's not a common convention on angular apps.
 * DockerFile generator not updated
 * Gruntfile ok.
 * Gulpfile ok.
 * HTML page ok.
 * JSONSchema ok.
 * JSX ok 
 * StyleSheet ok.
 * StyleSheetLess ok.
 * StyleSheetSCss ok.

## Other issues / high level feedback
* Casing in generators: Different generators (specially subgenerators) use different casing that doesn't obey any specific rule. This makes really hard to use the subgenerators from the command line as names need to be a case sensitive match. It will be way better if all generators are just lowercase.
* Excesive amount of generators. There are two buckets here, generators that create an empty or barely populated file, which don't provide a lot of value given how easy is to create a file from any IDE and generators for other technologies like angularjs or typescript for which there are many other generators that can provide a better experience.

**Comment by peterblazejewicz** [comment]
@javiercn Javier, thanks!
I'll review your points

> I did the verification against the master branch on 05/04/2016

Can you verify the same using `RC2` branch, which is more stable and to-date with aspnet/Templates?

**Comment by peterblazejewicz** [comment]
@javiercn
There are updates to `RC2` merged into `RC2` branch. Also there are two PRs that are WIP and postponed until after `dotnet build` errors are solved.

**Comment by peterblazejewicz** [comment]
@javiercn 
Can I close this? The RC2 branch has been updated with recent bits and tested on `1.0.0-preview1-002702` runtime?
The most important is Dockerfile update pending
Thanks!

**Comment by javiercn** [comment]
Hi,

Sorry for the delay. I'll be doing another final pass on Monday. I'll update this thread after that.

**Comment by sayedihashimi** [comment]
@javiercn let me know what you find out

**Comment by javiercn** [comment]
I did a second pass yesterday. I basically created every project (with every option) and ran restore, build, run, publish, run published bits. Everything worked without issues! (Opened on the browser and everything looked fine).

I'm closing this issue
