### ISSUE TITLE
ASP.NET Core RC2 Web API template final version

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#703]
This is the final version of the template.
[WebAPI.zip](https://github.com/OmniSharp/generator-aspnet/files/263601/WebAPI.zip)

Please use the following feed and CLI

**.NET CLI**
.NET Command Line Tools 1.0.0-preview1-002702
Install Location: https://github.com/dotnet/cli#installers-and-binaries

**NuGet Feed**
https://www.myget.org/F/aspnetrc2/api/v3/index.json
https://api.nuget.org/v3/index.json

**Comment by peterblazejewicz** [comment]
closed via 001d44a
