### ISSUE TITLE
ASP.NET Core RC2 Empty Web template final version

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#704]
[EmptyWebApp.zip](https://github.com/OmniSharp/generator-aspnet/files/263604/EmptyWebApp.zip)

Please use the following feed and CLI

**.NET CLI**
.NET Command Line Tools 1.0.0-preview1-002702
Install Location: https://github.com/dotnet/cli#installers-and-binaries

**NuGet Feed**
https://www.myget.org/F/aspnetrc2/api/v3/index.json
https://api.nuget.org/v3/index.json

**Comment by ardalis** [comment]
Just tested this and got it working. Quick question. Why does the Empty template include "extra" namespaces in files like Program.cs and Startup.cs? Specifically, these four are immediately marked as unused by VS Code when I open both of these files:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

**Comment by rustd** [comment]
We think these are the most common namespaces that developers will use so we add it by default.
https://github.com/aspnet/Templates/issues/565

**Comment by ardalis** [comment]
...and I probably wouldn't complain about that fact, except in the Empty template, which is supposed to be as minimal as possible and without any of the usual "stuff we think developers might want". IMHO.

**Comment by peterblazejewicz** [comment]
Closed via: 	4b75a8e
