### ISSUE TITLE
.NET Core RC2 Class Library template final version

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#705]
[ClassLibrary1.zip](https://github.com/OmniSharp/generator-aspnet/files/263608/ClassLibrary1.zip)

Please use the following feed and CLI

**.NET CLI**
.NET Command Line Tools 1.0.0-preview1-002702
Install Location: https://github.com/dotnet/cli#installers-and-binaries

**NuGet Feed**
https://www.myget.org/F/aspnetrc2/api/v3/index.json
https://api.nuget.org/v3/index.json

**Comment by peterblazejewicz** [comment]
Closed via 395c751
