### ISSUE TITLE
.NET Core RC2 Console App Template final version

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#706]
[ConsoleApp1.zip](https://github.com/OmniSharp/generator-aspnet/files/263610/ConsoleApp1.zip)

Please use the following feed and CLI

**.NET CLI**
.NET Command Line Tools 1.0.0-preview1-002702
Install Location: https://github.com/dotnet/cli#installers-and-binaries

**NuGet Feed**
https://www.myget.org/F/aspnetrc2/api/v3/index.json
https://api.nuget.org/v3/index.json

/cc @sayedihashimi

**Comment by peterblazejewicz** [comment]
Closed via: 5a021ce
