### ISSUE TITLE
Fix typo in ASCII Welcome

### ISSUE THREAD

**Issue by ardalis** [OmniSharp/generator-aspnet#707]
### Short issue description
Marvelous is not spelled correctly

### Expected behavior
Marvelous

### Actual behavior
Marvellous

### Steps to reproduce the behavior
yo aspnet
read initial ASCII welcome

----
#### NodeJS version
```
node --version
```

#### Yeoman version
```
yo --version
```

#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
Actually, that's British invasion artefact (`|ˈɑːtɪfakt| (US artifact)`) 🇬🇧 
```
marvellous |ˈmɑːv(ə)ləs| (US marvelous)
```
This is part of the version of Yo generator uses:
https://github.com/yeoman/generator-generator/blob/aa6cdbad86b2f9cedef06b913cff88f2ee3715da/app/templates/app/index.js#L24
and it will be replaced by configurable option when yo dependency is updated:
https://github.com/yeoman/generator-generator/blob/59f2c8ee711a492bba1b2f68fa1b35f2af6fadf7/subgenerator/templates/index.js#L10

Closing. Thanks!
