### ISSUE TITLE
Generation with rc2 problem.

### ISSUE THREAD

**Issue by Stalso** [OmniSharp/generator-aspnet#725]
### Short issue description
Hello. I have generated project using this generator. Then I have tried to open it in Visual Studio (also I have tried to add it to existing solution in Visual Studio). In both this options I have the same issue:

![issue](https://cloud.githubusercontent.com/assets/6276096/15314852/fd9dc8d0-1c1c-11e6-800e-7eb86042428d.png)

What I am doing wrong? RC2 projects, generated by Visual Studio are working fine

**Comment by peterblazejewicz** [comment]
See similar: https://github.com/aspnet/Tooling/issues/480
This can be VSTooling problem
/cc @sayedihashimi
