### ISSUE TITLE
"dotnet run" not working

### ISSUE THREAD

**Issue by asadsahi** [OmniSharp/generator-aspnet#726]
`dotnet run` ends up in following description:

```
Expect required library hostpolicy.dll to be present in [C:\Users\asahi\aspnet-rc2\bin\Debug\netcoreapp1.0]
  - This may be because of an invalid .NET Core FX configuration in the director
y.

```

![image](https://cloud.githubusercontent.com/assets/3470892/15320123/c5e2302a-1c26-11e6-8571-dbeef8043d57.png)

**Comment by peterblazejewicz** [comment]
@asadsahi 
That's `cli` tool issue, not `generator` I think:
https://github.com/dotnet/cli/issues/2859
Thanks!

**Comment by frapid** [comment]
Is there any solution for this?

**Comment by sayedihashimi** [comment]
For follow up https://github.com/dotnet/cli/issues/2859
