### ISSUE TITLE
Bundler introduction for RTM release

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#733]
@sayedihashimi @rustd
I'm writing a PR with changes from https://github.com/aspnet/Templates/pull/592
Before I rewrite all files (there are tests, grunt/gulp options), am I correct doing this? I assume folks in MS are aware of consequence of removing NPM support and using in-house solution (bundler). 
I'll let you know how bundler works on x-plat (for now OS X)

**Comment by sayedihashimi** [comment]
Having gulp/npm in templates by default has caused some issues with users. We are going to simply that. It should work xplat it you find any issues let me know.
BTW @rustd moved on to work in some other areas. I own VS ASP.NET and .NET Core templates now.

**Comment by sayedihashimi** [comment]
For users who do want gulp it should be easy to add.

**Comment by peterblazejewicz** [comment]
Sayed, thanks! (I know you're busy). Can't run this on OS X:
https://github.com/aspnet/Templates/pull/592#issuecomment-224387087

**Comment by peterblazejewicz** [comment]
https://github.com/madskristensen/BundlerMinifier/issues/130

**Comment by sayedihashimi** [comment]
Thanks, we are investigating.

**Comment by peterblazejewicz** [comment]
It seems to be fixed with update 2.0.208 version. I'll go ahead with Bundler related changes.
I'll review old topic of including `.vscode` configuration with templates, it could be useful after removing Gulp/Grunt tasks - some kind of task support should be shipped with projects.
Thanks!
