### ISSUE TITLE
Update Nancy templates for beta3

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#74]
The Nancy templates were [removed](8762f105faf017d8e99fa9b8bd9e74c90dc04cbe) because it was not building/running under beta 3. Can we get the Nancy templates updated to the latest?

cc @jchannon @larsw @spboyer

**Comment by larsw** [comment]
I'll look into it.

Your "removed" link (https://github.com/OmniSharp/generator-aspnet/issues/8762f105faf017d8e99fa9b8bd9e74c90dc04cbe) returns 404 by the way.

**Comment by larsw** [comment]
This should do the trick. https://github.com/OmniSharp/generator-aspnet/pull/77

**Comment by jchannon** [comment]
Nice one!

**Comment by spboyer** [comment]
Closed with https://github.com/OmniSharp/generator-aspnet/pull/77
