### ISSUE TITLE
change aspnet 5 to core on the repo title

### ISSUE THREAD

**Issue by lcssk8board** [OmniSharp/generator-aspnet#747]
Completely minor priority change but, this is indexed by google and some people can just get out thinking that this repo isnt updated or maintained regularly.

Sorry for do not follow the guidelines but maybe don't fit with this type of issue.

**Comment by peterblazejewicz** [comment]
cc/
@sayedihashimi

**Comment by scottaddie** [comment]
@peterblazejewicz @sayedihashimi Any updates on this? I think it's important that people don't associate ASP.NET 5 with the ASP.NET Core projects being scaffolded by this generator. It will only add to the confusion.

**Comment by sayedihashimi** [comment]
Thanks for letting us know about this. I've fixed it. Let me know if there are any other similar updates required. Closing now.
