### ISSUE TITLE
Update unit test template for beta3

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#75]
The unit test template [removed](8762f105faf017d8e99fa9b8bd9e74c90dc04cbe) because it was not building/running under beta 3. We should update to use the latest beta3 packages and the latest xunit packages (_the packages have moved from what we were using before_).

@suhasj can I assign this item to you?

**Comment by larsw** [comment]
Consider it done: https://github.com/OmniSharp/generator-aspnet/pull/78

**Comment by sayedihashimi** [comment]
Replaced with #165
