### ISSUE TITLE
Name inconsistencies (PascalCasing vs all lower)

### ISSUE THREAD

**Issue by HaoK** [OmniSharp/generator-aspnet#755]
### Short issue description
Currently the names are not consistent in their casing, and since the commands are case sensitive this is a bit awkward.  We should pick one style to use everywhere.

They currently are:
```
AngularController
AngularControllerAs
AngularDirective
AngularFactory
AngularModule
AppSettings
BowerJson
Class
CoffeeScript
Dockerfile
gitignore
Gruntfile
Gulpfile
HTMLPage
Interface
JavaScript
JSON
JSONSchema
JSX
Middleware
MvcController
MvcView
nuget
PackageJson
Program
readme
Startup
StyleSheet
StyleSheetLess
StyleSheetSCSS
TagHelper
TextFile
tfignore
TypeScript
TypeScriptConfig
TypeScriptJSX
UserSecrets
WebApiController
```

**Comment by peterblazejewicz** [comment]
There is a lot of authors of these subgenerators :). I'm used to all lower case (like: https://github.com/yeoman/generator-angular or https://cli.angular.io/)

The generator should go all lower case probably as `dotnet new {something}` will probably also be lower case - just guessing.

**Comment by peterblazejewicz** [comment]
`dotnet` CLI tool docs: https://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-new.html

**Comment by sayedihashimi** [comment]
I like the all lowercase here. For yo aspnet in this particular case it's important to be consistent with other yo generators.
For dotnet new I'll bring this up for discussion. I'm thinking it will be case-insensitive and docs should use lowercase but I'll need to discuss with some others.

**Comment by Spinarooni** [comment]
Would we want to change the casing in the template file also or just the command name?
