### ISSUE TITLE
Web templates: replace EntityFrameworkCore.SQLite with a "real" database provider 

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/generator-aspnet#759]
The web templates currently use Microsoft.EntityFrameworkCore.Sqlite as the default provider. Although using this provider has the benefit of working out-of-box for most platforms, SQLite is not well-suited to back a website. Consider replacing this with MSSQL, Postgres, or MySQL instead.

Or, better yet, make the database-provider an option as a part of the templating prompts.

What should be the default EF Core database provider in **web site templates**?

Use "reactions" to vote: (just once please)

:heart: SQLite  (Microsoft.EntityFrameworkCore.Sqlite)
:tada: Microsoft SQL Server (Microsoft.EntityFrameworkCore.SqlServer)
:smile: PostgreSQL  (Npgsql.EntityFrameworkCore.PostgreSQL)
:confused: MySQL (Not available yet...but "coming soon")
:+1: No default - make this a yeoman prompt

**Comment by sayedihashimi** [comment]
I'm interested to see what the community thoughts are here. I haven't heard any complaints thus far but maybe it's still early foe that.

**Comment by peterblazejewicz** [comment]
That's broader problem. How one will promote and evangelize platform easily (dotnet core) without going into details of different deps and all that mess:
https://github.com/aspnet/EntityFramework/issues/5659#issuecomment-223843043
https://github.com/aspnet/EntityFramework/issues/5682
https://github.com/aspnet/EntityFramework/issues/4863
The beauty of SQLite is that is used everywhere including small, embedded devices. We could write a small dotnet app runnable everywhere without external requirement (local or remote db server).

When MS SQL for Linux is out of the private beta, that would be better choice - as I assume EF will support it out of the box (assuming content I've seen on Linux early beta preview on Channel 9, sorry, the link was in the email about beta status I've already trashed).
Thanks!

**Comment by natemcmaster** [comment]
Perhaps we can make this simpler.

What should be the default EF Core database provider in **web site templates**?

Use "reactions" to vote:

:heart: SQLite  (Microsoft.EntityFrameworkCore.Sqlite)
:tada: Microsoft SQL Server (Microsoft.EntityFrameworkCore.SqlServer)
:smile: PostgreSQL  (Npgsql.EntityFrameworkCore.PostgreSQL)
:confused: MySQL (Not available yet...but "coming soon")
:+1: No default - make this a yeoman prompt

**Comment by natemcmaster** [comment]
Side note: @peterblazejewicz EF Core already works with MSSQL on Linux. Apply for the private beta if you'd like to try it. http://sqlserverforlinux.com/

**Comment by peterblazejewicz** [comment]
> Apply for the private beta if you'd like to try it

I'm already in beta - but on wait list (while filling apply form I'be mentioned that I'd want to try Unix version specifically for the purpose of this project :) )

**Comment by spboyer** [comment]
:+1:

**Comment by Kagamine** [comment]
There is an open sourced and free mysql provider for ef core now: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by DeathArrow01** [comment]
See: https://github.com/OmniSharp/generator-aspnet/issues/806

PostgreSQL works on all major platforms: Windows, Linux, Mac, also ef core and tooling supports the npgsql core driver. 

I've just used aspnet generator to generate an Web Aplication project, replaced the SQLite connection string with proper Postgres connection string, removed SQlite packages, added packages for Postgres, modified the DBContext, and I had the site up and running. I also tested ef migrations and they work.

**Comment by Tanato** [comment]
@natemcmaster Turns out that SQLite suits very well for most (small and medium) websites and web applications. I know it's not intuitive and I was skeptical when I began using it in my personal projects.

In the end, as there are so many options of database engines and choosing only one will never satisfy everyone needs I think that keeping the SQLite as default bring more benefits than problems.

And If you are building a big project that really needs a powerful DB engine, changing the project to use another one is about 2 lines of code, thats not a burden in the end.

From [SQLite documentation](https://www.sqlite.org/whentouse.html ):

> SQLite works great as the database engine for most low to medium traffic websites (which is to say, most websites). The amount of web traffic that SQLite can handle depends on how heavily the website uses its database. Generally speaking, any site that gets fewer than 100K hits/day should work fine with SQLite. The 100K hits/day figure is a conservative estimate, not a hard upper bound. SQLite has been demonstrated to work with 10 times that amount of traffic.

**Comment by jahead** [comment]
Why not add the ability to choose your db driver like there is for UI Framework?

**Comment by spboyer** [comment]
@jahead probably will be an option when the conversion is complete to use the new template system. Currently in `dotnet new` you can select an option for the DB for the `mvc` template. As new templates are developed, someone could give you the option as well for a specific driver

```bash
 -uld|--use-local-db  Whether or not to use LocalDB instead of SQLite
                       bool - Optional
                       Default: false
```

i.e. `dotnet new mvc -uld true`

**Comment by jahead** [comment]
Oh okay, for our use case we are still using Sql Server, but it's not too hard for us to modify it post generation.

**Comment by natemcmaster** [comment]
ASP.NET Core web templates moved to github.com/aspnet/templating, and include some options for controlling the type of database used in a new project.
