### ISSUE TITLE
Blog post on update for beta 3

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#76]
Now that we have updated the generators for ```beta3``` we should write a blog post announcing the updates and post it on the [official ASP.NET team blog](http://blogs.msdn.com/b/webdev/).

I'd like to give @spboyer the first chance to be the author on that since he was the main contributor for the updates. If he is not interested then I'd like to see if anyone else is.

**Comment by spboyer** [comment]
I have already started a post. I'll send it over to you when it's completed.

**Comment by spboyer** [comment]
submitted.

**Comment by sayedihashimi** [comment]
OK I have reviewed and tried to publish, but for some reason I can not publish any longer. I think there is some issue on my side.

I've asked Jeff Fritz if he can help me get it posted. I'll keep you posted.

**Comment by sayedihashimi** [comment]
It's been posted http://blogs.msdn.com/b/webdev/archive/2015/02/28/asp-net-yeoman-generators-for-beta-3.aspx

**Comment by peterblazejewicz** [comment]
a way better now :D
