### ISSUE TITLE
Support for F# Projects

### ISSUE THREAD

**Issue by rogersachan** [OmniSharp/generator-aspnet#785]
Is there a hidden way to create a F# project, if not please add F# support soon!

**Comment by peterblazejewicz** [comment]
Do F# community have kind of templates like aspnet/Templates projecto or xUnit:
https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by rogersachan** [comment]
They have their own generator at: https://github.com/fsprojects/generator-fsharp

I'm not sure which parts are (still) functional in .NET Core, but I assumed that since ASP.NET MVC was built on F#  we had that functionality by now.

Starting a F# project in .NET Core just takes `dotnet new --lang f#` and a few minutes to install dependencies.

**Comment by peterblazejewicz** [comment]
That generator does not seem to support dotnet. Maybe just F# command line project from this one:
https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-new/FSharp_Console

**Comment by rogersachan** [comment]
I think it would be best just to support F# console projects for right now.

**Comment by sayedihashimi** [comment]
>I think it would be best just to support F# console projects for right now.

I disagree, if we are to consider adding F# it should apply across the board for all relevant project types.

**Comment by sayedihashimi** [comment]
Sorry clicked the wrong button and closed it, reopened.

**Comment by rogersachan** [comment]
The problem is that it is only in ASP.NET MVC Core and once again, console projects. There's not much to choose from and should be a somewhat easy implementation

**Comment by sayedihashimi** [comment]
Sorry maybe I've misunderstood. Wouldn't an F# option be applicable to all templates we have here?

**Comment by sayedihashimi** [comment]
@cartermp is looking at F# support and IIRC it does apply to web templates. @cartermp what should F# templates look like for `yo aspnet`?

**Comment by cartermp** [comment]
Currently we have F# console and library templates about to be checked into the CLI here: https://github.com/dotnet/cli/pull/3789

Any `yo aspnet` templates that do just a class library or console app can have the F# equivalents as well.

There is no support for F# as the language to write the actual ASP.NET app right now, although *technically* you can write code which reads and writes to the request/response streams.  Since ASP.NET Core is just a .NET Core console app, it would all work.  But that's a raw experience that we probably wouldn't want a template for.

**Comment by rogersachan** [comment]
Templates were just checked in recently. Any updates?

**Comment by sayedihashimi** [comment]
I'm supportive of adding F# as an option if we have a community member who is willing and committed to keeping them updated. With each release of .net core the templates need to be updated before release day.

**Comment by odytrice** [comment]
What would it take to add F# support? looking at the code, I'm thinking that I would have to split each template into csharp and fsharp folders right?

**Comment by peterblazejewicz** [comment]
@odytrice 
1) get a copy of F# lib template from dotnet cli (as aspnet/Templates does not ship an F# template:
https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-new/FSharp_Console
2) create `fsharp` directory within `projects`: https://github.com/OmniSharp/generator-aspnet/tree/master/templates/projects
3) copy files as to this new directory
4) add tests to core tests: https://github.com/OmniSharp/generator-aspnet/blob/master/test/test-core.js for `fsharp` option
5) add documentation for F# sharp project to project README.md
6) repeat above for `F# Console` project

You could use `Class Library` and 'Console Project' project as guide as it comes with the similar content:
https://github.com/OmniSharp/generator-aspnet/tree/master/templates/projects/

> You need to remember about copying `.gitignore` - as `.gitignore` is not included as template file in the project.

This assumes that you would create two different project templates: `F# Console` and `F# Library` as in `dotnet new` command.

Thanks!

**Comment by odytrice** [comment]
Thanks, will do

**Comment by odytrice** [comment]
I've been able to do the Console and Class Library Templates. Soon, I'll be able to add the Web Templates
