### ISSUE TITLE
Initial scaffolding will not build / restore

### ISSUE THREAD

**Issue by jackjwilliams** [OmniSharp/generator-aspnet#790]
### Short issue description
When doing a new, yo aspnet using bootstrap (or semantic-ui), then opening in VS, or VS Code, or dotnet restore / build CLI, I get a bunch of errors.

Just installed Visual Studio Update 3, installed cli RC2 before that.

### Expected behavior
Project should build and run fine

### Actual behavior
Error in visual studio upon restore:

`project.json(0,0): Error: Microsoft.Dnx.Runtime.FileFormatException: unknown keyword platform ---> System.InvalidOperationException: unknown keyword platform`

Error in CLI on dotnet restore:

`error: Package Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003121 supports: netstandard1.6 (.NETStandard,Version=v1.6)`

... Followed by a bunch of others

### Steps to reproduce the behavior
Install latest .NET Core CLI / SDK
Install VS 2015 Update 3

yo aspnet

----
#### OS version (Win/Mac/\*Nix?)
Windows 10

#### NodeJS version
```
v5.1.1
```

#### Yeoman version
```
1.7.7
```

#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet = 0.0.92
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

Is there something I am missing to get this going?

I'm also using an npm link from master since I worked on the semantic-ui portion (pulling latest, of course).

**Comment by jackjwilliams** [comment]
If anyone else is wondering, simply installing the latest CLI did not work for me (the old RC2 was still showing in Programs). I had to uninstall RC2 CLI, and re-install the latest (preview3). Now all is right with the world.

**Comment by peterblazejewicz** [comment]
Thanks for info!
