### ISSUE TITLE
Building docker image for aspnet website application template failes with "do you want to continue?" question

### ISSUE THREAD

**Issue by guybartal** [OmniSharp/generator-aspnet#793]
### Short issue description

Building docker image for aspnet website application template results "do you want to continue?" confirm message on apt-get install and break RUN step
### Expected behavior

build completed successfully
### Actual behavior

RUN step failure
### Steps to reproduce the behavior

docker build -t <your alias>/dotnet .

---
#### OS version (Win/Mac/*Nix?)

Win
#### NodeJS version

```
node --version
```

4.4.7
#### Yeoman version

```
yo --version
```

1.8.4
#### Generator version

NPM 3.*:

```
npm list -g generator-aspnet
```

NPM 2.*:

```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
@guybartal Thanks! I think this was fixed by this commit but not yet landed in NPM release:
https://github.com/OmniSharp/generator-aspnet/commit/68c6e0c9bc205fb99b56bbd894d38089b0f8ed90
Can you verify with this content for Dockerfile:
```
FROM microsoft/dotnet:latest

RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore"]

RUN ["dotnet", "build"]

RUN ["dotnet", "ef", "database", "update"]

EXPOSE 5000/tcp

ENTRYPOINT ["dotnet", "run", "--server.urls", "http://0.0.0.0:5000"]
```

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
