### ISSUE TITLE
Can I choose other database type?

### ISSUE THREAD

**Issue by Denzeen** [OmniSharp/generator-aspnet#795]
### Short issue description

Now it only support sqllite，but i want to use mssqlserver.
### Steps to reproduce the behavior

---
#### NodeJS version

```
node --version
```
#### Yeoman version

```
yo --version
```
#### Generator version

NPM 3.*:

```
npm list -g generator-aspnet
```

NPM 2.*:

```
npm ls generator-aspnet -ls=0 --long
```

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
