### ISSUE TITLE
Update Bootstrap dependencies

### ISSUE THREAD

**Issue by ArgTang** [OmniSharp/generator-aspnet#798]
### Short issue description

Bootstrap updated to 3.3.7 with support for jQuery 3.1.0
http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/
### Expected behavior

aspnet generator is setup with bootstrap 3.3.7and Jquery 3.1.0

**Comment by peterblazejewicz** [comment]
This should be first tested for compatibility:
https://github.com/jzaefferer/jquery-validation/issues/1813
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryexpr-is-jqueryexprpseudos
and then cross-posted to aspnet/Templates

**Comment by ArgTang** [comment]
Bootstrap

**Comment by peterblazejewicz** [comment]
Update when jquery-validation updated version is shipped. The 3.3.7 is the last version to be released, considered stable:
https://github.com/twbs/bootstrap/issues/20631#issue-175132021
The next will be version 4

**Comment by ArgTang** [comment]
https://github.com/jzaefferer/jquery-validation/issues/1866

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
