### ISSUE TITLE
Any sub-generator to generate a model class?

### ISSUE THREAD

**Issue by zh-wowtv** [OmniSharp/generator-aspnet#803]
I didn't find any. 

Any suggestion? Thanks.

**Comment by peterblazejewicz** [comment]
No, there is no one. There is no default one in VS templates if I recon correctly from my VS2015 at work (I always use Class template)

**Comment by zh-wowtv** [comment]
@peterblazejewicz You're right. There is no default one in VS2015. But do you think it's worth adding it. I know adding the code manually is not difficult at all?

**Comment by zh-wowtv** [comment]
@peterblazejewicz I found when I create a class, VS2015 will generate a Model class for me. I'm wondering it's still a good idea to add it in aspnet generator.
