### ISSUE TITLE
can't find module ./lodash

### ISSUE THREAD

**Issue by hamxabaig** [OmniSharp/generator-aspnet#805]
### Short issue description
When i successfully install generator-aspnet and try to run it by doing `yo aspnet` it gives me error that it can't find ./lodash

### Expected behavior
It should run fine.

### Steps to reproduce the behavior
Install it on mac el capitan 10.11.6

----
#### OS version (Win/Mac/\*Nix?)
el capitan 10.11.6 (mac)

#### NodeJS version
```
node --version
```
4.4.7

#### Yeoman version
```
yo --version
1.8.4
```

#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet
0.2.1
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long

generator-aspnet@0.2.1 
    Yeoman generator for ASP.NET Core apps
    git+https://github.com/omnisharp/generator-aspnet.git
    https://github.com/omnisharp/generator-aspnet#readm
```

**Comment by peterblazejewicz** [comment]
The generator directly does not depends on Lodash. Can you post all output from the console?

**Comment by hamxabaig** [comment]
@peterblazejewicz thanks for replying. I'm posting a output from Console.

```
Hamzas-MacBook-Pro:ASP.NET Projects bogi$ yo aspnet
module.js:327
    throw err;
    ^

Error: Cannot find module './lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bogi/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/lodash/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
Hamzas-MacBook-Pro:ASP.NET Projects bogi$ 


```

**Comment by peterblazejewicz** [comment]
When you run `npm list -g` you should see your global tree of NPM modules under NPM 3.
Somewhere within the tree you should see `yeoman-environment` leaf and it should list loads. Copied from my setup:
```
─┬ yeoman-environment@1.6.3
│ │ │ ├── diff@2.2.3
│ │ │ ├─┬ globby@4.1.0
│ │ │ │ ├── array-union@1.0.2
│ │ │ │ ├── arrify@1.0.1
│ │ │ │ ├── glob@6.0.4
│ │ │ │ ├── object-assign@4.1.0
│ │ │ │ └── pify@2.3.0
│ │ │ ├── grouped-queue@0.3.2
│ │ │ ├─┬ inquirer@1.1.2
│ │ │ │ ├── ansi-escapes@1.4.0
│ │ │ │ ├─┬ cli-cursor@1.0.2
│ │ │ │ │ └─┬ restore-cursor@1.0.1
│ │ │ │ │   └── exit-hook@1.1.1
│ │ │ │ ├── cli-width@2.1.0
│ │ │ │ ├─┬ external-editor@1.0.3
│ │ │ │ │ ├─┬ spawn-sync@1.0.15
│ │ │ │ │ │ └── os-shim@0.1.3
│ │ │ │ │ └─┬ temp@0.8.3
│ │ │ │ │   ├── os-tmpdir@1.0.1
│ │ │ │ │   └── rimraf@2.2.8
│ │ │ │ ├── mute-stream@0.0.6
│ │ │ │ ├─┬ run-async@2.2.0
│ │ │ │ │ └── is-promise@2.1.0
│ │ │ │ └── rx@4.1.0
│ │ │ ├── lodash@4.14.0
```
If it is missing in the output you will need to reinstall. Just `npm cache clean` and reinstall `yo` and `generator-aspnet`. Hope this will fix problem.

**Comment by hamxabaig** [comment]
@peterblazejewicz 
thanks but i have the following output.. looks same
```
┬ yeoman-environment@1.6.3
  │ ├── diff@2.2.3
  │ ├─┬ globby@4.1.0
  │ │ ├─┬ array-union@1.0.2
  │ │ │ └── array-uniq@1.0.3
  │ │ └─┬ glob@6.0.4
  │ │   ├── inflight@1.0.5
  │ │   └── path-is-absolute@1.0.0
  │ ├── grouped-queue@0.3.2
  │ ├─┬ inquirer@1.1.2
  │ │ ├── cli-width@2.1.0
  │ │ ├── mute-stream@0.0.6
  │ │ └── run-async@2.2.0
  │ ├── lodash@4.14.1
  │ ├─┬ mem-fs@1.1.3
  │ │ ├─┬ through2@2.0.1
  │ │ │ ├── readable-stream@2.0.6
  │ │ │ └── xtend@4.0.1
  │ │ ├─┬ vinyl@1.2.0
  │ │ │ ├── clone@1.0.2
  │ │ │ ├── clone-stats@0.0.1
  │ │ │ └── replace-ext@0.0.1
  │ │ └─┬ vinyl-file@2.0.0
  │ │   └─┬ strip-bom-stream@2.0.0
  │ │     └── first-chunk-stream@2.0.0
  │ ├── text-table@0.2.0
  │ └── untildify@2.1.0

```

**Comment by hamxabaig** [comment]
@peterblazejewicz does it have to do anything with NodeJS version? I'm using `v4.4.7`!

**Comment by peterblazejewicz** [comment]
Doubt this as I have the same 'node --version > v4.4.7' (I always use LTS)

**Comment by hamxabaig** [comment]
Do you think there are some alternatives for creating Projects?

**Comment by peterblazejewicz** [comment]
https://github.com/aspnet/cli-samples and:
```
dotnet new --help
.NET Initializer

Usage: dotnet new [options]

Options:
  -h|--help             Show help information
  -l|--lang <LANGUAGE>  Language of project [C#|F#]
  -t|--type <TYPE>      Type of project
```
https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-new

**Comment by hamxabaig** [comment]
I solved it by going to this directory 
`/Users/bogi/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/gruntfile-editor/`
deleting the `node_modules` folder and then typing `npm install` after that it complained that i don't have `gulpfile.js` so I went to github repo of `gruntfile-editor` module and copied pasted the `gulpfile.js`
Ran `npm install` again and voila it worked!
