### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by DeathArrow01** [OmniSharp/generator-aspnet#806]
### It would be nice to add support for PostGreSQL, see: https://andrewlock.net/adding-ef-core-to-a-project-on-os-x and https://damienbod.com/2016/01/11/asp-net-5-with-postgresql-and-entity-framework-7/

All tools needed to make it happen do exist and work. It would be nice to add PostgreSQl support so we can use this generator on linux and Mac and do useful things.

**Comment by DeathArrow01** [comment]
Forked, it, hacked it, it works. Finally I can have an ASP.NET Core MVC project generator with proper database support. Thanks Omnisharp, I just hacked some stuff, you've did all the important work.

If anybody is interested, here it is: https://github.com/DeathArrow01/generator-aspnetpostgresql

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
