### ISSUE TITLE
Implement proper generator run loop

### ISSUE THREAD

**Issue by DarqueWarrior** [OmniSharp/generator-aspnet#808]
### Short issue description

I was trying to extend this generator using composeWith but you don't prompt during the prompting priority explained [here](http://yeoman.io/authoring/running-context.html).
### Expected behavior

I wanted to add my prompts after yours. However, the prompting priority is executed before the default priority where your askFor function is called. This causes my prompts to come first.
### Steps to reproduce the behavior

Create new generator and during initializing add

```
this.composeWith('aspnet');
this.composeWith('my-generator:sub-generator');
```

Your sub-generator prompts will be shown before those of aspnet.

---
#### OS version (Win/Mac/*Nix?)

Windows 10
#### NodeJS version

```
v6.4.0
```
#### Yeoman version

```
1.8.4
```
#### Generator version

NPM 3.*:

```
generator-aspnet@0.2.1
```

NPM 2.*:

```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
@DarqueWarrior Yes, the project was not written for composition during its life. Hence use of non-standard (that is not Yeoman advised names for methods and their visibility). Do you have a source of that other generator somewhere so folks could try?
Thanks!

**Comment by DarqueWarrior** [comment]
I was building my other generator when I noticed this so it is not complete. Trying to figure out a work around now.

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
