### ISSUE TITLE
Please make it support Angular 2

### ISSUE THREAD

**Issue by lednhatkhanh** [OmniSharp/generator-aspnet#809]
Asp.Net core is great and Angular 2 is great, too. But to install Angular 2 into Asp.Net core is a nightmare! So please make this generator support angular 2.

**Comment by spboyer** [comment]
There are some new templates coming in the near future. In the meantime checkout `generator-aspnetcore-spa` the walkthrough is here: http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/
