### ISSUE TITLE
Add options to bypass question of template type

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/generator-aspnet#81]
Generator should have an option to bypass the `type` questions 

`--web` - Web template
`--webapi` - Web API template
`--empty` - Empty template
`--nancy` - Nancy template
`--console` - Console template
`--classlib` - Class Library template

Usage would the allow for CLI to pass name and option of the type i.e. 
`yo aspnet [name] --[type]`

**Comment by peterblazejewicz** [comment]
Maybe this can be delegated (and refactored) into SubGenerators? `aspnet:Web`, `aspnet:WebApi` as in current convetion, etc?

**Comment by peterblazejewicz** [comment]
The #555 PR covers this
