### ISSUE TITLE
Migrate project name module to use `to-pascal-case` NPM module

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#812]
Widely used, e.g. in some of MS projects (JavaScriptServices):
https://www.npmjs.com/package/to-pascal-case

The project is now using custom-provided module.

Thanks!

**Comment by Spinarooni** [comment]
@peterblazejewicz The current solution covers scenarios such as names with a leading number or when it contains "special" characters.  I think the custom module was written to mimic how Visual Studio sanitizes project names so switching is going to lose some of that functionality.

**Comment by peterblazejewicz** [comment]
> as names with a leading number

This is not a case in C# I think. But otherwise you're correct I think
https://msdn.microsoft.com/en-us/library/aa664670(VS.71).aspx
Let this hang for a while, thanks for input!
