### ISSUE TITLE
Upgrade project templates to .NET Core 1.0.1

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#817]
### Short issue description

Now that .NET Core 1.0.1 has been released and [.NET Core 1.0.1 - VS 2015 Tooling Preview 2](https://www.microsoft.com/net/download#tools) is available, these project templates should match what VS 2015 generates.
### Expected behavior

The `project.json` file in each project template should explicitly target .NET Core 1.0.1.
### Actual behavior

The `'project.json` file in each project template is targeting .NET Core 1.0.0.
### Steps to reproduce the behavior
1. `yo aspnet`
2. Scaffold any of the project types.
3. Open the `project.json` file and look in its `dependencies` section. You'll see the following:

``` json
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
```

---
#### OS version (Win/Mac/*Nix?)

Win 10
#### NodeJS version

```
node --version
```

4.5.0
#### Yeoman version

```
yo --version
```

1.8.5
#### Generator version

NPM 3.*:

```
npm list -g generator-aspnet
```

NPM 2.*:

```
npm ls generator-aspnet -ls=0 --long
```

0.2.2

**Comment by sayedihashimi** [comment]
@phenning @balachir any other updates needed to match what we have recently released?

Once we get the content exactly the same I can rerelease

**Comment by peterblazejewicz** [comment]
> @phenning @balachir any other updates needed to match what we have recently released?
> 
> Once we get the content exactly the same I can rerelease

Folks, just let us know which branch now (and commit) is now sync point for 1.0.1 and MS Tooling.
Thanks!

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
