### ISSUE TITLE
Templated Project JSON contains comments...

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/generator-aspnet#82]
... Which apparently aren't valid for JSON docs...
http://stackoverflow.com/a/4183018/23300

https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/webapi/project.json

This manifests itself as an issue with certain JSON deserializers which will fail to decode them. Specifically, trying to edit a newly created aspnet project with Omnisharp-sublime will fail:

```
File "./json/decoder.py", line 176, in JSONObject
ValueError: Expecting property name enclosed in double quotes: line 2 column 5 (char 6)
```

Stripping the comments from project.json, and then everything works fine.

Reported by @Martin105  on jabbr!

**Comment by sayedihashimi** [comment]
Ok well the larger problem is that VS templates include comments as well. Should we remove those as well?

cc @rustd @madskristensen

**Comment by peterblazejewicz** [comment]
Maybe tooling in VS strips comments before JSON is used? That's common solution, e.g.:
https://github.com/sindresorhus/strip-json-comments

**Comment by ctolkien** [comment]
VS will already handle JSON with comments, so I don't think that's the issue, it's more if you're roundtripping with other editors which don't (or developers on other editors). 

I'm in two minds, on the one hand, it's against the spec, on the other, comments are genuinely useful and the only editor that seems to choke right now is Sublime, so a workaround could be employed for that.

My current leaning is if JSON is going to be the project format, then it should be valid JSON.

**Comment by spboyer** [comment]
PR #83 addresses the templates with comments in the project.json files
