### ISSUE TITLE
Is there a way to specify target framework version during generation?

### ISSUE THREAD

**Issue by foragerr** [OmniSharp/generator-aspnet#820]
### Short issue description
#817 changes .netcore framework version for the generated project to 1.0.1, is there a way to specify that I want to generate a project that targets a different framework version, say 1.0.0?

### Expected behavior
Generates project targeting framework version 1.0.0

### Actual behavior
Generates project targeting framework version 1.0.1

### Steps to reproduce the behavior
`yo aspnet`

----
#### OS version (Win/Mac/\*Nix?)
Mac - the official .net core installer currently installs framework version 1.0.0

**Comment by sayedihashimi** [comment]
I think it would be better to use different versions of generator-aspnet to achieve this. Even Visual Studio doesn't offer avenues to invoke older templates.

**Comment by foragerr** [comment]
That would work, I could go to `generator-aspnet@0.2.2`, but wouldn't I miss out on the changes since?

**Comment by sayedihashimi** [comment]
>but wouldn't I miss out on the changes since?

Yes. In this case I think most changes were just package versions. In other cases when changes are more broad then there's no guarantee old packages will work with new template content.

**Comment by peterblazejewicz** [comment]
@foragerr You should be able to see Dotnet core warning. I've mentioned that problem when accepting PR:
https://github.com/OmniSharp/generator-aspnet/pull/818#issuecomment-249260189
Just downgrade your package version to `1.0.0`. You could have both 1.0.0 and 1.0.1 on the same machine btw, as described in article linked in my comment.
Thanks!

**Comment by foragerr** [comment]
ok, I'll stick with manually changing package version for now.

Thank you!
