### ISSUE TITLE
Bundleconfig and Sass

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/generator-aspnet#823]
I just generated a project and I see there is a bundleconfig.json to concat and minify files. Does this support Sass? When I deploy to azure do I need to source control the compiled css files or will it compile my sass for me? Thanks

**Comment by peterblazejewicz** [comment]
The bundle minifier does exactly what its name suggests. It does not compile Less or Sass.
See project issues: BundlerMinifier#93
The solution is to create e.g. Gulp file to manage resources and use their guide to use existing bundle config file with other tasks:
https://github.com/madskristensen/BundlerMinifier/wiki/Use-from-Gulp

**Comment by jrock2004** [comment]
Ah ok, so this solution is not a replacement for gulp, at least not now

**Comment by peterblazejewicz** [comment]
Yes, it was added to limit number of tools and solutions required to build an web app. You could vote for Sass/Less: madskristensen/BundlerMinifier#93

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
