### ISSUE TITLE
Generating solution file with generator used by Omnisharp (ST 3)

### ISSUE THREAD

**Issue by PeterBocan** [OmniSharp/generator-aspnet#830]
### Short issue description

Missing solution file for Omnisharp (Sublime Text 3)
### Expected behavior

I assume the workflow is generating a project using this generator and open it within Sublime.
### Actual behavior

After generating project I have to create sublime project manually (and that's okay) but reading the docs of Omnisharp, it requires solution file, which is not generated. 
### Steps to reproduce the behavior

Generate project, try to use it with Sublime. 

---
#### OS version (Win/Mac/*Nix?)

Using macOS Sierra (10.12).
#### NodeJS version

```
v4.4.1
```
#### Yeoman version

```
1.8.4
```
#### Generator version

```
0.2.1
```

**Comment by PeterBocan** [comment]
I am not sure which side is broken, but the workflow is broken... if it's Omnisharp plugin for ST3, or generator, or docs.

**Comment by peterblazejewicz** [comment]
@PeterBocan 
There are no solution/project related files in ASP.NET templates. So there is no `.vscode` folder generated or any other, similar IDEs. We have discussed generation of VSCode compatible content. The ASP.NET projects are not shipping with any kind of presumed project or solution file.
So for example a folder with a content generated with `yo aspnet` is picked up as `project` when opened in VScode or Atom editor - when OmniSharp C# plugin finds top-most `project.json` file. The user is eventually asked to choose a `project.json` if a root directory contains multiple directories and multiple `project.json` files.

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
