### ISSUE TITLE
Unexpected end of json chrome

### ISSUE THREAD

**Issue by aborderon** [OmniSharp/generator-aspnet#832]
Hi, 

I installed an MVC application with generator-aspnet (WebApplication).
When I run the application with firefox by default, the application works well.
But when I run the application with Chrome by default, I have the error "unexpected end of json chrome" and my application is broken.

![capture du 2016-10-14 16-10-05](https://cloud.githubusercontent.com/assets/6728728/19390526/c11a8efc-9228-11e6-8a30-6909e1dafd36.png)

I can not find the error, I guess the error because "}" is missing but I just initialized the project with the command "yo aspnet".

Thank you for your help.
Sorry for my english, i'am french ;)
cordially

**Comment by peterblazejewicz** [comment]
Can you try to run the same app using terminal/console only?
```bash
dotnet restore
dotnet run
```
I'd like to see output with the error after initial Kestrel output:
```
dotnet run
Project WebApplicationBasic (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
Compiling WebApplicationBasic for .NETCoreApp,Version=v1.0
Bundling with configuration from /Users/piotrblazejewicz/development/WebApplicationBasic/bundleconfig.json
Processing wwwroot/css/site.min.css
  Bundled
  Minified
Processing wwwroot/js/site.min.js
  Bundled

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.5120857
 (The compilation time can be improved. Run "dotnet build --build-profile" for more information)

Hosting environment: Production
Content root path: /Users/piotrblazejewicz/development/WebApplicationBasic
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
...
`

**Comment by Adrienb16** [comment]
Thank for your reply.

Yes, I try to run my app using terminal and when i run chrome to show application, my app work perfectly.

The output of Kestrel is :
```
Project notitia_web (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
Compiling notitia_web for .NETCoreApp,Version=v1.0
Bundling with configuration from /home/adrien/workdir/notitia/notitia_web/bundleconfig.json
Processing wwwroot/css/site.min.css
  Bundled
  Minified
Processing wwwroot/js/site.min.js
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:05.4491290
 (The compilation time can be improved. Run "dotnet build --build-profile" for more information)
```

But when i run my app for ".Net Core Launch (Web)" in Chrome, it does not work and i see my previous error.

**Comment by peterblazejewicz** [comment]
@Adrienb16 I would like to see entire output after you type `dotnet run` copied from console - when you run it in Chrome. There will be output messages for any error or warning - something that should help here .

**Comment by wladioh** [comment]
I have been the same problems

It is my ouput after run on Vs code in web mode :
`
1: (4669) ->~"      Finished handling request.\n"
E output: {"category":"stdout","output":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Market.Api.Helpers.UnitOfWorkMiddleware[0]\n","data":null,"type":"output"}
info: Market.Api.Helpers.UnitOfWorkMiddleware[0]
E output: {"category":"stdout","output":"      Finished handling request.\n","data":null,"type":"output"}
      Finished handling request.
1: (4697) ->=library-loaded,id="{50cab8f4-5309-4dcd-97a4-a7512630cab8}",target-name="/home/wladimir/.nuget/packages/System.Runtime.CompilerServices.Unsafe/4.3.0/lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",host-name="/home/wladimir/.nuget/packages/System.Runtime.CompilerServices.Unsafe/4.3.0/lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",symbols-loaded="0",base-address="0x7fe3f7b95000",size="24576"
E output: {"category":"console","output":"Loaded '/home/wladimir/.nuget/packages/System.Runtime.CompilerServices.Unsafe/4.3.0/lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll'. Cannot find or open the symbol file.\n","data":null,"type":"output"}
Loaded '/home/wladimir/.nuget/packages/System.Runtime.CompilerServices.Unsafe/4.3.0/lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll'. Cannot find or open the symbol file.
1: (4747) ->~"Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 874.573ms 404 \n"
E output: {"category":"stdout","output":"Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 874.573ms 404 \n","data":null,"type":"output"}
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 874.573ms 404 
1: (4756) ->~"info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]\n"
1: (4756) ->~"      Request finished in 874.573ms 404 \n"
E output: {"category":"stdout","output":"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]\n","data":null,"type":"output"}
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
E output: {"category":"stdout","output":"      Request finished in 874.573ms 404 \n","data":null,"type":"output"}
      Request finished in 874.573ms 404 `
