### ISSUE TITLE
Deployment to azure is not working

### ISSUE THREAD

**Issue by thinking-twins** [OmniSharp/generator-aspnet#836]
Deploying any .net core based project to azure suddenly stopped working today. Looks like a global.json is required to downgrade the SDK kudu uses for building/publishing.

It's not the generators fault, maybe helps some people looking for this issue. might be fixed by azure within the next days as well.

See http://stackoverflow.com/questions/40650681/net-core-azure-deployment-failing-project-file-does-not-exist

### How to reproduce

1. create new web app in azure
2. enable local git source

3. yo aspnet -> create Empty Web Application
4. git remote add origin https://user@***.scm.azurewebsites.net:443/***.git
5. git push

Deployment fails with the message: MSBUILD : error MSB1009: Project file does not exist.

### How to fix

following MatthieuGD's fix on SO seems to work:

add global.json to the root folder (where project.json lives) with the following content:

`{
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}`
----
#### Yeoman version 1.4.8, Generator: 0.2.4

**Comment by thinking-twins** [comment]
See PR #418 as well

**Comment by peterblazejewicz** [comment]
@thinking-twins #418 is unrelated - there was an effort to create *project-like* solution to work with  sets of dotnet core projects: https://github.com/aspnet/Tooling/issues/369

Your one seems to be more like Kudu service problem, e.g. like this one: https://github.com/projectkudu/kudu/issues/2083
Could you repost your current problem there?
I've been always publishing web sites to Azure only with 'project.json', without `global.json`, like this one:
https://github.com/peterblazejewicz/polymer-shop-azure
I'm using my own deploy scripts usually, like this one:
https://github.com/peterblazejewicz/polymer-shop-azure/blob/develop/deploy.cmd

When you repost on Kudu, can you post there output of manual run of `deploy.cmd` run from Kudu CLI console?
Thanks!

**Comment by thinking-twins** [comment]
@peterblazejewicz you're totally right. i would see this issue more as an informal one until things got fixed.

i was also publishing all my web apps with `project.json` only. This worked like a charm ... till yesterday :D

I hope the azure team is going to fix this issue but for now all generated projects using just the project.json file cannot be deployed (At least me and some other guys on SO experienced this).

**Comment by peterblazejewicz** [comment]
https://github.com/aspnet/Templates/issues/716

**Comment by stewartadam** [comment]
What's the current status of this?

Based on what I can pull together form the issue queue, the [Version Info](https://github.com/OmniSharp/generator-aspnet/wiki/Version-info) page it sounds like 0.3.0 will support csproj-based projects but those using the current generators will experience deployment failures on Azure, and have been for about two months now.

Unless 0.3.0 is due for release very soon, why not make a small patch release to include global.json in the mean time?

**Comment by peterblazejewicz** [comment]
@stewartadam 
Can you verify that adding global.json on the same directory would work?
This could be achieved in two different ways:
- patching generators to always create `global.json` with other content
- adding `globaljson` subgenerator to create currend sdk configured `global.json` in the current CMD directory

**Comment by stewartadam** [comment]
I can confirm, adding `global.json` in the root (alongside `project.json`) with a version string as noted by the issue reporter fixes the issue for Azure App Service deployments.
