### ISSUE TITLE
Update Console app to match vs2017 RC release

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#838]
We recently released VS2017 RC, we should update the content from yo aspnet to match VS2017 RC. The files for this template are located at: https://github.com/sayedihashimi/aspnettemplates/tree/vs2017rc/samples/ConsoleApp1.

**Comment by peterblazejewicz** [comment]
closed via: 2601b0eef37023d60a44632c386b530d93fb2cc7
