### ISSUE TITLE
Add MSTest project template to match vs2017 RC

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#845]
We recently released VS2017 RC, there we added a new template for MSTest. We should also add that here  to match VS2017 RC. The files for this template are located at: https://github.com/sayedihashimi/aspnettemplates/tree/vs2017rc/samples/UnitTestProjectMSTest

**Comment by peterblazejewicz** [comment]
closed via: 	a95f2db
