### ISSUE TITLE
Did dnu replaced dotnet command?

### ISSUE THREAD

**Issue by alvirtuoso** [OmniSharp/generator-aspnet#850]
### Short issue description
I reinstalled the generator but now I got prompted to use 'dnu restore' instead of 'dotnet restore' for available commands. Is this normal?

### Steps to reproduce the behavior

----
#### OS version (Win/Mac/\*Nix?)
Mac Sierra

#### NodeJS version
 5.10
node --version
```


#### Yeoman version
1.8.5
yo --version
```

#### Generator version
NPM 3.8.*:
```
npm list -g generator-aspnet
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
> I reinstalled the generator but now I got prompted to use 'dnu restore' instead of 'dotnet restore' for available commands. Is this normal?

No. This is not normal. Do you use or had used NVM or similar Node version manager? I had such problem when with NPM global modules taking over managed ones (NVM creates synlinks NPM for each Node version used).

**Comment by alvirtuoso** [comment]
@peterblazejewicz , Thanks for sending me to right direction.
 I uninstalled NVM but that also removed my node so I just did a clean uninstall for both node & npm by following instructions here at https://gist.github.com/DanHerbert/9520689  which says to run the following 2 steps:
1)
rm -rf /usr/local/lib/node_modules
brew uninstall node
brew install node --without-npm
echo prefix=~/.npm-packages >> ~/.npmrc
curl -L https://www.npmjs.com/install.sh | sh

2)
then edit ~/.bash-profile by adding
export PATH="$HOME/.npm-packages/bin:$PATH"


Finally, I Reinstalled the yo and generator which now works as expected.

Thank you!

**Comment by peterblazejewicz** [comment]
You're welcome!
