### ISSUE TITLE
Dockerfile should not use FROM microsoft/dotnet:latest

### ISSUE THREAD

**Issue by mauricedb** [OmniSharp/generator-aspnet#851]
### Short issue description

The generated Dockerfile uses the `FROM microsoft/dotnet:latest` to indicate the source image. If there is a `microsoft/dotnet:latest` Docker image available it will use that one even if it is not the correct version.

On my laptop the `microsoft/dotnet:latest` tag pointed to a Docker image with Core CLR 1.0.1. This results in an error when doing a `docker build` where the build stops with `The command 'dotnet restore' returned a non-zero code: 139`

### Expected behavior

The Dockerfile to specify the correct version of the base image with `FROM microsoft/dotnet:1.1.0-sdk-projectjson`. This results in a correct build and image.

### Actual behavior
Docker builds using whatever image is tagged `microsoft/dotnet:latest` and fails if this is not correct.

### Steps to reproduce the behavior

1. Make sure you have a docker image with CLR 1.0.1 tagged as latest. Im my case this was image with ID 773ea153b89f
1. Create a new Web Application with `yo aspnet`. I used the Web Application Basic [without Membership and Authorization] but the same appears to be true for other options.
1. Run `docker build -t oops .`
1. Observe the output:
`
Step 1/7 : FROM microsoft/dotnet:latest
 ---> 773ea153b89f
Step 2/7 : COPY . /app
 ---> Using cache
 ---> ded8cf51581e
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> 6f4a26c24ce3
Step 4/7 : RUN dotnet restore
 ---> Running in 4db0a5b620d8
log  : Restoring packages for /app/project.json...
The command 'dotnet restore' returned a non-zero code: 139
`

----
#### OS version (Win/Mac/\*Nix?)
Windows 10

#### NodeJS version
v6.9.0

#### Yeoman version
1.8.5

#### Generator version
generator-aspnet@0.2.5

**Comment by peterblazejewicz** [comment]
@mauricedb 
Should it be based on this samples referenced in following commit?
https://github.com/dotnet/dotnet-docker-samples/commit/7fd0e4f2a1239ba5526b31f9cd3f9f1370f19425
https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-current
Also it seems the project should create Windows container Dockerfile version (Dockerfile.nano)
https://github.com/dotnet/dotnet-docker-samples/blob/master/dotnetapp-current/Dockerfile.nano

**Comment by mauricedb** [comment]
@peterblazejewicz 

The Docker sample use `FROM microsoft/dotnet:1.1-runtime` which makes for a much smaller Docker container but does require the project to be build first and the DLL to be run with `ENTRYPOINT ["dotnet", "dotnetapp.dll"]`. I would advise to use `runtime` when deploying but during development I would use `FROM microsoft/dotnet:1.1.0-sdk-projectjson` where I can just rebuild the container.

I completely agree about adding the Windows Nano container Docker file. I am running The Docker for Windows beta 31 and the nano container works just fine if a bit slower. The only thing you need to know for now is that you need to use the Container IP address instead of localhost to send an HTTP request to it. But that is just a temporary Docker bug.

Let me know if you prefer runtime or SDK and I will create a PR.

**Comment by peterblazejewicz** [comment]
Thanks for the update! Yes, I think there should be Windows container version ouf-of-the-box
