### ISSUE TITLE
[Feature Request?]Scaffolding controller with EF Core Model using yo aspnet:mvccontroller

### ISSUE THREAD

**Issue by ssjsk** [OmniSharp/generator-aspnet#857]
### Short issue description
Scaffolding a ASP.NET MVC Controller in Mac OSx using yo aspnet:mvccontroller doesn't support passing of Model, Layout file parameters like Visual Studio 2015/2017 does in order to generate CRUD views and db migration definition. I'm using Visual Studio Code directly on OSx Yosemite and not Windows virtual machine.

### Expected behavior
Ideally it'll be useful if a migration for passed model, CRUD action methods in controller and corresponding views were generated from command line as part of scaffolding.
Visual Studio 2015/17 have something like attached screenshot while adding a controller with scaffolding https://s27.postimg.org/ipfpqhvoj/Screen_Shot_2016_12_26_at_6_12_11_PM.png
### Actual behavior
A controller is generated in current path from where I run yo aspnet:mvccontroller ControllerName with Index() method.

### Steps to reproduce the behavior
1. create a new ASP.NET Web Application in Mac OSX using yo aspnet generator
2. add a controller 

----
#### OS version (Win/Mac/\*Nix?)
Mac OSx - Yosemite

#### Yeoman version
current stable version for Mac OSx

**Comment by peterblazejewicz** [comment]
design notes:
- `.yo-rc` support in-place of `project.json` (which is phased-out actually to `.csproj`)
- `.yo-rc` can be used as root of the project (the `yo` always correctly resolves where the content should be created using `.yo-rc` as root convention:
http://yeoman.io/authoring/storage.html
https://github.com/yeoman/generator/blob/244c92cfd622852326f8d6592dc6aa18dc560316/lib/index.js#L123-L126

**Comment by ssjsk** [comment]
I found out that yeoman aspnet generator already supports scaffolding MVC Controller with support for CRUD view and EF model, just that information for OSx wasn't available readily.  Following is syntax for achieving so

dotnet aspnet-codegenerator --project /Users/coreapps/CoreWebApp2 controller --force --controllerName MoviesController --model CoreWebApp2.Models.Movie --dataContext CoreWebApp2.Data.ApplicationDbContext --relativeFolderPath Controllers --controllerNamespace CoreWebApp2.Controllers --useDefaultLayout
