### ISSUE TITLE
phase out `--skip-install` option 

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#86]
Usually the commonly used `--skip-install` option in Yeoman generators is used to not perform dependencies installation after content has been created.
For example:
`generator-angular`:
https://github.com/yeoman/generator-angular/blob/master/app/index.js#L315-L324
`generator-webapp`:
https://github.com/yeoman/generator-webapp/blob/master/app/index.js#L201-L206

and they all are based around idea of built-in feature:
https://github.com/yeoman/generator/pull/205

Our generator currently does nothing really that important to be at all mentioned or used in code:
https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L287-L295

This option has a lot of sense in older releases:
https://github.com/OmniSharp/generator-aspnet/commit/a83d7e8889972b9a310fd36a265203236897fddc#diff-2018087f584c4398b5c3a23fc0e5f9dbR91
as it was used in the same context and based on similar concept.

I think it should be now removed from help text (and from code check) as we do not perform anything related at the current state and people should always see final *all is good* + short *what next* message (so it can be a sign that everything ended OK).

Thanks!

**Comment by sayedihashimi** [comment]
+1

**Comment by peterblazejewicz** [comment]
x-ref: https://github.com/OmniSharp/generator-aspnet/pull/90
