### ISSUE TITLE
Don't allow a dot in the project name as it causes build failures.

### ISSUE THREAD

**Issue by VishalMadhvani** [OmniSharp/generator-aspnet#860]
yo aspnet --version
1.8.5

**Comment by peterblazejewicz** [comment]
This is common pattern in C# I believe to have `MyWebApp.Client` or `MyWebApp.Service`, etc naming convention and 
```shell
What type of application do you want to create? Empty Web Application
? What's the name of your ASP.NET application? MyApp.Web
```
We need use-case of your failure. Thanks!

**Comment by VishalMadhvani** [comment]
of course it is!! sorry posted that during a dim moment :(

"bla.1" for example doesn't work... but probably not worth the effort to validate.
feel free to close this.
