### ISSUE TITLE
Docker file generated improperly

### ISSUE THREAD

**Issue by unjello** [OmniSharp/generator-aspnet#869]
### Short issue description
Docker file is created with /app folder by default as working directory, while name of the folder should be equal to application name[1], e.g. /WebApplication

[1] https://github.com/aspnet/Mvc/issues/4306

### Expected behavior
ASP.NET Core MVC Application runs inside docker.

### Actual behavior
Kestrel throws: Cannot resolve TagHelper containing assembly 'WebApplication'. Error: Could not load file or assembly 'WebApplication, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified

### Steps to reproduce the behavior
build and run docker for newly generated "WebApplication" straight from template.
yo aspnet
Web Application
cd WebApplication
docker build -t webapp .
docker run -it -p 5000:5000 webapp

----
#### OS version (Win/Mac/\*Nix?)
macOS Sierra 10.12.3
docker image runs:
Linux ed75c1ec383d 4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017 x86_64 GNU/Linux

#### NodeJS version
v7.4.0

#### Yeoman version
1.8.5

#### Generator version
/usr/local/lib
└── generator-aspnet@0.2.6

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
