### ISSUE TITLE
Replace documentation animated gif with one covering recent version

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#87]
We are using outdated GIF showing old version with old install behavior (automatic deps installation) and old content (old WebApplication content)

Can we update it to newer version, crafted to desired results? (hey, let's show people how easy is to create MVC project without using MS, cool!)

![aspnet](https://cloud.githubusercontent.com/assets/14539/6697962/a57211ac-ccf4-11e4-97d9-7ed16bb16d37.gif)

**Comment by sayedihashimi** [comment]
+1 please do
