### ISSUE TITLE
Is it possible to use this generator to generate a asp.net mvc 5 project?

### ISSUE THREAD

**Issue by eddeyang** [OmniSharp/generator-aspnet#873]
Hi guys,

I'm new to this project and I want to use asp.net mvc 5 with semantic-ui. I want to know if this generator can help me. I tried to use it and generated a few projects and it seems they are all asp.net core projects. Is that true?

Thanks.

**Comment by peterblazejewicz** [comment]
No, this was crafted for ASP.NET Core.
You would use NuGet packages to install Semantic UI and jQuery and then in your default MVC web site template configure `BundleConfig`:
```.cs
public static void RegisterBundles(BundleCollection bundles)
{
	ScriptBundle thirdPartyScripts = new ScriptBundle("~/scripts/vendor");
	thirdPartyScripts.Include("~/Scripts/jquery-1.8.1.js",
						"~/Scripts/semantic.js");
	bundles.Add(thirdPartyScripts);
	StyleBundle stylesBundleFiles = new StyleBundle("~/styles/vendor");
	stylesBundleFiles.Include("~/Content/semantic.css");
	BundleTable.EnableOptimizations = true;
}
```
(written without VS on Mac, so there could be some corrections required)
https://www.asp.net/mvc/overview/performance/bundling-and-minification

**Comment by eddeyang** [comment]
Thank you Peter!
