### ISSUE TITLE
Is it possible to create specific generators i.e. Starter Web so they can be forked and modded?

### ISSUE THREAD

**Issue by xtianus79** [OmniSharp/generator-aspnet#88]
I would like to combine my scaffolding with an ASP.net generator but that won't be possible unless there is some focus.  Could you guys/gals create forks of the most popular templates so they can more concise in file structure and combined with other projects? 

Thanks.

**Comment by peterblazejewicz** [comment]
@xtianus79 which other project templates? Do you mean something like home project templates?
https://github.com/aspnet/Home/tree/master/samples
Thanks!

**Comment by xtianus79** [comment]
@peterblazejewicz I would like to have the template for C# web Starter Web... is that possible?

**Comment by xtianus79** [comment]
Also @peterblazejewicz what node.js versions does this iteration of VS Vnext actually use?  seems to be in clonflict with my node.js 0.12.0

**Comment by spboyer** [comment]
@xtianus79 the package.json file spcifies node.js version >= 0.10 
https://github.com/OmniSharp/generator-aspnet/blob/master/package.json#L37-L38

**Comment by xtianus79** [comment]
@spboyer so can this be changed to 0.12?  moreover... I have 0.12 installed on my machine... is there a way to change the engine that VS is using?  thanks

**Comment by xtianus79** [comment]
Wait I just rethought that... the setting is saying this needs to run on node.js .10 or later. doesn't mean that is what VS is running on.  is this an official answer?

**Comment by spboyer** [comment]
@xtianus79 the generator needs to run on nodejs >= 0.10, it is unrelated to VS. You don't Visual Studio to run this, change the output, compile, or build and view. Just the ASPNET runtime or KLR. Which is also now known as DNX.

**Comment by xtianus79** [comment]
No im asking what node does vs vnext have baked in?. What version is it running or at least looking for.  Perhaps I said that wrong.

Sent from my Windows Phone
________________________________

**Comment by xtianus79** [comment]
so is this possible?

**Comment by sayedihashimi** [comment]
@xtianus79 it's not clear to me what your question/suggestion is. Can you be more specific?

>I would like to have the template for C# web Starter Web

In the generators the [web template](https://github.com/OmniSharp/generator-aspnet/tree/master/templates/projects/web) is equivalent to the Starter Web template

You can fork this repo and modify that if you like.

>No im asking what node does vs vnext have baked in?. What version is it running or at least looking for. Perhaps I said that wrong.

In Visual Studio I modified ```project.json``` to include the following in the scripts section to the following.

```json
"scripts": {
    "postrestore": [ "node -v" ]
}
```

The result printed in the ```Package Manager Log``` was ```v0.10.31```.

**Comment by xtianus79** [comment]
@sayedihashimi thanks for the reply. 2 things. 

1.  https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/_gruntfile.js <<< yes I can deal with that.  Awesome!!!

So basically I can use the generator and use this template<<< is this template connected to the generator or is this separate unto itself?  

2.  is there an official way to change this to use the node that is installed globally on the system?

**Comment by xtianus79** [comment]
@sayedihashimi 

this is my print out... Resolving complete, 7127ms elapsed
npm WARN package.json @0.0.0 No description
npm WARN package.json @0.0.0 No repository field.
npm WARN package.json @0.0.0 No README data
v0.10.31

when I right click on NPM and choose configure external tools it comes to the choice to edit the "External Web tools" 

I unchecked the first box which is .node_modules\.bin and then added C: \Program Files\Nodejs and hit ok and I still get the information from above... no change seems to take affect.

**Comment by xtianus79** [comment]
@sayedihashimi @spboyer Ok I am going to clone the project now and try to implement my bits and setup from here... it i can get it working it would be amazing.

**Comment by sayedihashimi** [comment]
@xtianus79 this repository is for the asp.net 5 yeoman generators. This is not the right place for getting info on how VS interacts with node/grunt. I noticed that Mads published a blog today at http://blogs.msdn.com/b/webdev/archive/2015/03/19/customize-external-web-tools-in-visual-studio-2015.aspx which relates to that. That seems like a good place to ask those questions.

**Comment by xtianus79** [comment]
yes you are correct and the blog post worked out perfectly.  Thanks!

Date: Thu, 19 Mar 2015 13:41:56 -0700

**Comment by peterblazejewicz** [comment]
@xtianus79 So are you satisfied with responses? Can we go and close this issues?

**Comment by xtianus79** [comment]
@peterblazejewicz Yes thanks.
