### ISSUE TITLE
Subgenerators cleanup for RC

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#891]
The update for RC is a great occasion to remove some subgenerators that IMO are just adding a noise to the content:

- angularcontroller
- angularcontrolleras
- angulardirective
- angularfactory
- angularmodule
- bowerjson
- coffeescript
- gruntfile
- gulpfile
- htmlpage
- javascript
- json
- jsonschema
- jsx
- packagejson
- stylesheet
- stylesheetless
- stylesheetscss
- textfile
- tfignore
- typescript
- typescriptconfig
- typescriptjsx

They are either outdated, have disputable value or can be easily replaced by relevant tools (`bower init`, `npm init -y`, `tsc init` as in case of configuration files).

Thanks!

@OmniSharp/generator-aspnet-team-push

**Comment by spboyer** [comment]
i agree these are noise and unrelated to [overall goals of the generator](https://github.com/OmniSharp/generator-aspnet/wiki/goals-and-related-generators)

@sayedihashimi

**Comment by peterblazejewicz** [comment]
Exemplification of the removal:
https://github.com/OmniSharp/generator-aspnet/pull/892

**Comment by sayedihashimi** [comment]
:shipti:

**Comment by peterblazejewicz** [comment]
closed via:  cb75646 

I've added comment to commit about way to bring specific template/subgenerator back

**Comment by peterblazejewicz** [comment]
Reopen this topic as the RC4 has been pushed to public already:
https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/

**Comment by peterblazejewicz** [comment]
closed (again) via: 	af33b27
