### ISSUE TITLE
[Possible Bug] Can't seem to run Yeoman generate project on Heroku

### ISSUE THREAD

**Issue by AbhimanyuAryan** [OmniSharp/generator-aspnet#926]
The empty DotNetCore project generated using Yeoman doesn't run on Heroku where as the project generated using `dotnet new -t web` seems to run on Heroku strange. Please refer to this [issue](https://github.com/friism/dotnet-buildpack/issues/4) I have created on Built-pack repo

Also as suggested by @halter73 [here](https://github.com/aspnet/KestrelHttpServer/issues/1357) it's some razor issue. Please let me know if this is some issue related to generator or there's fix to it?

**Comment by peterblazejewicz** [comment]
@AbhimanyuAryan 
Which versions you're using? There are now multiple version both of Yo generator and dotnet. Your screenshots suggest you're using pre RC4 dotnet (one with .csproj support):
https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/

**Comment by peterblazejewicz** [comment]
cross-post: https://github.com/aspnet/Razor/issues/994

**Comment by AbhimanyuAryan** [comment]
@peterblazejewicz I was using RC4 both then I removed it & installed 

```
dotnet --version
1.0.0-preview2-1-003177
```

but yeoman still seems to use RC4...How can make it generate .json project?

**Comment by peterblazejewicz** [comment]
@AbhimanyuAryan 
```bash
npm install -g genator-aspnet@0.2.6
```
This will install version supporting content with `project.json`

**Comment by AbhimanyuAryan** [comment]
& what's the generator for 1.0.0-rc4-004771? I have upgrade my dotnet sdk to .csproj

**Comment by peterblazejewicz** [comment]
> what's the generator version for 1.0.0-rc4-004771? I have upgrade my dotnet sdk to .csproj

just the latest:
```
npm install -g generator-aspnet
```
```
npm install -g generator-aspnet@latest
```
(both above should install 0.3.1 version)

**Comment by AbhimanyuAryan** [comment]
Figured out there's some error with default template that yo aspnet generate using semantic UI

Bootstrap app generated by YO: https://obscure-escarpment-47381.herokuapp.com/
Semantic UI app generated by YO: https://floating-lake-33641.herokuapp.com/

Bootstrap app: https://github.com/ivdstudios/YoBootStrap
Semantic app: https://github.com/ivdstudios/YoSemanticUI

**Comment by peterblazejewicz** [comment]
> I changed the Layout file manually & app seems to run.

So what was changed? And in which version (0.2.* or 0.3.*) content?

**Comment by AbhimanyuAryan** [comment]
pasted HTML for _Layout.cshtml from this [post](http://www.khalidabuhakmeh.com/using-semantic-ui-with-asp-net-core) and it magically worked

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
