### ISSUE TITLE
Cant project in visual studio

### ISSUE THREAD

**Issue by MKI-Miro** [OmniSharp/generator-aspnet#931]
### Short issue description
When I try to open csproj file i got this error

The default XML namespace of the project must be the MSBuild XML namespace.....

I have VS 2015 community update 3

### Expected behavior

Open new project

### Actual behavior

Cant open project

### Steps to reproduce the behavior
Just create project project with yeoman and open it.

----
#### OS version (Win/Mac/\*Nix?)

Windows 10

#### Dotnet version

```bash
dotnet --info
1.0.0-preview2-003131

#### NodeJS version
```
node --version
6.9.4

#### Yeoman version
```
yo --version
1.8.5


#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet
generator-aspnet@0.3.1
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
Hi @MKI-Miro 
Unfortunately this cannot be corrected as MS does not support .csproj in VS 2015 yet (at least now):
https://github.com/OmniSharp/generator-aspnet/issues/927#issuecomment-281482505
https://github.com/dotnet/cli/issues/5725

**Comment by sayedihashimi** [comment]
Correct the .csproj for .NET Core is only supported in VS2017. Closing this now.
