### ISSUE TITLE
The target "Restore" does not exist in the project

### ISSUE THREAD

**Issue by jaredcnance** [OmniSharp/generator-aspnet#932]
### Short issue description
Just upgraded to the latest generator version and installed the latest .Net Core SDK (1.0.0-preview3-004056) and can't even `dotnet restore` the fresh application.

### Expected behavior
The generator + SDK should just work.

### Actual behavior
Can't restore or build out of the box. Restore fails with error:
```
.../test/test.csproj : error MSB4057: The target "Restore" does not exist in the project.
```

### Steps to reproduce the behavior
- Download latest generator (0.3.2)
- Download latest SDK (1.0.0-preview3-004056)
- `yo aspnet:app webapi test`
- `cd test && dotnet restore`

----
#### OS version (Win/Mac/\*Nix?)

Mac Sierra 10.12

#### Dotnet version

```bash
dotnet --info

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

#### NodeJS version
```
node --version
v6.7.0
```

#### Yeoman version
```
yo --version
1.8.5
```

#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

0.3.2

**Comment by jaredcnance** [comment]
upgrading to rc4 fixed the issue

https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md

**Comment by peterblazejewicz** [comment]
@jaredcnance Thanks for future reference link!
