### ISSUE TITLE
Subgenerators are not available

### ISSUE THREAD

**Issue by DesktopMan** [OmniSharp/generator-aspnet#934]
### Short issue description

Installed yo and generator-aspnet through npm. Ran yo aspnet --help. I don't see the full list of sub generators.

### Expected behavior

See a bunch of subgenerators like aspnet:webapiontroller and aspnet:mvccontroller.

### Actual behavior

```
Subgenerators:

  yo aspnet:nugetconfig [options]
  yo aspnet:webconfig [options] <name>
```

### Steps to reproduce the behavior
```
npm install -g yo generator-aspnet
yo aspnet --help
```

#### OS version (Win/Mac/\*Nix?)
Ubuntu 16.10

#### Dotnet version
1.0.1

#### NodeJS version
v4.2.6

#### Yeoman version
1.8.5

#### Generator version
0.3.2

**Comment by peterblazejewicz** [comment]
Hi @DesktopMan 

The subgenerators were mostly entirely removed from generator during migration to RC version (now 0.3.* on NPM):
https://github.com/OmniSharp/generator-aspnet/issues/891
There was a hug maintaince burdern and there was no upstream reference repository for most of them (for example for C# controllers). The content in current version of generator is aligned with two other projects: https://github.com/dotnet/templating and https://github.com/aspnet/Templates now (so there is a subgenerator for items like nuget or web.config)
Thanks!

**Comment by DesktopMan** [comment]
I see. That's really unfortunate as you can already generate the basic project types with dotnet new. generator-aspnet went from must have to not that useful without the subgenerators. Hopefully aspnet/Templates will add more templates once the dotnet new templating is expanded.

**Comment by ruidfigueiredo** [comment]
Is there any alternative to the subgenerators that were removed if you are in Linux?

**Comment by peterblazejewicz** [comment]
@ruidfigueiredo 
I'm on *nix platform most of the time, so I know the problem well. Yes, the individual item templates can be just reintroduced into generator via PR. 
The broader discussion on items/projects templating and community involvement is currently channeled through this repo:
https://github.com/dotnet/templating/issues
(just search for item templates and scaffolding topics in isssues)

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
