### ISSUE TITLE
Can not bundle Js and css file in aspcore/angular2

### ISSUE THREAD

**Issue by Lekinio** [OmniSharp/generator-aspnet#936]
### Short issue description
hello,i wan to bundle my css and js files with webpack but when i am trying its outputs files in dist but site does not have any effect

### Steps to reproduce the behavior
in webpack.config.vendor.js
```
 entry: {
            vendor: [
                '@angular/common',
                '@angular/compiler',
                '@angular/core',
                '@angular/http',
                '@angular/platform-browser',
                '@angular/platform-browser-dynamic',
                '@angular/router',
                '@angular/platform-server',
                'angular2-universal',
                'angular2-universal-polyfills',
                'bootstrap',
                'bootstrap/dist/css/bootstrap.css',
                'es6-shim',
                'es6-promise',
                'event-source-polyfill',
                'jquery',
                'zone.js',
            ],
            mine: [
                "./ClientApp/dist/mine.js",
            ]
        },
```

i am calling it in index.cshtml
<script src="~/dist/mine.js" asp-append-version="true"></script>

----
#### Dotnet version

```bash
dotnet --info
```

#### NodeJS version
```
node --version
```

#### Yeoman version
```
yo --version
```

#### Generator version
NPM 3.*:
```
npm list -g generator-aspnet
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

**Comment by peterblazejewicz** [comment]
This project content (just like one on @dotnet/templating ) does not support webpack bundler by default.
That project:
https://github.com/aspnet/JavaScriptServices
ships with generator that creates .NET web projects that support Webpack as bundler for client side code

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
