### ISSUE TITLE
Bower is deprecated

### ISSUE THREAD

**Issue by rogersachan** [OmniSharp/generator-aspnet#940]
See https://github.com/bower/bower/issues/2298 and https://bower.io/ .

I suggest using node for front-end scripts.

**Comment by peterblazejewicz** [comment]
We could rewrite it here (i'm using solely Yarn (NPM) + WebPack, unless there is obvious need for Bower like with Polymer project libraries) - but the problem with MS not having a clean stance on this topic I think. I'll repost the problem to aspnet/home and dotnet/templating
Thanks!

**Comment by peterblazejewicz** [comment]
x-ref: https://github.com/dotnet/templating/issues/840

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
