### ISSUE TITLE
double '<' character in csproj files

### ISSUE THREAD

**Issue by ylaguna** [OmniSharp/generator-aspnet#941]
Hello!

I started learning dotnet core few days ago and found this package.

I started by creating a dotnetcore webapplication in 1.1 framwork and came across this error message.

> Testa.csproj(30,6): error MSB4025: The project file could not be loaded. Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 30, position 6.

When I manually remove the double '<' the "restore" and "build" proceed normally...

I think the right solution is removing the doubled '<' from CompanyWebApplication1.* files

changing this:

`<<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />`

to:
`<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />`

**Comment by peterblazejewicz** [comment]
Thanks for the report! The fix is submitted.
