### ISSUE TITLE
Error when using --version-current

### ISSUE THREAD

**Issue by thanhnntq** [OmniSharp/generator-aspnet#943]
### Short issue description
File .csproject maked with misstake at line 4 col 965 and line 2 col 693.
That file have a redundancy character '<'.
Please remove it!

**Comment by peterblazejewicz** [comment]
@thanhnntq which template (which project)? Thx!

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
