### ISSUE TITLE
Upgrade project templates to .NET Core 2.0

### ISSUE THREAD

**Issue by hoobtron** [OmniSharp/generator-aspnet#944]
Hi, I like yo and want to use generator-aspnet with an ASP.NET Core 2.0 WebApi project.

Does it make sense to wait for an upgrade?

**Comment by peterblazejewicz** [comment]
@hoobtron 
I think you should use official `dotnet new` scaffolding tool in your  projects. If you are using the latest 2.0 (final) release, you will get the latest content:
https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
