### ISSUE TITLE
Deprecate generator-aspnet package

### ISSUE THREAD

**Issue by svick** [OmniSharp/generator-aspnet#948]
At this point, `yo aspnet` is significantly outdated. But some old tutorials still use it, so I think it would be nice to discourage its use.

Probably the best way would be to deprecate the generator-aspnet package, with a message pointing to `dotnet new`.

**Comment by peterblazejewicz** [comment]
@svick thx!

@sayedihashimi can you still do this and publish deprecate to NPM?
https://docs.npmjs.com/cli/deprecate

**Comment by sayedihashimi** [comment]
Sorry for the delay. I have marked it deprecated.

What should we do in the repo? I was thinking the following:
 - Update readme letting people know to use `dotnet new`
 - Close all open issues

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Archive repo:
https://help.github.com/articles/about-archiving-repositories/
That's best user friendly way I think,

**Comment by sayedihashimi** [comment]
Thanks, the issues have been closed out as well as the only open PR. I just updated the Readme and now I'll archive it.

It was really great working on this project, truly one of the highlights of my career. It makes me sad to archive this, but our goals were achieved in `dotnet new`. I still love templates and likely always will.
