### ISSUE TITLE
Update documentation with short description of generated projects

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#95]
We have new templates, with new content, quite different from content shown on ASP.NET home and MVC projects:
https://github.com/aspnet/Home/tree/master/samples
https://github.com/aspnet/Mvc/tree/dev/samples
```
❯ Empty Application 
  Console Application 
  Web Application 
  Web API Application 
  Nancy ASP.NET Application 
  Class Library 
```
Short note would be efficient - it could be placed prominently on top of Readme.md, so it is spotted first on NPM register, etc.
This was previously covered by outdated and spoiled: 
https://github.com/OmniSharp/generator-aspnet/issues/63

Thanks!

**Comment by spboyer** [comment]
:+1:

**Comment by peterblazejewicz** [comment]
Can we just get content as quote from this blog post introducing CTP6?
http://blogs.msdn.com/b/webdev/archive/2015/02/23/aspnet-5-updates-for-feb-2015.aspx

**Comment by sayedihashimi** [comment]
Sure feel free to copy anything you want from there.
