### ISSUE TITLE
Remove dependency to Gulp from project file

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#96]
I think this is no longer required, maybe it was used locally:
https://github.com/OmniSharp/generator-aspnet/blame/master/package.json#L52
May we remove it?
cc/ @spboyer

**Comment by peterblazejewicz** [comment]
also this one, `fx-extra`?
https://github.com/OmniSharp/generator-aspnet/blob/master/package.json#L51

**Comment by spboyer** [comment]
@peterblazejewicz we can remove both of these dependencies.
