### ISSUE TITLE
The app generators should generate a .gitignore file

### ISSUE THREAD

**Issue by rustd** [OmniSharp/generator-aspnet#98]
The app generator should generate the .gitignore file which will exclude node_modules and bower_components folders.
We could use the following as the default gitignore file https://github.com/github/gitignore/blob/master/VisualStudio.gitignore 
Some of the other generators such as https://github.com/yeoman/generator-webapp do this.

**Comment by peterblazejewicz** [comment]
:+1:
@rustd This one have no relation to current or envisioned ASP.NET project structures unfortunately. 

@sayedihashimi @spboyer 
Can you consider discussing a new project within OmniSharp to work as umbrella project for all kinds of templates for ASP.NET? The VS comes without support for range of tools (still) while people use them all the time, e.g. at work. These could be `.gitignore`, `.gitattributes`, `.editorconfig` (those 4 spaces in VS), `.bowerrc`, etc.
We could later reuse that templates here to fulfil @rustd proposal.

**Comment by sayedihashimi** [comment]
@peterblazejewicz are you saying that VS should add the file first and then we will add it? I'm not following your comment above.

As @rustd stated generator-webapp does drop a .gitignore file in the project directory. The contents are below.

```
node_modules
dist
.tmp
bower_components
```

For this generator I think we could start with the following.

```
node_modules
bower_components
```

Thoughts?

@rustd if we are saying that the yo generators should place a ```.gitignore``` in the root then likely we should do the same for Visual Studio. I guess the only tricky part there is that the project may be checked into TFS (or some other version control system). But the same goes with yo, but it's far more likely that git is being used.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I meant something similar to HTML5 boilerplate set of default files:
https://github.com/h5bp/html5-boilerplate/tree/master/src
Some of them can be actually empty and works as best-practise only samples:
https://github.com/h5bp/html5-boilerplate/blob/master/src/.gitignore

**Comment by xtianus79** [comment]
@sayedihashimi I totally agree that a .gitignore file should be included... and yes the options of node_modules
.tmp 
bower_components should be included... and then per template could define others if needed... 

but it should be an accessible file because certain packages need things to be ignored.  Every case is different.

**Comment by rustd** [comment]
@sayedihashimi VS drops in a gitignore file when you checkin using Git. let's add a .gitignore file

**Comment by peterblazejewicz** [comment]
@rustd @sayedihashimi 
I have an idea - let's make subgenerator also aspnet:gitignore - the sole purpose will be to just create `.gitignore` for VS in current directory.
Can I make a ticket for this?

**Comment by spboyer** [comment]
#112 Submitted @sayedihashimi can you review

**Comment by sayedihashimi** [comment]
@peterblazejewicz 
>I have an idea - let's make subgenerator also aspnet:gitignore - the sole purpose will be to just create .gitignore for VS in current directory.
Can I make a ticket for this?

I created #125 for this.

**Comment by spboyer** [comment]
Ha, i had that done. just didn't check it in yet. Will do now.
